/-
Copyright (c) 2026 Logos Library Formalization Project. All rights reserved.
Released under MIT license as described in the file LICENSE.
Author: Adam Bornemann
Filename: ModularTheory/CrossedProducts/Definition.lean
-/
import Spectra.ModularTheory.TomitaTakesaki
import Mathlib.MeasureTheory.Function.LpSpace.Basic
import Mathlib.MeasureTheory.Function.LpSpace.Complete
import Mathlib.Algebra.Star.Subalgebra
/-!
# The Crossed Product `M ⋊_α ℝ`

Given a von Neumann algebra `M` acting on a Hilbert space `H` with cyclic and
separating vector `Ω`, together with a strongly continuous one-parameter
*-automorphism group `α : ℝ → Aut(M)`, this file constructs the algebraic
skeleton of the crossed product `M ⋊_α ℝ`.

## The Construction

The crossed product acts on `K := L²(ℝ, H)`, the Hilbert space of square-
integrable `H`-valued functions on `ℝ`. It is generated by two families of
bounded operators:

* **The diagonal representation** `π : M → B(K)`, defined by
      `(π(a) ξ)(s) := α_{-s}(a) (ξ(s)).`

* **The translation representation** `U : ℝ → U(K)`, defined by
      `(U(t) ξ)(s) := ξ(s - t).`

These satisfy the **covariance relation**
      `U(t) · π(a) · U(t)* = π(α_t(a))`,
which is the entire reason for the construction: an automorphism `α_t` of
`M` — which is typically *outer*, generating no inner symmetry of `M` itself —
becomes *inner* in the crossed product, implemented by conjugation with the
unitary `U(t)`. The crossed product is, in a precise sense, the minimal
enlargement of `M` in which `α` becomes inner.

## Physics

The case of principal interest is `α = σ^φ`, the modular automorphism group
of a faithful normal state `φ`. Takesaki's theorem then asserts: if `M` is
a Type III₁ factor (the typical case for local algebras in QFT), the crossed
product `M ⋊_{σ^φ} ℝ` is a Type II_∞ factor.

This is the mechanism by which entropy enters quantum field theory in the
presence of gravity. Type III algebras have no trace, hence no density
matrices, hence no `S = -Tr ρ log ρ`. The crossed product, forced upon us by
the gravitational constraints (the Hamiltonian must be treated as a generator
of a gauge symmetry, and adjoining "time" performs exactly the crossed product
construction), supplies a trace and with it a well-defined entropy:

      `S_gen = (Area)/(4G_N) + S_out`.

References for the physics: Witten, "Gravity and the crossed product",
JHEP 10 (2022) 008; Chandrasekaran-Longo-Penington-Witten, "An algebra of
observables for de Sitter space", JHEP 02 (2023) 082.

## Design

This file is the algebraic skeleton only:

1. `RDynamics M` — strongly continuous one-parameter *-automorphism groups.
2. `CrossedSpace H` — the Hilbert space `L²(ℝ, H)`.
3. `DiagonalRep`, `TranslationRep` — the two representations, bundled.
4. `CovariantRep` — the covariance relation packaging both.
5. `RegularCovariantRep` — existence of the canonical example, bundled.
6. `crossedProduct` — the *-subalgebra generated by `π(M) ∪ U(ℝ)`.
7. `inner_implementation` — the theorem that `α_t` is inner in `M ⋊_α ℝ`.

The *von Neumann* crossed product is the WOT/SOT-closure of this
*-subalgebra. Closure is a separate construction; for now we work with the
algebraic crossed product. The dual action, dual weight, Takesaki duality,
and the Type II classification follow in sibling files.

## References

* M. Takesaki, *Theory of Operator Algebras II*, Ch. X.
* A. Connes, *Noncommutative Geometry*, App. V.B.
* E. Witten, "Gravity and the crossed product", JHEP 10 (2022) 008.
* V. Chandrasekaran, R. Longo, G. Penington, E. Witten,
  "An algebra of observables for de Sitter space", JHEP 02 (2023) 082.

## Tags

crossed product, covariant representation, modular flow, Type II, thermal time
-/
open MeasureTheory Complex ContinuousLinearMap
open Spectra.QuantumMechanics.ModularTheory
variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
namespace Spectra.CrossedProduct
/-!
## Section 1: One-Parameter Automorphism Groups

A strongly continuous *-automorphism group of `M` is essentially the same
data as your existing `ModularGroupData`, but with strong continuity and
isometry made explicit. We pull it out as an independent structure since
the crossed product is defined for *any* such group, not specifically the
modular one. The modular case is recovered by feeding in `modularAutomorphism`
together with the consequences of `TomitaTheorem`.
-/

/-- A strongly continuous one-parameter *-automorphism group of a von Neumann
    algebra `M ⊂ B(H)`.

    The group is given as a map `ℝ → (B(H) → B(H))` whose action preserves
    `M`. The full algebraic structure (group law, multiplicativity, *-
    preservation, ℂ-linearity) is required, together with two analytic
    properties: each `α_t` is isometric, and the orbit `t ↦ α_t(a) ξ` is
    continuous for every `a, ξ`. -/
structure RDynamics (M : VNAlgebraWithVector H) where
  /-- The automorphism at time `t`. -/
  α : ℝ → (H →L[ℂ] H) → (H →L[ℂ] H)
  /-- `α_t` preserves `M`. -/
  preserves_algebra : ∀ t (a : H →L[ℂ] H), a ∈ M.algebra → α t a ∈ M.algebra
  /-- Group law: `α_{s+t} = α_s ∘ α_t`. -/
  group_law : ∀ s t a, α (s + t) a = α s (α t a)
  /-- Identity at zero: `α_0 = id`. -/
  at_zero : ∀ a, α 0 a = a
  /-- Multiplicativity: `α_t(ab) = α_t(a) · α_t(b)`. -/
  map_mul : ∀ t a b, α t (a * b) = α t a * α t b
  /-- *-preservation: `α_t(a*) = α_t(a)*`. -/
  map_star : ∀ t a, α t (star a) = star (α t a)
  /-- Additivity: `α_t(a + b) = α_t(a) + α_t(b)`. -/
  map_add : ∀ t a b, α t (a + b) = α t a + α t b
  /-- ℂ-linearity. -/
  map_smul : ∀ t (c : ℂ) a, α t (c • a) = c • α t a
  /-- Isometry: `α_t` preserves the operator norm. -/
  isometric : ∀ t a, ‖α t a‖ = ‖a‖
  /-- Strong continuity: `t ↦ α_t(a) ξ` is continuous for all `a, ξ`. -/
  strongly_continuous : ∀ (a : H →L[ℂ] H) (ξ : H),
    Continuous (fun t => α t a ξ)

/-- `α_t` has inverse `α_{-t}`. -/
lemma RDynamics.inv_eq {M : VNAlgebraWithVector H} (α : RDynamics M) (t : ℝ) (a : H →L[ℂ] H) :
    α.α (-t) (α.α t a) = a := by
  rw [← α.group_law, neg_add_cancel, α.at_zero]

lemma RDynamics.inv_eq' {M : VNAlgebraWithVector H} (α : RDynamics M) (t : ℝ) (a : H →L[ℂ] H) :
    α.α t (α.α (-t) a) = a := by
  rw [← α.group_law, add_neg_cancel, α.at_zero]

/-!
## Section 2: The Crossed Product Hilbert Space

The crossed product acts on `K := L²(ℝ, H)`, which we realize concretely as
the Mathlib `Lp` space of `H`-valued square-integrable functions on `ℝ` with
respect to Lebesgue measure. Mathlib supplies the Hilbert space structure
(norm, inner product, completeness) for this type automatically.
-/

/-- The crossed product Hilbert space `K = L²(ℝ, H)`. -/
noncomputable abbrev CrossedSpace (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℂ H] :=
  Lp H 2 (MeasureTheory.volume : Measure ℝ)

/-!
## Section 3: The Diagonal Representation π

`π : M → B(K)` defined by `(π(a) ξ)(s) = α_{-s}(a) (ξ(s))`.

We bundle the diagonal representation as a structure rather than try to
construct `π` from `α` directly. The construction requires Bochner
measurability of `s ↦ α_{-s}(a) ξ(s)` (which uses strong continuity of `α`
plus measurability of `ξ`) together with the L² bound

      `∫ ‖α_{-s}(a) ξ(s)‖² ds ≤ ‖a‖² · ∫ ‖ξ(s)‖² ds = ‖a‖² ‖ξ‖²`

(the inequality coming from `‖α_{-s}(a)‖ = ‖a‖`). Both ingredients are
standard but their formalization is non-trivial; we defer them.

The algebraic properties (multiplicativity, *, linearity, isometry) hold
strictly on `M.algebra` — outside `M`, `α_{-s}(a)` is not defined, so neither
is `π(a)`. We encode this by restricting the relevant axioms to elements
of `M.algebra`. -/
structure DiagonalRep (M : VNAlgebraWithVector H) where
  /-- The representation π. -/
  π : (H →L[ℂ] H) → CrossedSpace H →L[ℂ] CrossedSpace H
  /-- π preserves zero and addition (globally). -/
  map_zero : π 0 = 0
  map_add : ∀ a b, π (a + b) = π a + π b
  /-- π preserves scalar multiplication (globally). -/
  map_smul : ∀ (c : ℂ) a, π (c • a) = c • π a
  /-- π is multiplicative on `M`. -/
  map_mul : ∀ a b, a ∈ M.algebra → b ∈ M.algebra → π (a * b) = π a * π b
  /-- π preserves the unit. -/
  map_one : π 1 = 1
  /-- π preserves *. -/
  map_star : ∀ a, a ∈ M.algebra → π (star a) = star (π a)
  /-- π is isometric on `M`. -/
  isometric : ∀ a, a ∈ M.algebra → ‖π a‖ = ‖a‖

/-!
## Section 4: The Translation Representation U

`U : ℝ → U(K)` defined by `(U(t) ξ)(s) = ξ(s - t)`.

This is the regular representation of `ℝ` on `L²(ℝ, H)`. Unitarity is from
translation-invariance of Lebesgue measure; the group law and strong
continuity are standard. -/
structure TranslationRep (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    [CompleteSpace H] where
  /-- The translation by `t`. -/
  U : ℝ → CrossedSpace H →L[ℂ] CrossedSpace H
  /-- U is a group homomorphism: `U(s+t) = U(s) · U(t)`. -/
  map_add : ∀ s t, U (s + t) = U s * U t
  /-- `U(0) = 1`. -/
  at_zero : U 0 = 1
  /-- Each `U(t)` is unitary. -/
  isUnitary : ∀ t, U t * adjoint (U t) = 1 ∧ adjoint (U t) * U t = 1
  /-- Strong continuity: `t ↦ U(t) ξ` is continuous for every `ξ`. -/
  strongly_continuous : ∀ ξ : CrossedSpace H, Continuous (fun t => U t ξ)

/-- The adjoint of `U(t)` is `U(-t)`. -/
lemma TranslationRep.adjoint_eq {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    [CompleteSpace H] (T : TranslationRep H) (t : ℝ) :
    adjoint (T.U t) = T.U (-t) := by
  -- U(-t) is a left inverse of U(t) from the group law;
  -- adjoint(U(t)) is a left inverse of U(t) from unitarity;
  -- right multiply by adjoint(U(t)) to extract U(-t) = adjoint(U(t)).
  have h_grp : T.U t * T.U (-t) = 1 := by
    rw [← T.map_add, add_neg_cancel, T.at_zero]
  have h_uni : T.U t * adjoint (T.U t) = 1 := (T.isUnitary t).1
  have h_adj_left : adjoint (T.U t) * T.U t = 1 := (T.isUnitary t).2
  calc adjoint (T.U t)
      = adjoint (T.U t) * 1 := (mul_one _).symm
    _ = adjoint (T.U t) * (T.U t * T.U (-t)) := by rw [h_grp]
    _ = (adjoint (T.U t) * T.U t) * T.U (-t) := by rw [mul_assoc]
    _ = 1 * T.U (-t) := by rw [h_adj_left]
    _ = T.U (-t) := one_mul _

/-!
## Section 5: Covariant Representations and the Crossed Product Algebra

The covariance relation `U(t) π(a) U(t)* = π(α_t(a))` is the soul of the
construction. It encodes that the crossed product is the algebra in which
`α_t` is implemented by conjugation with `U(t)`.
-/

variable {M : VNAlgebraWithVector H}

/-- A **covariant representation** of `(M, α)` on `K`: a diagonal representation
    `π` of `M` together with a translation representation `U` of `ℝ`, satisfying
    the covariance relation

        `U(t) · π(a) · U(t)* = π(α_t(a))`

    for all `a ∈ M` and `t ∈ ℝ`. The canonical example is the regular covariant
    representation on `L²(ℝ, H)`; existence of this canonical example is
    bundled as `RegularCovariantRep`. -/
structure CovariantRep (α : RDynamics M) where
  /-- The diagonal representation. -/
  diag : DiagonalRep M
  /-- The translation representation. -/
  trans : TranslationRep H
  /-- The covariance relation: `U(t) π(a) U(t)* = π(α_t(a))` for `a ∈ M`. -/
  covariance : ∀ (t : ℝ) (a : H →L[ℂ] H), a ∈ M.algebra →
    trans.U t * diag.π a * adjoint (trans.U t) = diag.π (α.α t a)

/-- **Existence of the regular covariant representation** on `L²(ℝ, H)`.

    Concretely, `π` and `U` are given by

        `(π(a) ξ)(s) = α_{-s}(a) (ξ(s))`,
        `(U(t) ξ)(s) = ξ(s - t)`.

    Showing that these define bounded operators with the required properties
    requires Bochner integration, the L² bound `‖π(a)‖ ≤ ‖a‖`, strong continuity,
    and a direct calculation of the covariance relation. We bundle the
    existence statement, to be discharged once the Bochner infrastructure is
    available. -/
structure RegularCovariantRep (α : RDynamics M) where
  rep : CovariantRep α

/-- The **algebraic crossed product** `M ⋊_α ℝ`: the *-subalgebra of `B(K)`
    generated by `π(M) ∪ U(ℝ)`.

    The von Neumann crossed product is the WOT-closure of this subalgebra;
    we defer the closure step. -/
noncomputable def crossedProduct (α : RDynamics M) (R : CovariantRep α) :
    StarSubalgebra ℂ (CrossedSpace H →L[ℂ] CrossedSpace H) :=
  StarAlgebra.adjoin ℂ
    ({R.diag.π a | a ∈ M.algebra} ∪ {R.trans.U t | t : ℝ})

/-- `π(a)` is in `M ⋊_α ℝ` for `a ∈ M`. -/
lemma diag_mem_crossedProduct (α : RDynamics M) (R : CovariantRep α)
    {a : H →L[ℂ] H} (ha : a ∈ M.algebra) :
    R.diag.π a ∈ crossedProduct α R :=
  StarAlgebra.subset_adjoin _ _ (Or.inl ⟨a, ha, rfl⟩)

/-- `U(t)` is in `M ⋊_α ℝ`. -/
lemma trans_mem_crossedProduct (α : RDynamics M) (R : CovariantRep α) (t : ℝ) :
    R.trans.U t ∈ crossedProduct α R :=
  StarAlgebra.subset_adjoin _ _ (Or.inr ⟨t, rfl⟩)

/-- The adjoint of `U(t)`, namely `U(-t)`, is also in `M ⋊_α ℝ`. -/
lemma trans_adjoint_mem_crossedProduct (α : RDynamics M) (R : CovariantRep α) (t : ℝ) :
    adjoint (R.trans.U t) ∈ crossedProduct α R := by
  rw [R.trans.adjoint_eq]
  exact trans_mem_crossedProduct α R (-t)

/-!
## Section 6: The Inner Implementation Theorem

The point of the whole construction: inside `M ⋊_α ℝ`, the automorphism
`α_t : M → M` is *inner*. Specifically, it is implemented by conjugation
with the unitary `U(t)` belonging to the crossed product.
-/

/-- **Inner Implementation Theorem.**

    For every `a ∈ M` and every `t ∈ ℝ`,

        `π(α_t(a)) = U(t) · π(a) · U(t)*`.

    In particular, the outer automorphism `α_t` of `M` becomes the inner
    automorphism `Ad(U(t))` of `M ⋊_α ℝ` when restricted to `π(M)`. This is
    the entire reason for performing the crossed product: it adjoins to `M`
    precisely the unitary needed to implement `α`. -/
theorem inner_implementation (α : RDynamics M) (R : CovariantRep α)
    (t : ℝ) {a : H →L[ℂ] H} (ha : a ∈ M.algebra) :
    R.diag.π (α.α t a) = R.trans.U t * R.diag.π a * adjoint (R.trans.U t) :=
  (R.covariance t a ha).symm

/-- A restatement of inner implementation using `U(-t)` in place of `U(t)*`. -/
theorem inner_implementation' (α : RDynamics M) (R : CovariantRep α)
    (t : ℝ) {a : H →L[ℂ] H} (ha : a ∈ M.algebra) :
    R.diag.π (α.α t a) = R.trans.U t * R.diag.π a * R.trans.U (-t) := by
  rw [inner_implementation α R t ha, R.trans.adjoint_eq]

end Spectra.CrossedProduct
