/-
Copyright (c) 2026 Spectra Formalization Project. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Adam Bornemann
Filename: Spectra.lean
-/
import Spectra.Mathlib.MeasureTheory.Integral.Basic
import Spectra.Kernel.Defs
import Spectra.Kernel.Arctan
import Spectra.Kernel.Resolvent
import Spectra.Kernel.Lorentzian
import Spectra.Kernel.Poisson.Lemmas
import Spectra.Kernel.Poisson.Basic
import Spectra.Fourier.IsUnique
import Spectra.Fourier.Inversion
import Spectra.Fourier.Identity
import Spectra.Operator.Symmetric
import Spectra.Operator.Unitary.Basic
import Spectra.Operator.Unitary.Powers
import Spectra.Herglotz.FejerMeans
import Spectra.Herglotz.FejerMeasure
import Spectra.Herglotz.Stieltjes.CumulativeDistFun
import Spectra.Herglotz.Stieltjes.Hellys
import Spectra.Herglotz.Stieltjes.IntegralConv
import Spectra.Herglotz.Basic
import Spectra.Resolvent.Integral.GroupIntegration
import Spectra.Resolvent.Integral.Limits.Helpers
import Spectra.Resolvent.Integral.Limits.Minus
import Spectra.Resolvent.Integral.Limits.Plus
import Spectra.Resolvent.Integral.Domain
import Spectra.Resolvent.Range.ClosedRange
import Spectra.Resolvent.Range.Orthogonal
import Spectra.Resolvent.Range.Surjectivity
import Spectra.Resolvent.Defs
import Spectra.Resolvent.NormExpansion
import Spectra.Resolvent.SpecialCases
import Spectra.Resolvent.LowerBound
import Spectra.Resolvent.Range
import Spectra.Resolvent.Identities
import Spectra.Resolvent.Analytic
import Spectra.Resolvent.Diagonal.Basic
import Spectra.Resolvent.Diagonal.IntegralZ.Defs
import Spectra.Resolvent.Diagonal.IntegralZ.Bulk
import Spectra.Resolvent.Diagonal.IntegralZ.Tendsto
import Spectra.Resolvent.Diagonal.IntegralZ.Shift
import Spectra.Resolvent.Diagonal.IntegralZ.GeneratorLim
import Spectra.Resolvent.Diagonal.IntegralZ.DiffQuotient
import Spectra.Resolvent.Diagonal.IntegralZ.Basic
import Spectra.CayleyTransform.Transform
import Spectra.CayleyTransform.RieszMarkov
import Spectra.CayleyTransform.Inverse
import Spectra.CayleyTransform.Mobius
import Spectra.CayleyTransform.Eigenvalue
import Spectra.CayleyTransform.BoundedBelow
import Spectra.CayleyTransform.MapsResolvent
import Spectra.CayleyTransform.Image
import Spectra.PositiveDefinite.Defs
import Spectra.PositiveDefinite.Basic
import Spectra.PositiveDefinite.PVMInterface
import Spectra.Bochner.Borel.Defs
import Spectra.Bochner.Borel.Fubini
import Spectra.Bochner.Borel.CDF
import Spectra.Bochner.Borel.Measure
import Spectra.Bochner.Borel.Identity.CauchyTransform
import Spectra.Bochner.Borel.Identity.CauchyVague
import Spectra.Bochner.Borel.Identity.BoundedCDF
import Spectra.Bochner.Borel.Basic
import Spectra.Bochner.GNS.Continuity
import Spectra.Bochner.GNS.PreHilbert
import Spectra.Bochner.GNS.PreHilbert.Defs
import Spectra.Bochner.GNS.PreHilbert.Evolution
import Spectra.Bochner.GNS.PreHilbert.Cyclic
import Spectra.Bochner.GNS.PreHilbert.Conjugate
import Spectra.Bochner.GNS.PreHilbert.Linearity
import Spectra.Bochner.GNS.PreHilbert.PosSemiDef
import Spectra.Bochner.GNS.PreHilbert.TransAction
import Spectra.Bochner.GNS.PreHilbert.NormEst
import Spectra.Bochner.GNS.Hilbert.Constructor
import Spectra.Bochner.GNS.Hilbert.NullSpace
import Spectra.Bochner.GNS.Hilbert.Bundler
import Spectra.Bochner.GNS.Representation.Lemmas
import Spectra.Bochner.GNS.Representation.StronglyCont
import Spectra.Bochner.GNS.Representation.UnitaryGroup
import Spectra.Bochner.GNS.Representation.Cyclic
import Spectra.Bochner.GNS.Representation.StronglyEx
import Spectra.Bochner.GNS.Representation.UnitaryConstructor
import Spectra.Bochner.GNS.Representation.ToStone
import Spectra.Bochner.GNS.Basic
import Spectra.Bochner.MeasureExists
import Spectra.Bochner.Basic
import Spectra.SobolevSpaces.WeakDerivative
import Spectra.SobolevSpaces.Density
import Spectra.SobolevSpaces.DuBoisReymond
import Spectra.SobolevSpaces.Operations
import Spectra.SobolevSpaces.Submodules
import Spectra.SobolevSpaces.Mollification
import Spectra.SobolevSpaces.MeyersSerrin
import Spectra.SobolevSpaces.MeyersMulti
import Spectra.SobolevSpaces.DensityResults
import Spectra.ModularTheory.KMS.PeriodicStrip.Defs
import Spectra.ModularTheory.KMS.PeriodicStrip.IndexProps
import Spectra.ModularTheory.KMS.PeriodicStrip.ExtensionProps
import Spectra.ModularTheory.KMS.PeriodicStrip.Hadamard
import Spectra.ModularTheory.KMS.PeriodicStrip.LineRemove
import Spectra.ModularTheory.KMS.PeriodicStrip.Painleve
import Spectra.ModularTheory.KMS.PeriodicStrip.Basic
import Spectra.ModularTheory.KMS.Condition
import Spectra.ModularTheory.KMS.Modular
import Spectra.QuantumMechanics.Observable.Basic
import Spectra.QuantumMechanics.Uncertainty.SchrodingerRobertson
import Spectra.QuantumMechanics.Uncertainty.Heisenberg
import Spectra.QuantumMechanics.Stone.Yosida.Defs
import Spectra.QuantumMechanics.Stone.Yosida.Helpers
import Spectra.QuantumMechanics.Stone.Yosida.Symmetry
import Spectra.QuantumMechanics.Stone.Yosida.Commutation
import Spectra.QuantumMechanics.Stone.Yosida.Bounds
import Spectra.QuantumMechanics.Stone.Yosida.Convergence.JOperator
import Spectra.QuantumMechanics.Stone.Yosida.Convergence.JNegOperator
import Spectra.QuantumMechanics.Stone.Yosida.Convergence.Approximants
import Spectra.QuantumMechanics.Stone.Yosida.ExpBounded.Helpers
import Spectra.QuantumMechanics.Stone.Yosida.ExpBounded.Unitary
import Spectra.QuantumMechanics.Stone.Yosida.ExpBounded.Adjoint
import Spectra.QuantumMechanics.Stone.Yosida.Exponential
import Spectra.QuantumMechanics.Stone.OneParameterUnitaryGroup
import Spectra.QuantumMechanics.Stone.Helpers
import Spectra.QuantumMechanics.Stone.Unique
import Spectra.QuantumMechanics.Stone.Basic
import Spectra.QuantumMechanics.Schrodinger
import Spectra.QuantumMechanics.Ehrenfest
import Spectra.QuantumMechanics.BellsTheorem.Basic
import Spectra.QuantumMechanics.BellsTheorem.CHSH_Bounds.CHSH_Basic
import Spectra.QuantumMechanics.BellsTheorem.CHSH_Bounds.Commuting
import Spectra.QuantumMechanics.BellsTheorem.CHSH_Bounds.Separable
import Spectra.QuantumMechanics.BellsTheorem.CHSH_Bounds.Tsirelson.CommutatorAlgebra
import Spectra.QuantumMechanics.BellsTheorem.CHSH_Bounds.Tsirelson.UnitaryBounds
import Spectra.QuantumMechanics.BellsTheorem.CHSH_Bounds.Tsirelson.Basic
import Spectra.QuantumMechanics.BellsTheorem.LHV
import Spectra.QuantumMechanics.BellsTheorem.QuantumCHSH.Q_CHSH_Basic
import Spectra.QuantumMechanics.BellsTheorem.QuantumCHSH.Correlations
import Spectra.QuantumMechanics.BellsTheorem.QuantumCHSH.Violation
import Spectra.QuantumMechanics.BellsTheorem.QuantumCHSH.Tsirelson
import Spectra.QuantumMechanics.Dirac.PauliMatrices
import Spectra.QuantumMechanics.Dirac.CliffordAlgebra
import Spectra.QuantumMechanics.Dirac.GammaTrace
import Spectra.QuantumMechanics.Dirac.Current
import Spectra.QuantumMechanics.Dirac.Conservation
import Spectra.QuantumMechanics.Dirac.Operator
import Spectra.InformationGeometry.Fisher.FisherInformation
import Spectra.InformationGeometry.Fisher.StatisticalModel
import Spectra.InformationGeometry.Fisher.Score
import Spectra.InformationGeometry.Fisher.FisherMetric
import Spectra.InformationGeometry.Fisher.StatisticalManifold
import Spectra.InformationGeometry.CramerRao.Basic
import Spectra.InformationGeometry.CramerRao.Cross
import Spectra.InformationGeometry.CramerRao.CauchySchwarz
import Spectra.InformationGeometry.CramerRao.Bound
import Spectra.InformationGeometry.CramerRao.SchrodingerRLD
