import Spectra.Bochner.Basic
import Spectra.Bochner.Borel.CDF
import Spectra.Bochner.Borel.Density
import Spectra.Bochner.Borel.Fubini
import Spectra.Bochner.Borel.Identity.BoundedCDF
import Spectra.Bochner.Borel.Identity.CauchyTransform
import Spectra.Bochner.Borel.Identity.CauchyVague
import Spectra.Bochner.Borel.Measure.Basic
import Spectra.Bochner.GNS.Continuity
import Spectra.Bochner.GNS.Hilbert.Bundler
import Spectra.Bochner.GNS.Hilbert.Constructor
import Spectra.Bochner.GNS.Hilbert.NullSpace
import Spectra.Bochner.GNS.PreHilbert
import Spectra.Bochner.GNS.PreHilbert.Conjugate
import Spectra.Bochner.GNS.PreHilbert.Cyclic
import Spectra.Bochner.GNS.PreHilbert.Defs
import Spectra.Bochner.GNS.PreHilbert.Evolution
import Spectra.Bochner.GNS.PreHilbert.Linearity
import Spectra.Bochner.GNS.PreHilbert.NormEst
import Spectra.Bochner.GNS.PreHilbert.PosSemiDef
import Spectra.Bochner.GNS.PreHilbert.TransAction
import Spectra.Bochner.GNS.PosDefFun
import Spectra.Bochner.GNS.Representation.Cyclic
import Spectra.Bochner.GNS.Representation.Lemmas
import Spectra.Bochner.GNS.Representation.StronglyCont
import Spectra.Bochner.GNS.Representation.StronglyEx
import Spectra.Bochner.GNS.Representation.ToStone
import Spectra.Bochner.GNS.Representation.UnitaryConstructor
import Spectra.Bochner.GNS.Representation.UnitaryGroup
import Spectra.CayleyTransform.BoundedBelow
import Spectra.CayleyTransform.Defs
import Spectra.CayleyTransform.Eigenvalue
import Spectra.CayleyTransform.Image
import Spectra.CayleyTransform.Inverse
import Spectra.CayleyTransform.Mobius
import Spectra.CayleyTransform.MapsResolvent
import Spectra.CayleyTransform.RieszMarkov
import Spectra.CayleyTransform.BorelCalculus
import Spectra.CayleyTransform.UnitaryGroup
import Spectra.CayleyTransform.Generator.Resolvent
import Spectra.CayleyTransform.Generator.Pushforward
import Spectra.CayleyTransform.Generator.Stone
import Spectra.CayleyTransform.Generator.InverseAction
import Spectra.Fourier.Identity
import Spectra.Fourier.Inversion
import Spectra.Fourier.IsUnique
import Spectra.Herglotz.Basic
import Spectra.Herglotz.CauchyInjective
import Spectra.Herglotz.FejerMeasure
import Spectra.Herglotz.FejerMeans
import Spectra.Herglotz.Stieltjes.CumulativeDistFun
import Spectra.Herglotz.Stieltjes.Hellys
import Spectra.Herglotz.Stieltjes.IntegralConv
import Spectra.InformationGeometry.GaussianModel
import Spectra.InformationGeometry.StatisticalModel
import Spectra.InformationGeometry.Score
import Spectra.InformationGeometry.Regularity
import Spectra.InformationGeometry.StatisticalManifold
import Spectra.InformationGeometry.Fisher.Information
import Spectra.InformationGeometry.Fisher.Metric
import Spectra.InformationGeometry.Divergence
import Spectra.InformationGeometry.Connection.Basic
import Spectra.InformationGeometry.Connection.AmariChentsov
import Spectra.InformationGeometry.Connection.Bartlett
import Spectra.InformationGeometry.GeometricData
import Spectra.InformationGeometry.CramerRao.Basic
import Spectra.InformationGeometry.CramerRao.Covariance
import Spectra.InformationGeometry.CramerRao.CauchySchwarz
import Spectra.InformationGeometry.CramerRao.Bound
import Spectra.InformationGeometry.CramerRao.Quantum
import Spectra.InformationGeometry.Flow.Basic
import Spectra.InformationGeometry.Flow.Family
import Spectra.InformationGeometry.Flow.Generator
import Spectra.InformationGeometry.Flow.Schrodinger
import Spectra.InformationGeometry.Flow.FaaDiBruno
import Spectra.InformationGeometry.Flow.MixtureConnection
import Spectra.InformationGeometry.Flow.CubicInvariance
import Spectra.InformationGeometry.Dichotomy
import Spectra.Kernel.Defs
import Spectra.Kernel.Arctan
import Spectra.Kernel.Resolvent
import Spectra.Kernel.Lorentzian
import Spectra.Kernel.Poisson.Lemmas
import Spectra.Kernel.Poisson.Basic
import Spectra.Mathlib.MeasureTheory.Integral.Basic
import Spectra.Mathlib.CharFunBridge
import Spectra.Modular.KMS.PeriodicStrip.Defs
import Spectra.Modular.KMS.PeriodicStrip.IndexProps
import Spectra.Modular.KMS.PeriodicStrip.ExtensionProps
import Spectra.Modular.KMS.PeriodicStrip.Hadamard
import Spectra.Modular.KMS.PeriodicStrip.LineRemove
import Spectra.Modular.KMS.PeriodicStrip.Painleve
import Spectra.Modular.KMS.PeriodicStrip.Basic
import Spectra.Modular.KMS.Condition
import Spectra.Modular.KMS.Modular
import Spectra.Modular.KMS.GroundState
import Spectra.Modular.KMS.StateTopology
import Spectra.Modular.KMS.AnalyticElements
import Spectra.Modular.KMS.Generator
import Spectra.Modular.KMS.ImaginaryTime
import Spectra.Modular.KMS.Equivalence
import Spectra.Modular.KMS.ExtremalKMS
import Spectra.Modular.KMS.UnitaryGroup
import Spectra.Modular.TomitaTakesaki.Basic
import Spectra.Modular.TomitaTakesaki.TomitaOperator
import Spectra.Modular.TomitaTakesaki.Duality
import Spectra.Modular.TomitaTakesaki.Closable
import Spectra.Modular.TomitaTakesaki.ModularOperator
import Spectra.Operator.Symmetric
import Spectra.Operator.Composite
import Spectra.Operator.Unitary.Basic
import Spectra.Operator.Unitary.Bridge
import Spectra.Operator.Unitary.Powers
import Spectra.PositiveDefinite.Unitary
import Spectra.PositiveDefinite.Basic
import Spectra.ProjValMeasure.PdInterface
import Spectra.ProjValMeasure.Basic
import Spectra.QuantumMechanics.BellsTheorem.Basic
import Spectra.QuantumMechanics.BellsTheorem.CHSH_Bounds.CHSH_Basic
import Spectra.QuantumMechanics.BellsTheorem.CHSH_Bounds.Commuting
import Spectra.QuantumMechanics.BellsTheorem.CHSH_Bounds.Op_square
import Spectra.QuantumMechanics.BellsTheorem.CHSH_Bounds.Separable
import Spectra.QuantumMechanics.BellsTheorem.CHSH_Bounds.Tsirelson.CommutatorAlgebra
import Spectra.QuantumMechanics.BellsTheorem.CHSH_Bounds.Tsirelson.UnitaryBounds
import Spectra.QuantumMechanics.BellsTheorem.CHSH_Bounds.Tsirelson.Basic
import Spectra.QuantumMechanics.BellsTheorem.LHV
import Spectra.QuantumMechanics.BellsTheorem.QuantumCHSH.Q_CHSH_Basic
import Spectra.QuantumMechanics.BellsTheorem.QuantumCHSH.Correlations
import Spectra.QuantumMechanics.BellsTheorem.QuantumCHSH.Violation
import Spectra.QuantumMechanics.BellsTheorem.QuantumCHSH.Tsirelson
import Spectra.QuantumMechanics.BornRule.Joint
-- `BornRule.JointForward` carries this layer's remaining roadmap `sorry`s (Goals 2–3); kept out of
-- the default build until proved.
--import Spectra.QuantumMechanics.BornRule.JointForward
import Spectra.QuantumMechanics.BornRule.Mixed
import Spectra.QuantumMechanics.BornRule.Moments
import Spectra.QuantumMechanics.BornRule.Naimark
import Spectra.QuantumMechanics.BornRule.Observable
import Spectra.QuantumMechanics.BornRule.POVM
import Spectra.QuantumMechanics.BornRule.PVM
import Spectra.QuantumMechanics.BornRule.Uncertainty
import Spectra.QuantumMechanics.DiracEquation.Chirality
import Spectra.QuantumMechanics.DiracEquation.CliffordAlgebra
import Spectra.QuantumMechanics.DiracEquation.CliffordOperators
import Spectra.QuantumMechanics.DiracEquation.ConcreteSpectrum
import Spectra.QuantumMechanics.DiracEquation.Conservation
import Spectra.QuantumMechanics.DiracEquation.Current
import Spectra.QuantumMechanics.DiracEquation.DiracFourier
import Spectra.QuantumMechanics.DiracEquation.Dispersion
import Spectra.QuantumMechanics.DiracEquation.FreeHamiltonian
import Spectra.QuantumMechanics.DiracEquation.GammaTrace
import Spectra.QuantumMechanics.DiracEquation.MassGap
import Spectra.QuantumMechanics.DiracEquation.NegativeEnergy
import Spectra.QuantumMechanics.DiracEquation.Operators
import Spectra.QuantumMechanics.DiracEquation.Spin
import Spectra.QuantumMechanics.DiracEquation.SpinorSpaceL2
import Spectra.QuantumMechanics.Ehrenfest
import Spectra.QuantumMechanics.FisherModel
import Spectra.QuantumMechanics.Generator.Basic
import Spectra.QuantumMechanics.Hydrogen.RadialProblem.TensorDecomp.Basic
import Spectra.QuantumMechanics.Hydrogen.RadialProblem.Equation.Basic
import Spectra.QuantumMechanics.Hydrogen.RadialProblem.Equation.Kummer
import Spectra.QuantumMechanics.Hydrogen.RadialProblem.Equation.Regularity
import Spectra.QuantumMechanics.Hydrogen.RadialProblem.Laguerre.Complete
import Spectra.QuantumMechanics.Hydrogen.RadialProblem.Laguerre.GenFun
import Spectra.QuantumMechanics.Hydrogen.RadialProblem.Laguerre.Orthogonality
import Spectra.QuantumMechanics.Hydrogen.Hamiltonian
import Spectra.QuantumMechanics.Hydrogen.Laplacian.Basic
import Spectra.QuantumMechanics.Hydrogen.Laplacian.FreeGreens.Basic
import Spectra.QuantumMechanics.Hydrogen.Laplacian.FreeGreens.Convolution
import Spectra.QuantumMechanics.Hydrogen.Laplacian.FreeGreens.Fourier
import Spectra.QuantumMechanics.Hydrogen.Laplacian.FreeGreens.L2
import Spectra.QuantumMechanics.Hydrogen.Laplacian.Spherical
import Spectra.QuantumMechanics.Hydrogen.Laplacian.SolidHarmonic
import Spectra.QuantumMechanics.Hydrogen.Laplacian.EssentialSpectrum
import Spectra.QuantumMechanics.Hydrogen.Laplacian.HalfLaplacian
import Spectra.QuantumMechanics.Hydrogen.Laplacian.SphereIntegral
import Spectra.QuantumMechanics.Hydrogen.Laplacian.ChartRealization
import Spectra.QuantumMechanics.Hydrogen.Laplacian.GreensIdentity
import Spectra.QuantumMechanics.Hydrogen.Spectrum.Continuous.Defs
import Spectra.QuantumMechanics.Hydrogen.Spectrum.Continuous.Compact
import Spectra.QuantumMechanics.Hydrogen.Spectrum.Continuous.Basic
import Spectra.QuantumMechanics.Hydrogen.BohrFormula
import Spectra.QuantumMechanics.Hydrogen.Spectrum.Complete
import Spectra.QuantumMechanics.Hydrogen.Spectrum.Degeneracy
import Spectra.QuantumMechanics.Hydrogen.Spectrum.Discrete
import Spectra.QuantumMechanics.Hydrogen.Spectrum.Eigenvalue
import Spectra.QuantumMechanics.Hydrogen.Spectrum.SectorReductionLocal
import Spectra.QuantumMechanics.Hydrogen.Spectrum.RadialEigenfunction
import Spectra.QuantumMechanics.Hydrogen.Spectrum.Forward
import Spectra.QuantumMechanics.Hydrogen.Spectrum.Isolation
import Spectra.QuantumMechanics.Hydrogen.Spectrum.Meromorphic
import Spectra.QuantumMechanics.Hydrogen.Spectrum.SectorProjection
import Spectra.QuantumMechanics.Hydrogen.Spectrum.SeparatedEigenfunction
import Spectra.QuantumMechanics.Hydrogen.Spectrum.Projections
import Spectra.QuantumMechanics.Observable.Basic
import Spectra.OneParameterUnitaryGroup.Basic
import Spectra.QuantumMechanics.PauliMatrices
import Spectra.QuantumMechanics.Perturbation.KatoRellich
import Spectra.QuantumMechanics.Perturbation.HardyInequality
import Spectra.QuantumMechanics.Perturbation.HardySharp
import Spectra.QuantumMechanics.Perturbation.CoulombBound
import Spectra.QuantumMechanics.Perturbation.TruncatedCoulombL2
import Spectra.QuantumMechanics.Perturbation.ResolventKernelL2
import Spectra.QuantumMechanics.SchrodingerEquation
import Spectra.QuantumMechanics.Uncertainty.Heisenberg
import Spectra.QuantumMechanics.Uncertainty.SchrodingerRobertson
import Spectra.QuantumMechanics.Unitarity.Basic
import Spectra.QuantumMechanics.Unitarity.FirstLawIff
import Spectra.YosidaHille.Approximation.Defs
import Spectra.YosidaHille.Approximation.Helpers
import Spectra.YosidaHille.Approximation.Symmetry
import Spectra.YosidaHille.Approximation.Commutation
import Spectra.YosidaHille.Approximation.Bounds
import Spectra.YosidaHille.Approximation.Convergence.JOperator
import Spectra.YosidaHille.Approximation.Convergence.JNegOperator
import Spectra.YosidaHille.Approximation.Convergence.Approximants
import Spectra.YosidaHille.Approximation.ExpBounded.Helpers
import Spectra.YosidaHille.Approximation.ExpBounded.Unitary
import Spectra.YosidaHille.Approximation.ExpBounded.Adjoint
import Spectra.YosidaHille.Approximation.Exponential
import Spectra.YosidaHille.Helpers
import Spectra.YosidaHille.Unique
import Spectra.YosidaHille.Basic
import Spectra.StoneBridge.Basic
import Spectra.Resolvent.Analytic
import Spectra.Resolvent.Residue
import Spectra.Resolvent.Defs
import Spectra.Resolvent.Diagonal.Basic
import Spectra.Resolvent.Diagonal.IntegralZ.Defs
import Spectra.Resolvent.Diagonal.IntegralZ.Bulk
import Spectra.Resolvent.Diagonal.IntegralZ.Tendsto
import Spectra.Resolvent.Diagonal.IntegralZ.Shift
import Spectra.Resolvent.Diagonal.IntegralZ.GeneratorLim
import Spectra.Resolvent.Diagonal.IntegralZ.DiffQuotient
import Spectra.Resolvent.Diagonal.IntegralZ.Basic
import Spectra.Resolvent.Identities
import Spectra.Resolvent.Meromorphic
import Spectra.Resolvent.Integral.GroupIntegration
import Spectra.Resolvent.Integral.Limits
import Spectra.Resolvent.Integral.Domain
import Spectra.Resolvent.LowerBound
import Spectra.Resolvent.NormExpansion
import Spectra.Resolvent.Range
import Spectra.Resolvent.Range.ClosedRange
import Spectra.Resolvent.Range.Orthogonal
import Spectra.Resolvent.Range.Surjectivity
import Spectra.Resolvent.Residue
import Spectra.Resolvent.SpecialCases
import Spectra.Resolvent.SpectralRepresentation
import Spectra.SobolevSpaces.Density
import Spectra.SobolevSpaces.DensityResults
import Spectra.SobolevSpaces.DuBoisReymond
import Spectra.SobolevSpaces.Embeddings
import Spectra.SobolevSpaces.IntegrationByParts
import Spectra.SobolevSpaces.MeyersCommon
import Spectra.SobolevSpaces.MeyersMulti
import Spectra.SobolevSpaces.MeyersSerrin
import Spectra.SobolevSpaces.Mollification
import Spectra.SobolevSpaces.Operations
import Spectra.SobolevSpaces.Submodules
import Spectra.SobolevSpaces.WeakDerivative
import Spectra.SpectralTheory.Algebra
import Spectra.SpectralTheory.ResolventForm
import Spectra.SpectralTheory.Antilinear.Conjugation
import Spectra.SpectralTheory.Antilinear.ConjugateSpace
import Spectra.SpectralTheory.Calculus.Bounded
import Spectra.SpectralTheory.Measure.Convergence
import Spectra.SpectralTheory.Measure.GeneratorLink
import Spectra.SpectralTheory.Measure.Polarized
import Spectra.SpectralTheory.SimplePole
import Spectra.SpectralTheory.StoneFormula.Basic
import Spectra.SpectralTheory.StoneFormula.Identities
import Spectra.SpectralTheory.Essential.WeakCompact
import Spectra.SpectralTheory.Essential.Defs
import Spectra.SpectralTheory.Essential.Weyl
import Spectra.SpectralTheory.Essential.Closed
import Spectra.SpectralTheory.Essential.Smul
import Spectra.SpectralTheory.Essential.Discrete
import Spectra.SpectralTheory.RectangleSimple
import Spectra.SpectralTheory.IntegralOperator
import Spectra.SpectralTheory.IntegralOperatorCompact
import Spectra.SpectralTheory.TranslationKernel
import Spectra.SpectralTheory.YoungConvolution
import Spectra.SpectralTheory.Weak
import Spectra.SpectralTheory.Eigenspace
import Spectra.SphericalHarmonics.AssociatedLegendre
import Spectra.SphericalHarmonics.Basic
import Spectra.SphericalHarmonics.Completeness
