/-
Copyright (c) 2026 Spectra Formalization Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Bornemann
-/
import Mathlib.Analysis.Calculus.ContDiff.Basic
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.MeasureTheory.Measure.Lebesgue.Basic
import Mathlib.Analysis.Calculus.BumpFunction.SmoothApprox
/-!
# Sobolev Spaces on ℝ^d: Foundations

This file lays the groundwork for `H¹(ℝ^d)` and `H²(ℝ^d)`, developed **generically over the
dimension `d`** (the physical `R3 := Rn 3` is a defeq special case, so all `R3` call-sites are
unaffected):

* the configuration space `Rn d := EuclideanSpace ℝ (Fin d)` with its Lebesgue
  measure structure;
* the Hilbert space `l2Rn d := Lp ℂ 2 (volume : Measure (Rn d))`;
* the predicate `HasWeakDerivative` capturing the distributional definition of
  the partial derivative;
* structural lemmas about smooth, compactly supported test functions — closure
  under complex conjugation, L² membership, and the well-behavedness of their
  partial derivatives — that the rest of the development reuses.

The density theory, submodule layer, integration by parts, and the operator
theory all build on this file.

## References

* [Adams, Fournier, *Sobolev Spaces*][adams2003]
* [Reed, Simon, *Methods of Modern Mathematical Physics II*][reed1975]
* [Lieb, Loss, *Analysis*][lieb2001], Chapter 7.
-/
open MeasureTheory
open scoped ContDiff
namespace Spectra.Sobolev

/-! ### Configuration space and Hilbert space -/

/-- Euclidean configuration space `ℝ^d`. The Sobolev / weak-derivative / Laplacian substrate below
    is developed **generically over the dimension `d`**; the physical `R3 := Rn 3` is a defeq
    special case, so all existing `R3` call-sites are unaffected. -/
abbrev Rn (d : ℕ) : Type := EuclideanSpace ℝ (Fin d)

/-- `Rn d`'s measurable structure is the Borel σ-algebra generated by its metric topology. Mathlib
    ships no `MeasurableSpace` on `EuclideanSpace ℝ (Fin d)` (it would clash with the inputs of
    `measureSpaceOfInnerProductSpace`), so we supply it here — a single instance, no diamond. -/
instance instMeasurableSpaceRn (d : ℕ) : MeasurableSpace (Rn d) := borel _

/-- The `BorelSpace` class asserts that the measurable space *is* `borel _`; with the instance above
    the two sides are syntactically equal, so `⟨rfl⟩` discharges it. -/
instance instBorelSpaceRn (d : ℕ) : BorelSpace (Rn d) := ⟨rfl⟩
-- `MeasureSpace (Rn d)` is provided by Mathlib's `measureSpaceOfInnerProductSpace`
-- (`volume := stdOrthonormalBasis.toBasis.addHaar`), which agrees with Mathlib's
-- L² Fourier transform. We deliberately do NOT declare our own `⟨Measure.addHaar⟩`
-- instance, to avoid a measure-instance diamond against `Lp.fourierTransformₗᵢ`.

/-- The physical configuration space ℝ³ (defeq `Rn 3`). -/
abbrev R3 : Type := Rn 3

/-- The Hilbert space L²(ℝ^d, ℂ) with Lebesgue measure. -/
abbrev l2Rn (d : ℕ) : Type := Lp ℂ 2 (volume : Measure (Rn d))

/-- The Hilbert space L²(ℝ³, ℂ) with Lebesgue measure (defeq `l2Rn 3`).

    This is the state space of non-relativistic quantum mechanics.
    It carries `NormedAddCommGroup`, `InnerProductSpace ℂ`, and
    `CompleteSpace` instances from Mathlib, making it a valid
    instantiation target for `Generator`. -/
abbrev l2R3 : Type := l2Rn 3

/-! ### Weak derivatives -/

/-- Predicate: `g` is the weak partial derivative of `f` in direction `i`.

    That is, for every smooth compactly supported test function φ:
      ∫ f(x) ∂ᵢφ(x) dx = - ∫ g(x) φ(x) dx

    We state this in terms of Lp representatives. This distributional pairing
    *is* the definition of a weak derivative — no `axiom` or `sorry` is used
    anywhere in this file. Existence of a weak derivative for a concrete `f`
    is established downstream via mollification. -/
def HasWeakDerivative {d : ℕ} (f : l2Rn d) (i : Fin d) (g : l2Rn d) : Prop :=
  ∀ (φ : Rn d → ℂ), ContDiff ℝ ∞ φ → HasCompactSupport φ →
    ∫ x, f x * fderiv ℝ φ x (EuclideanSpace.single i 1) =
    - ∫ x, g x * φ x

/-! ### Smooth, compactly supported test functions

Closure properties of `C_c^∞(ℝ³, ℂ)` under the operations that recur in
integration-by-parts arguments: complex conjugation, restriction to L², and
taking a partial derivative. -/

/-- Conjugation preserves smoothness (ℝ-smooth). -/
lemma contDiff_starRingEnd_comp {d : ℕ} {f : Rn d → ℂ} (hf : ContDiff ℝ ∞ f) :
    ContDiff ℝ ∞ (fun x => starRingEnd ℂ (f x)) :=
  ContDiff.continuousLinearMap_comp Complex.conjCLE.toContinuousLinearMap hf

/-- Conjugation preserves compact support (`star z = 0 ↔ z = 0`). -/
lemma hasCompactSupport_starRingEnd_comp {d : ℕ} {f : Rn d → ℂ} (hf : HasCompactSupport f) :
    HasCompactSupport (fun x => starRingEnd ℂ (f x)) :=
  hf.comp_left (map_zero (starRingEnd ℂ))

/-- Smooth compactly supported functions on ℝ^d belong to L². -/
lemma memLp_of_smooth_compactSupport {d : ℕ} (φ : Rn d → ℂ)
    (hφ : ContDiff ℝ ∞ φ) (hsupp : HasCompactSupport φ) :
    MemLp φ 2 (volume : Measure (Rn d)) := by
  have hcont := hφ.continuous
  haveI : IsFiniteMeasureOnCompacts (volume : Measure (Rn d)) := inferInstance
  obtain ⟨C, hC⟩ := hcont.bounded_above_of_compact_support hsupp
  exact hsupp.memLp_of_bound hcont.aestronglyMeasurable C (ae_of_all _ hC)

/-- Compact support of partial derivatives. -/
lemma hasCompactSupport_partialDeriv {d : ℕ} (φ : Rn d → ℂ) (i : Fin d)
    (hsupp : HasCompactSupport φ) :
    HasCompactSupport (fun x => fderiv ℝ φ x (EuclideanSpace.single i 1)) := by
  apply HasCompactSupport.mono (hsupp.fderiv ℝ)
  intro x hx
  exact fun h => hx (by simp [h, ContinuousLinearMap.zero_apply])

/-- Smoothness of partial derivatives. -/
lemma contDiff_partialDeriv {d : ℕ} (φ : Rn d → ℂ) (i : Fin d)
    (hφ : ContDiff ℝ ∞ φ) :
    ContDiff ℝ ∞ (fun x => fderiv ℝ φ x (EuclideanSpace.single i 1)) :=
  (contDiff_infty_iff_fderiv.mp hφ).2.clm_apply contDiff_const

/-- Partial derivatives of smooth compactly supported functions are in L². -/
lemma memLp_partialDeriv {d : ℕ} (φ : Rn d → ℂ) (i : Fin d)
    (hφ : ContDiff ℝ ∞ φ) (hsupp : HasCompactSupport φ) :
    MemLp (fun x => fderiv ℝ φ x (EuclideanSpace.single i 1)) 2 volume :=
  memLp_of_smooth_compactSupport _ (contDiff_partialDeriv φ i hφ)
    (hasCompactSupport_partialDeriv φ i hsupp)

end Spectra.Sobolev
