/-
Copyright (c) 2026 Spectra Formalization Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Bornemann
-/
import Spectra.SphericalHarmonics.Basic
import Mathlib.Analysis.Calculus.BumpFunction.SmoothApprox
import Mathlib.Analysis.Distribution.AEEqOfIntegralContDiff
import Mathlib.Analysis.Fourier.AddCircle
import Mathlib.Analysis.InnerProductSpace.Projection.Submodule
import Mathlib.MeasureTheory.Integral.IntervalIntegral.Periodic
import Mathlib.Topology.ContinuousMap.StoneWeierstrass
import Mathlib.Topology.ContinuousMap.Polynomial
import Mathlib.RingTheory.Adjoin.Polynomial.Basic
/-!
# Completeness of the spherical harmonics

`{Y_ℓ^m : 0 ≤ ℓ, |m| ≤ ℓ}` is complete in `L²(S²)`
(`sphericalHarmonic_complete`): the closure of its span is everything. No
Stone–Weierstrass on `S²` is needed.

`sphereMeasure` factors as `thetaMeasure.prod phiMeasure`
(`sphereMeasure_eq_prod`); an orthogonal-complement argument plus Fubini reduces
completeness to two one-dimensional facts:

* a `cos θ`-moment problem on `(0, π]` — Stone–Weierstrass for the algebra
  generated by `cos`, then the smooth-bump duality
  `ae_eq_zero_of_integral_contDiff_smul_eq_zero`
  (`ae_eq_zero_of_forall_integral_polyCos_eq_zero`);
* Fourier completeness on `(0, 2π]` — transported to `AddCircle (2π)` via
  `span_fourierLp_closure_eq_top`
  (`ae_eq_zero_of_forall_integral_fourier_eq_zero`).

The algebraic input is that the Rodrigues polynomials
`rodriguesDeriv (|m|+j) (|m|+j+|m|)` form a triangular (degree-`j`) family, so
`sin^{|m|}θ · q(cos θ) · e^{imφ}` lies in the span of the `Y_ℓ^m` for *every*
polynomial `q` (`toLp_sepFun_mem_span`). The completeness proof never uses
orthonormality. The triangularity lemmas themselves live in
`Spectra.SphericalHarmonics.AssociatedLegendre`.

## Main statements

* `sphereMeasure_eq_prod` — Fubini's input: `sphereMeasure` is a product.
* `sphericalHarmonic_complete` — completeness in `L²(S²)`.
-/

open MeasureTheory Complex Filter InnerProductSpace
open scoped Topology NNReal ENNReal ContDiff

namespace Spectra.SphericalHarmonics

/-! ### The factor measures

`sphereMeasure` is a product (Fubini's input): the `sin θ dθ` measure on
`(0, π]` times Lebesgue measure on `(0, 2π]`. Splitting it lets the two
1-dimensional completeness facts — Weierstrass moments in `cos θ` and Fourier
completeness in `φ` — be proved separately and glued by slicing. -/

/-- The θ-side factor of `sphereMeasure`: `sin θ dθ` on `(0, π]`. -/
noncomputable def thetaMeasure : Measure ℝ :=
  ((volume : Measure ℝ).restrict (Set.Ioc 0 Real.pi)).withDensity
    fun θ => ENNReal.ofReal (Real.sin θ)

/-- The φ-side factor of `sphereMeasure`: Lebesgue measure on `(0, 2π]`. -/
noncomputable def phiMeasure : Measure ℝ :=
  (volume : Measure ℝ).restrict (Set.Ioc 0 (2 * Real.pi))

instance : IsFiniteMeasure thetaMeasure := by
  unfold thetaMeasure
  apply isFiniteMeasure_withDensity
  have hle : (∫⁻ θ, ENNReal.ofReal (Real.sin θ)
        ∂((volume : Measure ℝ).restrict (Set.Ioc 0 Real.pi)))
      ≤ (volume : Measure ℝ) (Set.Ioc 0 Real.pi) := by
    calc (∫⁻ θ, ENNReal.ofReal (Real.sin θ)
          ∂((volume : Measure ℝ).restrict (Set.Ioc 0 Real.pi)))
        ≤ ∫⁻ _, 1 ∂((volume : Measure ℝ).restrict (Set.Ioc 0 Real.pi)) :=
          lintegral_mono fun θ => ENNReal.ofReal_le_one.mpr (Real.sin_le_one _)
      _ = (volume : Measure ℝ) (Set.Ioc 0 Real.pi) := by
          rw [lintegral_one, Measure.restrict_apply_univ]
  refine ne_top_of_le_ne_top ?_ hle
  rw [Real.volume_Ioc]
  exact ENNReal.ofReal_ne_top

instance : IsFiniteMeasure phiMeasure := by
  constructor
  unfold phiMeasure
  rw [Measure.restrict_apply_univ, Real.volume_Ioc]
  exact ENNReal.ofReal_lt_top

/-- Almost every point of `sphereMeasure` lies in the coordinate box. -/
lemma ae_mem_box :
    ∀ᵐ p ∂sphereMeasure,
      p ∈ Set.Ioc (0 : ℝ) Real.pi ×ˢ Set.Ioc (0 : ℝ) (2 * Real.pi) := by
  unfold sphereMeasure
  exact (ae_restrict_mem (measurableSet_Ioc.prod measurableSet_Ioc)).filter_mono
    (Measure.AbsolutelyContinuous.ae_le (withDensity_absolutelyContinuous _ _))

/-- Almost every θ (w.r.t. `thetaMeasure`) lies in `(0, π]`. -/
lemma ae_theta_mem_Ioc : ∀ᵐ θ ∂thetaMeasure, θ ∈ Set.Ioc (0 : ℝ) Real.pi := by
  unfold thetaMeasure
  exact (ae_restrict_mem measurableSet_Ioc).filter_mono
    (Measure.AbsolutelyContinuous.ae_le (withDensity_absolutelyContinuous _ _))

/-- Almost every θ lies in the *open* interval `(0, π)`: the endpoint `{π}` is
    a Lebesgue-null singleton and `thetaMeasure ≪ volume`. Inside `(0, π)` we
    have `sin θ ≠ 0`, which lets the `sin^{|m|}θ` factor be divided out. -/
lemma ae_theta_mem_Ioo : ∀ᵐ θ ∂thetaMeasure, θ ∈ Set.Ioo (0 : ℝ) Real.pi := by
  have hac : thetaMeasure ≪ (volume : Measure ℝ) := by
    unfold thetaMeasure
    exact (withDensity_absolutelyContinuous _ _).trans
      (Measure.absolutelyContinuous_of_le Measure.restrict_le_self)
  have hpi_vol : ∀ᵐ θ ∂(volume : Measure ℝ), θ ≠ Real.pi := by
    rw [ae_iff]
    have hset : {θ : ℝ | ¬θ ≠ Real.pi} = {Real.pi} := by
      ext θ
      simp only [ne_eq, Decidable.not_not, Set.setOf_eq_eq_singleton,
        Set.mem_singleton_iff]
    rw [hset]
    exact Real.volume_singleton
  filter_upwards [ae_theta_mem_Ioc,
    hpi_vol.filter_mono (Measure.AbsolutelyContinuous.ae_le hac)] with θ hθ hne
  exact ⟨hθ.1, lt_of_le_of_ne hθ.2 hne⟩

/-- `‖e^{ikφ}‖ = 1` for `k : ℤ`, `φ : ℝ`. -/
lemma norm_exp_I_int_mul (k : ℤ) (φ : ℝ) : ‖Complex.exp (I * k * φ)‖ = 1 := by
  rw [show I * (k : ℂ) * (φ : ℂ) = (((k : ℝ) * φ : ℝ) : ℂ) * I by push_cast; ring]
  exact Complex.norm_exp_ofReal_mul_I _

/-- The reflection factor never vanishes (it is `1` or `±(ℓ-|m|)!/(ℓ+|m|)!`). -/
lemma reflectionFactor_ne_zero (ℓ : ℕ) (m : ℤ) : reflectionFactor ℓ m ≠ 0 := by
  unfold reflectionFactor
  split_ifs
  · exact one_ne_zero
  · exact div_ne_zero
      (mul_ne_zero (pow_ne_zero _ (by norm_num))
        (Nat.cast_ne_zero.mpr (Nat.factorial_ne_zero _)))
      (Nat.cast_ne_zero.mpr (Nat.factorial_ne_zero _))

/-- **Fubini's input**: `sphereMeasure` is the product of the factor measures.
    Both sides agree on measurable rectangles (Tonelli for the density), and
    both factors are finite, so `Measure.prod_eq` applies. -/
lemma sphereMeasure_eq_prod : sphereMeasure = thetaMeasure.prod phiMeasure := by
  refine (Measure.prod_eq fun s t hs ht => ?_).symm
  have hst : MeasurableSet (s ×ˢ t) := hs.prod ht
  calc sphereMeasure (s ×ˢ t)
      = ∫⁻ p in (s ×ˢ t) ∩ Set.Ioc 0 Real.pi ×ˢ Set.Ioc 0 (2 * Real.pi),
          ENNReal.ofReal (Real.sin p.1) ∂(volume : Measure (ℝ × ℝ)) := by
        unfold sphereMeasure
        rw [withDensity_apply _ hst, Measure.restrict_restrict hst]
    _ = ∫⁻ p in (s ∩ Set.Ioc 0 Real.pi) ×ˢ (t ∩ Set.Ioc 0 (2 * Real.pi)),
          ENNReal.ofReal (Real.sin p.1) ∂(volume : Measure (ℝ × ℝ)) := by
        rw [Set.prod_inter_prod]
    _ = ∫⁻ p, ENNReal.ofReal (Real.sin p.1)
          ∂(((volume : Measure ℝ).restrict (s ∩ Set.Ioc 0 Real.pi)).prod
            ((volume : Measure ℝ).restrict (t ∩ Set.Ioc 0 (2 * Real.pi)))) := by
        rw [Measure.volume_eq_prod ℝ ℝ, ← Measure.prod_restrict]
    _ = (∫⁻ θ in s ∩ Set.Ioc 0 Real.pi, ENNReal.ofReal (Real.sin θ)) *
          ∫⁻ _ in t ∩ Set.Ioc 0 (2 * Real.pi), (1 : ℝ≥0∞) := by
        have hfg : (fun p : ℝ × ℝ => ENNReal.ofReal (Real.sin p.1)) =
            fun p : ℝ × ℝ =>
              (fun θ => ENNReal.ofReal (Real.sin θ)) p.1 *
                (fun _ : ℝ => (1 : ℝ≥0∞)) p.2 := by
          funext p
          simp
        rw [hfg]
        exact lintegral_prod_mul
          ((ENNReal.measurable_ofReal.comp Real.measurable_sin).aemeasurable)
          aemeasurable_const
    _ = thetaMeasure s * phiMeasure t := by
        rw [lintegral_one, Measure.restrict_apply_univ]
        congr 1
        · unfold thetaMeasure
          rw [withDensity_apply _ hs, Measure.restrict_restrict hs]
        · unfold phiMeasure
          rw [Measure.restrict_apply ht]

/-! ### The separated test functions -/

/-- `sin^{|m|}θ · q(cos θ) · e^{imφ}`: the separated functions whose `toLp`
    images populate the span of the spherical harmonics. -/
noncomputable def sepFun (m : ℤ) (q : Polynomial ℝ) : ℝ × ℝ → ℂ := fun p =>
  ((Real.sin p.1 ^ m.natAbs * q.eval (Real.cos p.1) : ℝ) : ℂ) *
    Complex.exp (I * m * p.2)

lemma sepFun_continuous (m : ℤ) (q : Polynomial ℝ) : Continuous (sepFun m q) := by
  unfold sepFun
  exact (Complex.continuous_ofReal.comp (by fun_prop)).mul
    (Complex.continuous_exp.comp (continuous_const.mul
      (Complex.continuous_ofReal.comp continuous_snd)))

/-- Continuity ⇒ membership in L²(S²): the `memLp_sphericalHarmonic` argument,
    abstracted over the function. -/
lemma memLp_of_continuous {F : ℝ × ℝ → ℂ} (hF : Continuous F) :
    MemLp F 2 sphereMeasure := by
  obtain ⟨C, hC⟩ := (isCompact_Icc.prod isCompact_Icc).exists_bound_of_continuousOn
    (hF.continuousOn (s := Set.Icc 0 Real.pi ×ˢ Set.Icc 0 (2 * Real.pi)))
  refine MemLp.of_bound hF.aestronglyMeasurable C ?_
  filter_upwards [ae_mem_box] with p hp
  exact hC p ⟨⟨hp.1.1.le, hp.1.2⟩, ⟨hp.2.1.le, hp.2.2⟩⟩

lemma memLp_sepFun (m : ℤ) (q : Polynomial ℝ) :
    MemLp (sepFun m q) 2 sphereMeasure :=
  memLp_of_continuous (sepFun_continuous m q)

/-- A uniform pointwise bound for `sepFun`: `|sin θ| ≤ 1`, `cos θ ∈ [-1, 1]`,
    `‖e^{imφ}‖ = 1`. -/
lemma sepFun_bound (m : ℤ) (q : Polynomial ℝ) :
    ∃ C : ℝ, ∀ p : ℝ × ℝ, ‖sepFun m q p‖ ≤ C := by
  have hqc : Continuous fun x : ℝ => q.eval x := by fun_prop
  obtain ⟨C, hC⟩ := isCompact_Icc.exists_bound_of_continuousOn
    (hqc.continuousOn (s := Set.Icc (-1 : ℝ) 1))
  refine ⟨max C 0, fun p => ?_⟩
  have hexp : ‖Complex.exp (I * m * p.2)‖ = 1 := norm_exp_I_int_mul m p.2
  have h1 : |Real.sin p.1 ^ m.natAbs| ≤ 1 := by
    rw [abs_pow]
    exact pow_le_one₀ (abs_nonneg _)
      (abs_le.mpr ⟨Real.neg_one_le_sin _, Real.sin_le_one _⟩)
  have h2 : |q.eval (Real.cos p.1)| ≤ C := by
    have h := hC (Real.cos p.1) ⟨Real.neg_one_le_cos _, Real.cos_le_one _⟩
    rwa [Real.norm_eq_abs] at h
  calc ‖sepFun m q p‖
      = |Real.sin p.1 ^ m.natAbs * q.eval (Real.cos p.1)| := by
        change ‖((Real.sin p.1 ^ m.natAbs * q.eval (Real.cos p.1) : ℝ) : ℂ) *
            Complex.exp (I * m * p.2)‖ = _
        rw [norm_mul, hexp, mul_one, Complex.norm_real, Real.norm_eq_abs]
    _ = |Real.sin p.1 ^ m.natAbs| * |q.eval (Real.cos p.1)| := abs_mul _ _
    _ ≤ 1 * C := mul_le_mul h1 h2 (abs_nonneg _) zero_le_one
    _ = C := one_mul C
    _ ≤ max C 0 := le_max_left C 0

/-- On the physical range `θ ∈ [0, π]` (where `√(1 - cos²θ) = sin θ`), the
    spherical harmonic is a constant times `sepFun m (rodriguesDeriv ℓ (ℓ+|m|))`. -/
lemma sphericalHarmonic_eq_sepFun (ℓ : ℕ) (m : ℤ) (hm : |m| ≤ (ℓ : ℤ))
    {a : ℝ} (ha : a ∈ Set.Icc (0 : ℝ) Real.pi) (b : ℝ) :
    SphericalHarmonic ℓ m hm (a, b) =
      ((sphericalNorm ℓ m * reflectionFactor ℓ m *
          ((-1 : ℝ) ^ m.natAbs / (2 ^ ℓ * ℓ.factorial : ℝ)) : ℝ) : ℂ) *
        sepFun m (rodriguesDeriv ℓ (ℓ + m.natAbs)) (a, b) := by
  have hsin : Real.sqrt (1 - Real.cos a ^ 2) = Real.sin a := by
    rw [← Real.sin_sq a]
    exact Real.sqrt_sq (Real.sin_nonneg_of_nonneg_of_le_pi ha.1 ha.2)
  rw [sphericalHarmonic_eq]
  rw [show sepFun m (rodriguesDeriv ℓ (ℓ + m.natAbs)) (a, b) =
      ((Real.sin a ^ m.natAbs *
          (rodriguesDeriv ℓ (ℓ + m.natAbs)).eval (Real.cos a) : ℝ) : ℂ) *
        Complex.exp (I * m * b) from rfl]
  rw [show assocLegendreNat ℓ m.natAbs (Real.cos a) =
      (-1 : ℝ) ^ m.natAbs / (2 ^ ℓ * ℓ.factorial : ℝ) *
        Real.sqrt (1 - Real.cos a ^ 2) ^ m.natAbs *
        (rodriguesDeriv ℓ (ℓ + m.natAbs)).eval (Real.cos a) from rfl]
  rw [hsin]
  push_cast
  ring

/-- The generating set of the completeness theorem, named once so that the
    span arguments below stay readable. (Must match the theorem statement
    verbatim.) -/
def harmonicSet : Set L2_S2 :=
  {g : L2_S2 | ∃ (ℓ : ℕ) (m : ℤ) (hm : |m| ≤ (ℓ : ℤ)),
    g = (memLp_sphericalHarmonic ℓ m hm).toLp (SphericalHarmonic ℓ m hm)}

/-- Each `sepFun m (rodriguesDeriv (|m|+j) (|m|+j+|m|))` lands (after `toLp`)
    in the span of the spherical harmonics: it is `Y_{|m|+j}^m` divided by a
    nonzero constant. -/
lemma toLp_sepFun_rodrigues_mem_span (m : ℤ) (j : ℕ) :
    (memLp_sepFun m (rodriguesDeriv (m.natAbs + j) (m.natAbs + j + m.natAbs))).toLp
        (sepFun m (rodriguesDeriv (m.natAbs + j) (m.natAbs + j + m.natAbs))) ∈
      Submodule.span ℂ harmonicSet := by
  set ℓ : ℕ := m.natAbs + j with _hℓ
  have hm' : |m| ≤ (ℓ : ℤ) := by
    rw [Int.abs_eq_natAbs]
    exact_mod_cast Nat.le_add_right m.natAbs j
  set c : ℝ := sphericalNorm ℓ m * reflectionFactor ℓ m *
    ((-1 : ℝ) ^ m.natAbs / (2 ^ ℓ * ℓ.factorial : ℝ)) with _hc
  have hc0 : c ≠ 0 := by
    refine mul_ne_zero (mul_ne_zero (sphericalNorm_pos ℓ m).ne'
      (reflectionFactor_ne_zero ℓ m)) ?_
    exact div_ne_zero (pow_ne_zero _ (by norm_num))
      (mul_ne_zero (pow_ne_zero _ two_ne_zero)
        (Nat.cast_ne_zero.mpr (Nat.factorial_ne_zero ℓ)))
  have hae : SphericalHarmonic ℓ m hm' =ᵐ[sphereMeasure]
      (c : ℂ) • sepFun m (rodriguesDeriv ℓ (ℓ + m.natAbs)) := by
    filter_upwards [ae_mem_box] with p hp
    obtain ⟨a, b⟩ := p
    rw [Pi.smul_apply, smul_eq_mul]
    exact sphericalHarmonic_eq_sepFun ℓ m hm' ⟨hp.1.1.le, hp.1.2⟩ b
  have h1 : (memLp_sphericalHarmonic ℓ m hm').toLp (SphericalHarmonic ℓ m hm') =
      (c : ℂ) • (memLp_sepFun m (rodriguesDeriv ℓ (ℓ + m.natAbs))).toLp
        (sepFun m (rodriguesDeriv ℓ (ℓ + m.natAbs))) := by
    rw [← MemLp.toLp_const_smul ((c : ℂ))
      (memLp_sepFun m (rodriguesDeriv ℓ (ℓ + m.natAbs)))]
    exact MemLp.toLp_congr _ _ hae
  have hYmem : (memLp_sphericalHarmonic ℓ m hm').toLp (SphericalHarmonic ℓ m hm') ∈
      Submodule.span ℂ harmonicSet :=
    Submodule.subset_span ⟨ℓ, m, hm', rfl⟩
  have h2 := Submodule.smul_mem (Submodule.span ℂ harmonicSet) ((c : ℂ))⁻¹ hYmem
  rw [h1, smul_smul, inv_mul_cancel₀ (Complex.ofReal_ne_zero.mpr hc0),
    one_smul] at h2
  exact h2

/-- Every separated function `sepFun m q` lands (after `toLp`) in the span of
    the spherical harmonics: triangularity of the Rodrigues family in the
    polynomial variable plus `toLp`-linearity. -/
lemma toLp_sepFun_mem_span (m : ℤ) (q : Polynomial ℝ) :
    (memLp_sepFun m q).toLp (sepFun m q) ∈ Submodule.span ℂ harmonicSet := by
  have hq : q ∈ Submodule.span ℝ (Set.range fun j : ℕ =>
      rodriguesDeriv (m.natAbs + j) (m.natAbs + j + m.natAbs)) := by
    refine span_of_natDegree _ (fun j => ?_) (fun j => ?_) q
    · have h := rodriguesDeriv_natDegree_le (m.natAbs + j) m.natAbs
      rwa [Nat.add_sub_cancel_left] at h
    · have h := rodriguesDeriv_coeff_ne_zero (m.natAbs + j) m.natAbs
        (Nat.le_add_right _ _)
      rwa [Nat.add_sub_cancel_left] at h
  induction hq using Submodule.span_induction with
  | mem x hx =>
      obtain ⟨j, rfl⟩ := hx
      exact toLp_sepFun_rodrigues_mem_span m j
  | zero =>
      have h0 : (memLp_sepFun m 0).toLp (sepFun m 0) = 0 := by
        rw [Lp.eq_zero_iff_ae_eq_zero]
        filter_upwards [(memLp_sepFun m 0).coeFn_toLp] with p hp
        rw [hp]
        simp [sepFun]
      rw [h0]
      exact Submodule.zero_mem _
  | add x y _hx _hy ihx ihy =>
      have hpt : sepFun m (x + y) = sepFun m x + sepFun m y := by
        funext p
        simp only [sepFun, Pi.add_apply, Polynomial.eval_add]
        push_cast
        ring
      have heq : (memLp_sepFun m (x + y)).toLp (sepFun m (x + y)) =
          (memLp_sepFun m x).toLp (sepFun m x) +
            (memLp_sepFun m y).toLp (sepFun m y) := by
        rw [← MemLp.toLp_add (memLp_sepFun m x) (memLp_sepFun m y)]
        exact MemLp.toLp_congr _ _
          (Filter.Eventually.of_forall fun p => congrFun hpt p)
      rw [heq]
      exact Submodule.add_mem _ ihx ihy
  | smul a x _hx ih =>
      have hpt : sepFun m (a • x) = (a : ℂ) • sepFun m x := by
        funext p
        simp only [sepFun, Pi.smul_apply, Polynomial.eval_smul, smul_eq_mul]
        push_cast
        ring
      have heq : (memLp_sepFun m (a • x)).toLp (sepFun m (a • x)) =
          (a : ℂ) • (memLp_sepFun m x).toLp (sepFun m x) := by
        rw [← MemLp.toLp_const_smul ((a : ℂ)) (memLp_sepFun m x)]
        exact MemLp.toLp_congr _ _
          (Filter.Eventually.of_forall fun p => congrFun hpt p)
      rw [heq]
      exact Submodule.smul_mem _ _ ih

/-! ### The θ-side: a moment problem on `(0, π]` -/

/-- **Moment vanishing ⇒ a.e. zero** on the θ-side: if `u` is integrable
    against `thetaMeasure` and all its moments against polynomials in `cos θ`
    vanish, then `u = 0` a.e.

    Proof: Stone–Weierstrass for `Algebra.adjoin ℝ {cos}` on the compact
    `[0, π]` (where `cos` is injective, so the algebra separates points)
    upgrades the polynomial moments to all continuous test functions via an
    `ε`-argument against `∫‖u‖`; then the smooth-bump duality
    `ae_eq_zero_of_integral_contDiff_smul_eq_zero` finishes. -/
lemma ae_eq_zero_of_forall_integral_polyCos_eq_zero {u : ℝ → ℂ}
    (hu : Integrable u thetaMeasure)
    (h : ∀ q : Polynomial ℝ,
      ∫ θ, ((q.eval (Real.cos θ) : ℝ) : ℂ) * u θ ∂thetaMeasure = 0) :
    ∀ᵐ θ ∂thetaMeasure, u θ = 0 := by
  -- products with continuous functions are integrable (sup bound on `(0, π]`)
  have hbd : ∀ H : ℝ → ℝ, Continuous H →
      Integrable (fun θ => ((H θ : ℝ) : ℂ) * u θ) thetaMeasure := by
    intro H hH
    obtain ⟨C, hC⟩ := isCompact_Icc.exists_bound_of_continuousOn
      (hH.continuousOn (s := Set.Icc (0 : ℝ) Real.pi))
    refine hu.bdd_mul (c := C)
      ((Complex.continuous_ofReal.comp hH).aestronglyMeasurable) ?_
    filter_upwards [ae_theta_mem_Ioc] with θ hθ
    rw [Complex.norm_real]
    exact hC θ ⟨hθ.1.le, hθ.2⟩
  -- Step 1: the moments vanish against every continuous test function.
  have key : ∀ G : ℝ → ℝ, Continuous G →
      ∫ θ, ((G θ : ℝ) : ℂ) * u θ ∂thetaMeasure = 0 := by
    intro G hG
    by_contra hne
    have hpos : 0 < ‖∫ θ, ((G θ : ℝ) : ℂ) * u θ ∂thetaMeasure‖ :=
      norm_pos_iff.mpr hne
    set B : ℝ := ∫ θ, ‖u θ‖ ∂thetaMeasure with hB
    have hB0 : 0 ≤ B := integral_nonneg fun θ => norm_nonneg _
    have hB1 : (0 : ℝ) < B + 1 := by linarith
    set ε : ℝ := ‖∫ θ, ((G θ : ℝ) : ℂ) * u θ ∂thetaMeasure‖ / (B + 1) with hε
    have hε0 : 0 < ε := div_pos hpos hB1
    -- Stone–Weierstrass: polynomials in `cos` are sup-dense in `C([0, π], ℝ)`
    haveI : CompactSpace (Set.Icc (0 : ℝ) Real.pi) :=
      isCompact_iff_compactSpace.mp isCompact_Icc
    set cosMap : C(Set.Icc (0 : ℝ) Real.pi, ℝ) :=
      ⟨fun x => Real.cos x.1, Real.continuous_cos.comp continuous_subtype_val⟩
      with _hcosMap
    have hsep : (Algebra.adjoin ℝ {cosMap}).SeparatesPoints := by
      intro x y hxy
      refine ⟨⇑cosMap, ⟨cosMap, Algebra.subset_adjoin (Set.mem_singleton _), rfl⟩, ?_⟩
      intro hcos
      exact hxy (Subtype.ext (Real.injOn_cos x.2 y.2 hcos))
    set fG : C(Set.Icc (0 : ℝ) Real.pi, ℝ) :=
      ⟨fun x => G x.1, hG.comp continuous_subtype_val⟩ with _hfG
    obtain ⟨gA, hgA⟩ :=
      ContinuousMap.exists_mem_subalgebra_near_continuousMap_of_separatesPoints
        (Algebra.adjoin ℝ {cosMap}) hsep fG ε hε0
    obtain ⟨q, hq⟩ : ∃ q : Polynomial ℝ,
        Polynomial.aeval cosMap q = (gA : C(Set.Icc (0 : ℝ) Real.pi, ℝ)) := by
      have hmem := gA.2
      simp only [Algebra.adjoin_singleton_eq_range_aeval ℝ cosMap] at hmem
      exact (AlgHom.mem_range _).mp hmem
    -- the polynomial `q` is uniformly `ε`-close to `G` on `[0, π]`
    have hpt : ∀ θ ∈ Set.Icc (0 : ℝ) Real.pi,
        |G θ - q.eval (Real.cos θ)| ≤ ε := by
      intro θ hθ
      have h1 := ContinuousMap.norm_coe_le_norm
        ((gA : C(Set.Icc (0 : ℝ) Real.pi, ℝ)) - fG) ⟨θ, hθ⟩
      rw [ContinuousMap.sub_apply] at h1
      have h2 : (gA : C(Set.Icc (0 : ℝ) Real.pi, ℝ)) ⟨θ, hθ⟩ =
          q.eval (Real.cos θ) := by
        rw [← hq]
        exact Polynomial.aeval_continuousMap_apply q cosMap ⟨θ, hθ⟩
      have h3 : fG ⟨θ, hθ⟩ = G θ := rfl
      rw [h2, h3, Real.norm_eq_abs] at h1
      rw [abs_sub_comm]
      exact le_trans h1 hgA.le
    -- the `G`-moment equals the `(G - q∘cos)`-moment, which is `ε·B`-small
    have hsplit : (∫ θ, ((G θ - q.eval (Real.cos θ) : ℝ) : ℂ) * u θ ∂thetaMeasure) =
        ∫ θ, ((G θ : ℝ) : ℂ) * u θ ∂thetaMeasure := by
      rw [← sub_zero (∫ θ, ((G θ : ℝ) : ℂ) * u θ ∂thetaMeasure), ← h q,
        ← integral_sub (hbd G hG)
          (hbd (fun θ => q.eval (Real.cos θ)) (by fun_prop))]
      refine integral_congr_ae (Filter.Eventually.of_forall fun θ => ?_)
      push_cast
      ring
    have hbound : ∀ᵐ θ ∂thetaMeasure,
        ‖((G θ - q.eval (Real.cos θ) : ℝ) : ℂ) * u θ‖ ≤ ε * ‖u θ‖ := by
      filter_upwards [ae_theta_mem_Ioc] with θ hθ
      rw [norm_mul, Complex.norm_real, Real.norm_eq_abs]
      exact mul_le_mul_of_nonneg_right (hpt θ ⟨hθ.1.le, hθ.2⟩) (norm_nonneg _)
    have hle : ‖∫ θ, ((G θ : ℝ) : ℂ) * u θ ∂thetaMeasure‖ ≤ ε * B := by
      rw [← hsplit]
      calc ‖∫ θ, ((G θ - q.eval (Real.cos θ) : ℝ) : ℂ) * u θ ∂thetaMeasure‖
          ≤ ∫ θ, ε * ‖u θ‖ ∂thetaMeasure :=
            norm_integral_le_of_norm_le (hu.norm.const_mul ε) hbound
        _ = ε * B := by rw [integral_const_mul, ← hB]
    have hεB : ε * (B + 1) = ‖∫ θ, ((G θ : ℝ) : ℂ) * u θ ∂thetaMeasure‖ := by
      rw [hε, div_mul_cancel₀ _ hB1.ne']
    have hlt : ε * B < ‖∫ θ, ((G θ : ℝ) : ℂ) * u θ ∂thetaMeasure‖ := by
      calc ε * B < ε * (B + 1) := mul_lt_mul_of_pos_left (lt_add_one B) hε0
        _ = _ := hεB
    exact absurd hle (not_le.mpr hlt)
  -- Step 2: smooth-bump duality.
  refine ae_eq_zero_of_integral_contDiff_smul_eq_zero hu.locallyIntegrable
    fun g hg _hsupp => ?_
  calc ∫ θ, g θ • u θ ∂thetaMeasure
      = ∫ θ, ((g θ : ℝ) : ℂ) * u θ ∂thetaMeasure :=
        integral_congr_ae (Filter.Eventually.of_forall fun θ => by
          simp only [Complex.real_smul])
    _ = 0 := key g hg.continuous

/-! ### The φ-side: Fourier completeness on `(0, 2π]` -/

/-- **Fourier completeness on the φ-side**: if `v ∈ L²(phiMeasure)` and all
    Fourier coefficients `∫ e^{ikφ} v(φ) dφ` vanish, then `v = 0` a.e.

    Proof: transport along the measure-preserving quotient map
    `ℝ → AddCircle (2π)` via `AddCircle.liftIoc` (applied to a strongly
    measurable representative), and use the completeness of the Fourier
    system, `span_fourierLp_closure_eq_top`. -/
lemma ae_eq_zero_of_forall_integral_fourier_eq_zero {v : ℝ → ℂ}
    (hv : MemLp v 2 phiMeasure)
    (h : ∀ k : ℤ, ∫ φ, Complex.exp (I * k * φ) * v φ ∂phiMeasure = 0) :
    ∀ᵐ φ ∂phiMeasure, v φ = 0 := by
  haveI : Fact (0 < 2 * Real.pi) := ⟨Real.two_pi_pos⟩
  -- bookkeeping: `phiMeasure` is `volume.restrict (Ioc 0 (0 + 2π))`
  have hIoc : Set.Ioc (0 : ℝ) (0 + 2 * Real.pi) = Set.Ioc 0 (2 * Real.pi) := by
    rw [zero_add]
  have hμ : phiMeasure =
      (volume : Measure ℝ).restrict (Set.Ioc 0 (0 + 2 * Real.pi)) := by
    unfold phiMeasure
    rw [hIoc]
  have hmem : ∀ᵐ φ ∂phiMeasure, φ ∈ Set.Ioc (0 : ℝ) (0 + 2 * Real.pi) := by
    rw [hμ]
    exact ae_restrict_mem measurableSet_Ioc
  -- a strongly measurable representative of `v`
  set g : ℝ → ℂ := hv.aestronglyMeasurable.mk v with _hg_def
  have hg_sm : StronglyMeasurable g := hv.aestronglyMeasurable.stronglyMeasurable_mk
  have hvg : v =ᵐ[phiMeasure] g := hv.aestronglyMeasurable.ae_eq_mk
  -- lift to the circle
  set V : AddCircle (2 * Real.pi) → ℂ := AddCircle.liftIoc (2 * Real.pi) 0 g
    with _hV_def
  have hV_sm : StronglyMeasurable V := by
    have h1 : Measurable fun x : Set.Ioc (0 : ℝ) (0 + 2 * Real.pi) => g x.1 :=
      hg_sm.measurable.comp measurable_subtype_coe
    exact (h1.comp
      (AddCircle.measurableEquivIoc (T := 2 * Real.pi) 0).measurable).stronglyMeasurable
  have hVcoe : ∀ x ∈ Set.Ioc (0 : ℝ) (0 + 2 * Real.pi),
      V ((x : ℝ) : AddCircle (2 * Real.pi)) = g x := fun x hx =>
    AddCircle.liftIoc_coe_apply hx
  have hmp := AddCircle.measurePreserving_mk (T := 2 * Real.pi) 0
  have hcomp : (fun x : ℝ => V ((x : ℝ) : AddCircle (2 * Real.pi)))
      =ᵐ[phiMeasure] v := by
    filter_upwards [hmem, hvg] with x hx hvx
    rw [hVcoe x hx]
    exact hvx.symm
  -- `V ∈ L²` for the circle volume, hence for the (rescaled) Haar measure
  have hVmem_vol : MemLp V 2 (volume : Measure (AddCircle (2 * Real.pi))) := by
    rw [← hmp.map_eq]
    refine (memLp_map_measure_iff hV_sm.aestronglyMeasurable
      hmp.measurable.aemeasurable).mpr ?_
    rw [← hμ]
    exact MemLp.ae_eq hcomp.symm hv
  have h2π_ne : ENNReal.ofReal (2 * Real.pi) ≠ 0 :=
    (ENNReal.ofReal_pos.mpr Real.two_pi_pos).ne'
  have hhaar_eq : (AddCircle.haarAddCircle : Measure (AddCircle (2 * Real.pi))) =
      (ENNReal.ofReal (2 * Real.pi))⁻¹ •
        (volume : Measure (AddCircle (2 * Real.pi))) := by
    rw [AddCircle.volume_eq_smul_haarAddCircle, ← smul_assoc, smul_eq_mul,
      ENNReal.inv_mul_cancel h2π_ne ENNReal.ofReal_ne_top, one_smul]
  have hVmem : MemLp V 2
      (AddCircle.haarAddCircle : Measure (AddCircle (2 * Real.pi))) := by
    rw [hhaar_eq]
    exact hVmem_vol.smul_measure (ENNReal.inv_ne_top.mpr h2π_ne)
  set VLp : Lp ℂ 2 (AddCircle.haarAddCircle : Measure (AddCircle (2 * Real.pi))) :=
    hVmem.toLp V with _hVLp_def
  -- all Fourier coefficients of `V` vanish (transport of `h`)
  have hgen : ∀ n : ℤ, inner ℂ (fourierLp (T := 2 * Real.pi) 2 n) VLp = 0 := by
    intro n
    have hasm : AEStronglyMeasurable
        (fun x : AddCircle (2 * Real.pi) => (starRingEnd ℂ) (fourier n x) * V x)
        (Measure.map ((↑) : ℝ → AddCircle (2 * Real.pi))
          ((volume : Measure ℝ).restrict (Set.Ioc 0 (0 + 2 * Real.pi)))) := by
      rw [hmp.map_eq]
      exact ((Complex.continuous_conj.comp
        (fourier n).continuous).aestronglyMeasurable).mul hV_sm.aestronglyMeasurable
    have hvol : (∫ x, (starRingEnd ℂ) (fourier n x) * V x
          ∂(volume : Measure (AddCircle (2 * Real.pi)))) = 0 := by
      rw [← hmp.map_eq, integral_map hmp.measurable.aemeasurable hasm, ← hμ,
        ← h (-n)]
      refine integral_congr_ae ?_
      filter_upwards [hmem, hvg] with φ hφ hvφ
      rw [hVcoe φ hφ, ← hvφ]
      congr 1
      -- `conj (fourier n φ) = exp (I·(-n)·φ)`
      have hπ : ((Real.pi : ℝ) : ℂ) ≠ 0 := Complex.ofReal_ne_zero.mpr Real.pi_ne_zero
      rw [fourier_coe_apply, ← Complex.exp_conj]
      congr 1
      rw [map_div₀]
      simp only [map_mul, Complex.conj_I, Complex.conj_ofReal, map_ofNat,
        map_intCast]
      push_cast
      rw [div_eq_iff (mul_ne_zero two_ne_zero hπ)]
      ring
    have hint0 : (∫ x, (starRingEnd ℂ) (fourier n x) * V x
        ∂(AddCircle.haarAddCircle : Measure (AddCircle (2 * Real.pi)))) = 0 := by
      have hsc : (∫ x, (starRingEnd ℂ) (fourier n x) * V x
            ∂(volume : Measure (AddCircle (2 * Real.pi)))) =
          (ENNReal.ofReal (2 * Real.pi)).toReal •
            ∫ x, (starRingEnd ℂ) (fourier n x) * V x
              ∂(AddCircle.haarAddCircle : Measure (AddCircle (2 * Real.pi))) := by
        rw [AddCircle.volume_eq_smul_haarAddCircle, integral_smul_measure]
      have h2 := hvol
      rw [hsc] at h2
      have htR : (ENNReal.ofReal (2 * Real.pi)).toReal ≠ 0 := by
        rw [ENNReal.toReal_ofReal Real.two_pi_pos.le]
        exact Real.two_pi_pos.ne'
      rcases smul_eq_zero.mp h2 with hc | hc
      · exact absurd hc htR
      · exact hc
    rw [MeasureTheory.L2.inner_def]
    calc (∫ x, inner ℂ ((fourierLp (T := 2 * Real.pi) 2 n) x) (VLp x)
          ∂(AddCircle.haarAddCircle : Measure (AddCircle (2 * Real.pi))))
        = ∫ x, (starRingEnd ℂ) (fourier n x) * V x
            ∂(AddCircle.haarAddCircle : Measure (AddCircle (2 * Real.pi))) := by
          refine integral_congr_ae ?_
          filter_upwards [coeFn_fourierLp (T := 2 * Real.pi) 2 n,
            hVmem.coeFn_toLp] with x h1 h2
          rw [h1, h2, RCLike.inner_apply']
      _ = 0 := hint0
  -- Fourier completeness ⇒ `VLp = 0`
  have hsp := span_fourierLp_closure_eq_top (T := 2 * Real.pi) (p := 2)
    ENNReal.ofNat_ne_top
  have horth : (Submodule.span ℂ
      (Set.range (fourierLp (T := 2 * Real.pi) 2)))ᗮ = ⊥ :=
    Submodule.topologicalClosure_eq_top_iff.mp hsp
  have hspan : ∀ w ∈ Submodule.span ℂ (Set.range (fourierLp (T := 2 * Real.pi) 2)),
      inner ℂ w VLp = 0 := by
    intro w hw
    induction hw using Submodule.span_induction with
    | mem x hx =>
        obtain ⟨n, rfl⟩ := hx
        exact hgen n
    | zero => exact inner_zero_left _
    | add x y hx hy ihx ihy => rw [inner_add_left, ihx, ihy, add_zero]
    | smul a x hx ih => rw [inner_smul_left, ih, mul_zero]
  have hVLp : VLp = 0 := by
    have hVmem' : VLp ∈ (Submodule.span ℂ
        (Set.range (fourierLp (T := 2 * Real.pi) 2)))ᗮ :=
      (Submodule.mem_orthogonal _ VLp).mpr hspan
    rw [horth] at hVmem'
    exact (Submodule.mem_bot ℂ).mp hVmem'
  -- pull back: `V = 0` a.e., hence `v = 0` a.e.
  have hVae : V =ᵐ[(AddCircle.haarAddCircle :
      Measure (AddCircle (2 * Real.pi)))] 0 :=
    (hVmem.coeFn_toLp.symm).trans (Lp.eq_zero_iff_ae_eq_zero.mp hVLp)
  have hVae_vol : V =ᵐ[(volume : Measure (AddCircle (2 * Real.pi)))] 0 := by
    rw [AddCircle.volume_eq_smul_haarAddCircle]
    exact Measure.ae_smul_measure hVae _
  have hVmap : V =ᵐ[Measure.map ((↑) : ℝ → AddCircle (2 * Real.pi))
      ((volume : Measure ℝ).restrict (Set.Ioc 0 (0 + 2 * Real.pi)))] 0 := by
    rw [hmp.map_eq]
    exact hVae_vol
  have hpull := MeasureTheory.ae_eq_comp hmp.measurable.aemeasurable hVmap
  have hpull' : ∀ᵐ φ ∂phiMeasure,
      V ((φ : ℝ) : AddCircle (2 * Real.pi)) = 0 := by
    rw [hμ]
    filter_upwards [hpull] with φ hφ
    simpa using hφ
  filter_upwards [hcomp, hpull'] with φ h1 h2
  rw [← h1]
  exact h2

/-- **Completeness**:
  span{Y_ℓ^m : ℓ ≥ 0, |m| ≤ ℓ} is dense in L²(S², dΩ).
    Every f ∈ L²(S²) is then the L²-convergent expansion
      f(θ, φ) = Σ_{ℓ=0}^∞ Σ_{m=-ℓ}^{ℓ} c_{ℓm} Y_ℓ^m(θ, φ). -/
theorem sphericalHarmonic_complete :
    (Submodule.span ℂ
      {g : L2_S2 | ∃ (ℓ : ℕ) (m : ℤ) (hm : |m| ≤ (ℓ : ℤ)),
        g = (memLp_sphericalHarmonic ℓ m hm).toLp
          (SphericalHarmonic ℓ m hm)}).topologicalClosure = ⊤ := by
  change (Submodule.span ℂ harmonicSet).topologicalClosure = ⊤
  rw [Submodule.topologicalClosure_eq_top_iff, Submodule.eq_bot_iff]
  intro f hf
  -- Step 0: orthogonality to the span transfers to every separated function.
  have hint : ∀ (m : ℤ) (q : Polynomial ℝ),
      ∫ p, (starRingEnd ℂ) (sepFun m q p) * f p ∂sphereMeasure = 0 := by
    intro m q
    have h := (Submodule.mem_orthogonal (K := Submodule.span ℂ harmonicSet) f).mp
      hf _ (toLp_sepFun_mem_span m q)
    rw [MeasureTheory.L2.inner_def] at h
    rw [← h]
    refine integral_congr_ae ?_
    filter_upwards [(memLp_sepFun m q).coeFn_toLp] with p hp
    rw [hp, RCLike.inner_apply']
  -- `f` as an L²- (hence L¹-) function on the product measure
  have hF2 : MemLp (⇑f) 2 (thetaMeasure.prod phiMeasure) := by
    rw [← sphereMeasure_eq_prod]
    exact Lp.memLp f
  have hFint : Integrable (⇑f) (thetaMeasure.prod phiMeasure) :=
    hF2.integrable one_le_two
  -- the parametrized Fourier coefficients are strongly measurable in θ
  have hc_meas : ∀ k : ℤ, StronglyMeasurable fun θ =>
      ∫ φ, Complex.exp (I * k * φ) * f (θ, φ) ∂phiMeasure := fun k =>
    MeasureTheory.StronglyMeasurable.integral_prod_right'
      (((Complex.continuous_exp.comp (continuous_const.mul
          (Complex.continuous_ofReal.comp continuous_snd))).stronglyMeasurable).mul
        (Lp.stronglyMeasurable f))
  -- Step 1 (Fubini): the orthogonality relations decouple into θ-moments of
  -- the Fourier coefficients.
  have hmoment : ∀ (k : ℤ) (q : Polynomial ℝ),
      ∫ θ, ((Real.sin θ ^ k.natAbs * q.eval (Real.cos θ) : ℝ) : ℂ) *
        (∫ φ, Complex.exp (I * k * φ) * f (θ, φ) ∂phiMeasure) ∂thetaMeasure = 0 := by
    intro k q
    have h0 : ∫ p, (starRingEnd ℂ) (sepFun (-k) q p) * f p
        ∂(thetaMeasure.prod phiMeasure) = 0 := by
      rw [← sphereMeasure_eq_prod]
      exact hint (-k) q
    obtain ⟨C, hC⟩ := sepFun_bound (-k) q
    have hI : Integrable (fun p => (starRingEnd ℂ) (sepFun (-k) q p) * f p)
        (thetaMeasure.prod phiMeasure) := by
      refine hFint.bdd_mul (c := C) ((Complex.continuous_conj.comp
        (sepFun_continuous (-k) q)).aestronglyMeasurable) ?_
      refine Filter.Eventually.of_forall fun p => ?_
      rw [RCLike.norm_conj]
      exact hC p
    rw [MeasureTheory.integral_prod _ hI] at h0
    rw [← h0]
    refine integral_congr_ae (Filter.Eventually.of_forall fun θ => ?_)
    simp only [← integral_const_mul]
    refine integral_congr_ae (Filter.Eventually.of_forall fun φ => ?_)
    simp only [show sepFun (-k) q (θ, φ) =
        ((Real.sin θ ^ (-k).natAbs * q.eval (Real.cos θ) : ℝ) : ℂ) *
          Complex.exp (I * ((-k : ℤ) : ℂ) * φ) from rfl]
    rw [map_mul, Complex.conj_ofReal, ← Complex.exp_conj,
      show (starRingEnd ℂ) (I * ((-k : ℤ) : ℂ) * (φ : ℂ)) = I * (k : ℂ) * (φ : ℂ) by
        simp only [map_mul, Complex.conj_I, Complex.conj_ofReal, map_intCast]
        push_cast
        ring,
      Int.natAbs_neg]
    ring
  -- Step 2 (θ-side): each Fourier coefficient vanishes a.e. in θ — the
  -- `sin^{|k|}θ` factor divides out on the open interval.
  have hcoef_zero : ∀ k : ℤ, ∀ᵐ θ ∂thetaMeasure,
      ∫ φ, Complex.exp (I * k * φ) * f (θ, φ) ∂phiMeasure = 0 := by
    intro k
    set u : ℝ → ℂ := fun θ => ((Real.sin θ ^ k.natAbs : ℝ) : ℂ) *
      ∫ φ, Complex.exp (I * k * φ) * f (θ, φ) ∂phiMeasure with _hu_def
    have hA := hFint.integral_norm_prod_left
    have hu_int : Integrable u thetaMeasure := by
      have hsm : AEStronglyMeasurable u thetaMeasure :=
        ((Complex.continuous_ofReal.comp
            (Real.continuous_sin.pow k.natAbs)).stronglyMeasurable.mul
          (hc_meas k)).aestronglyMeasurable
      refine hA.mono' hsm ?_
      refine Filter.Eventually.of_forall fun θ => ?_
      have hsin1 : ‖((Real.sin θ ^ k.natAbs : ℝ) : ℂ)‖ ≤ 1 := by
        rw [Complex.norm_real, Real.norm_eq_abs, abs_pow]
        exact pow_le_one₀ (abs_nonneg _)
          (abs_le.mpr ⟨Real.neg_one_le_sin _, Real.sin_le_one _⟩)
      have hcs : ‖∫ φ, Complex.exp (I * k * φ) * f (θ, φ) ∂phiMeasure‖
          ≤ ∫ φ, ‖f (θ, φ)‖ ∂phiMeasure := by
        calc ‖∫ φ, Complex.exp (I * k * φ) * f (θ, φ) ∂phiMeasure‖
            ≤ ∫ φ, ‖Complex.exp (I * k * φ) * f (θ, φ)‖ ∂phiMeasure :=
              norm_integral_le_integral_norm _
          _ = ∫ φ, ‖f (θ, φ)‖ ∂phiMeasure := by
              refine integral_congr_ae (Filter.Eventually.of_forall fun φ => ?_)
              simp only [norm_mul, norm_exp_I_int_mul, one_mul]
      change ‖((Real.sin θ ^ k.natAbs : ℝ) : ℂ) *
          ∫ φ, Complex.exp (I * k * φ) * f (θ, φ) ∂phiMeasure‖
        ≤ ∫ φ, ‖f (θ, φ)‖ ∂phiMeasure
      calc ‖((Real.sin θ ^ k.natAbs : ℝ) : ℂ) *
            ∫ φ, Complex.exp (I * k * φ) * f (θ, φ) ∂phiMeasure‖
          = ‖((Real.sin θ ^ k.natAbs : ℝ) : ℂ)‖ *
              ‖∫ φ, Complex.exp (I * k * φ) * f (θ, φ) ∂phiMeasure‖ :=
            norm_mul _ _
        _ ≤ 1 * ∫ φ, ‖f (θ, φ)‖ ∂phiMeasure :=
            mul_le_mul hsin1 hcs (norm_nonneg _) zero_le_one
        _ = ∫ φ, ‖f (θ, φ)‖ ∂phiMeasure := one_mul _
    have hu_mom : ∀ q : Polynomial ℝ,
        ∫ θ, ((q.eval (Real.cos θ) : ℝ) : ℂ) * u θ ∂thetaMeasure = 0 := by
      intro q
      rw [← hmoment k q]
      refine integral_congr_ae (Filter.Eventually.of_forall fun θ => ?_)
      change ((q.eval (Real.cos θ) : ℝ) : ℂ) *
          (((Real.sin θ ^ k.natAbs : ℝ) : ℂ) *
            ∫ φ, Complex.exp (I * k * φ) * f (θ, φ) ∂phiMeasure) =
        ((Real.sin θ ^ k.natAbs * q.eval (Real.cos θ) : ℝ) : ℂ) *
          ∫ φ, Complex.exp (I * k * φ) * f (θ, φ) ∂phiMeasure
      push_cast
      ring
    have hu0 := ae_eq_zero_of_forall_integral_polyCos_eq_zero hu_int hu_mom
    filter_upwards [hu0, ae_theta_mem_Ioo] with θ hθ hθmem
    have hsin : Real.sin θ ≠ 0 :=
      (Real.sin_pos_of_pos_of_lt_pi hθmem.1 hθmem.2).ne'
    have hcast : ((Real.sin θ ^ k.natAbs : ℝ) : ℂ) ≠ 0 :=
      Complex.ofReal_ne_zero.mpr (pow_ne_zero _ hsin)
    have hθ' : ((Real.sin θ ^ k.natAbs : ℝ) : ℂ) *
        (∫ φ, Complex.exp (I * k * φ) * f (θ, φ) ∂phiMeasure) = 0 := hθ
    exact (mul_eq_zero.mp hθ').resolve_left hcast
  -- a.e. θ-slice of `f` is in L²(phiMeasure) (Fubini for `‖f‖²`)
  have hslice_mem : ∀ᵐ θ ∂thetaMeasure,
      MemLp (fun φ => f (θ, φ)) 2 phiMeasure := by
    have hsq := (memLp_two_iff_integrable_sq_norm hF2.aestronglyMeasurable).mp hF2
    filter_upwards [hsq.prod_right_ae] with θ hθ
    exact (memLp_two_iff_integrable_sq_norm
      (((Lp.stronglyMeasurable f).comp_measurable
        measurable_prodMk_left).aestronglyMeasurable)).mpr hθ
  -- Step 3 (φ-side): Fourier completeness kills a.e. slice.
  have hslices : ∀ᵐ θ ∂thetaMeasure, ∀ᵐ φ ∂phiMeasure, f (θ, φ) = 0 := by
    have hall : ∀ᵐ θ ∂thetaMeasure, ∀ k : ℤ,
        ∫ φ, Complex.exp (I * k * φ) * f (θ, φ) ∂phiMeasure = 0 :=
      ae_all_iff.mpr hcoef_zero
    filter_upwards [hall, hslice_mem] with θ hθall hθmem
    exact ae_eq_zero_of_forall_integral_fourier_eq_zero hθmem hθall
  -- Step 4: glue the slices and conclude `f = 0` in L².
  have hms : MeasurableSet {p : ℝ × ℝ | f p ≠ 0} := by
    have hset : {p : ℝ × ℝ | f p ≠ 0} = ⇑f ⁻¹' {0}ᶜ := rfl
    rw [hset]
    exact (Lp.stronglyMeasurable f).measurable (measurableSet_singleton 0).compl
  have hnull : (thetaMeasure.prod phiMeasure) {p : ℝ × ℝ | f p ≠ 0} = 0 := by
    refine MeasureTheory.Measure.measure_prod_null_of_ae_null hms ?_
    filter_upwards [hslices] with θ hθ
    change phiMeasure (Prod.mk θ ⁻¹' {p : ℝ × ℝ | f p ≠ 0}) = 0
    exact ae_iff.mp hθ
  have h0 : ∀ᵐ p ∂(thetaMeasure.prod phiMeasure), f p = 0 := by
    rw [ae_iff]
    exact hnull
  have hae0 : ⇑f =ᵐ[sphereMeasure] 0 := by
    simp only [sphereMeasure_eq_prod]
    refine h0.mono fun p hp => ?_
    simpa using hp
  exact Lp.eq_zero_iff_ae_eq_zero.mpr hae0


end Spectra.SphericalHarmonics
