/-
Copyright (c) 2026 Spectra Formalization Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Bornemann
-/
import Spectra.OneParameterUnitaryGroup.Basic
import Spectra.YosidaHille.Basic
import Spectra.Operator.SelfAdjoint
import Spectra.Spaces.Sobolev.DensityResults
import Spectra.Spaces.Sobolev.FourierDecay
import Spectra.SpectralTheory.ResolventForm
import Mathlib.Analysis.Fourier.LpSpace
import Mathlib.Analysis.Real.Pi.Bounds
import Mathlib.Analysis.Distribution.FourierMultiplier
import Mathlib.Analysis.Distribution.AEEqOfIntegralContDiff
import Spectra.Resolvent.Range
/-!
# The Laplacian as a Self-Adjoint Operator

This file packages the negative Laplacian −Δ on H²(ℝ³) as an unbounded
operator `laplacianPMap : l2R3 →ₗ.[ℂ] l2R3` and establishes the spectral
pipeline around it.

## Architecture

This file was rewritten for the refactored Stone library.  The old design
("`Generator U` as a structure with `domain`/`op`/`symmetric` fields, built
*from* a unitary group") is inverted: the fundamental object is now the
partial linear map, self-adjointness is Mathlib's star-based `IsSelfAdjoint`
on `LinearPMap`, and the unitary group is *derived* by Stone's theorem:

```
  Spaces/Sobolev/*.lean                    this file
  ┌───────────────────┐                    ┌──────────────────────────────┐
  │ SobolevH2         │── domain ────────→ │ laplacianPMap : L2 →ₗ.[ℂ] L2 │
  │ laplacianLinearMap│── toFun ─────────→ │                              │
  │ laplacian_symm    │── IsFormalAdjoint→ │ laplacian_isSelfAdjoint      │
  │ sobolevH2_dense   │── Dense ─────────→ │   (von Neumann criterion)    │
  └───────────────────┘                    └──────────────┬───────────────┘
                                                          │ genToGroup
                                           ┌──────────────▼───────────────┐
                                           │ freeParticleGroup            │
                                           │ selfAdjointResolvent         │
                                           │ spectralPVM / spectralTheorem│
                                           └──────────────────────────────┘
```

Once `laplacian_isSelfAdjoint` is in place, the library gives for free:
* `freeParticleGroup := genToGroup laplacian_isSelfAdjoint` with
  `generator freeParticleGroup = laplacianPMap` (Stone);
* `selfAdjointResolvent laplacian_isSelfAdjoint z hz` with the norm bound
  `≤ 1/|Im z|` (proved below, *not* sorried);
* `spectralPVM laplacian_isSelfAdjoint` and the full spectral theorem.

## Analytic content

The whole file is sorry-free.  The one piece of genuine mathematics is
surjectivity of (−Δ + ε) on H² for `ε.im ≠ 0` (`laplacian_range_general`,
proved), from which the two deficiency-index conditions (−Δ ± i)
(`laplacian_range_add_I`, `laplacian_range_sub_I`) follow immediately.
Everything that was a structural obligation in the old design
(`generator_formula`, `domain_invariant`, `domain_maximal`) is now a theorem
of the Stone library.

**How surjectivity is proved (Fourier transform).** Under Plancherel, −Δ is
multiplication by `(2π)²‖ξ‖²` (`fourier_weakLaplacian`).  The equation
(−Δ + ε)ψ = φ becomes ((2π)²‖ξ‖² + ε)ψ̂ = φ̂, solved by
ψ̂ = φ̂ · `resolventSymbol ε ξ`; the estimates `|resolventSymbol ε| ≤ 1/|ε.im|`
and `(1+‖ξ‖²)·resolventSymbol ε` bounded give ψ ∈ H²
(`memSobolevH2_of_fourier_decay`).

## Main definitions

* `laplacianPMap` — −Δ with domain H²(ℝ³), as a `LinearPMap`.
* `laplacianObservable` — the same, packaged as `SelfAdjointOperator`.
* `freeParticleGroup` — the unitary group generated by −Δ via Stone.
  NB: in this library's convention (`schrodingerEquation`:
  d/dt U(t)ψ = i·A·U(t)ψ), the group generated by A = −Δ is
  U(t) = exp(it(−Δ)) = exp(−itΔ).

## Main statements

* `laplacian_isSelfAdjoint` — −Δ is self-adjoint on H²(ℝ³)
  (assembled from symmetry, density, and the two surjectivity lemmas via the
  von Neumann criterion; sorry-free).
* `fourier_weakLaplacian` — 𝓕 diagonalises −Δ: `𝓕(−Δψ) = (2π)²‖ξ‖²·𝓕ψ` a.e.
* `laplacian_range_general` — (−Δ + ε) is surjective on H² for `ε.im ≠ 0`.
* `generator_freeParticleGroup` — the generator of `freeParticleGroup` is −Δ
  (Stone's theorem).
* `laplacian_spectrum_nonneg` — eigenvalues of −Δ are ≥ 0.
* `laplacian_no_eigenvalues` — −Δ on ℝ³ has no eigenvalues (Fourier).
* `laplacian_resolvent_bound` — ‖(−Δ − z)⁻¹‖ ≤ 1/|Im z|, from
  `Spectra.Resolvent.resolvent_bound`.

## References

* [Reed, Simon, *Methods of Modern Mathematical Physics II*][reed1975], Thm X.25.
* [Hall, *Quantum Theory for Mathematicians*][hall2013], §9.6.
* [Lieb, Loss, *Analysis*][lieb2001], Chapter 7.
-/

noncomputable section

open MeasureTheory Complex Filter InnerProductSpace
open Spectra.Sobolev
open Spectra.OneParameterUnitaryGroup
open Spectra.YosidaHille
open Spectra.Resolvent
open Spectra.Operator
open Spectra.QuantumMechanics.SpectralTheory
open FourierTransform
open scoped Topology NNReal ENNReal SchwartzMap ContDiff

namespace Spectra.QuantumMechanics.Hydrogen

/-! ## −Δ as a partial linear map -/

/-- **The negative Laplacian as an unbounded operator on L²(ℝ³).**

    Domain H²(ℝ³), action `laplacianLinearMap` (= the weak −Δ from
    `Spaces/Sobolev/`).  Both fields are supplied by `Spaces/Sobolev/`,
    so this definition is sorry-free, and the domain/action lemmas below are
    `rfl`. -/
def laplacianPMap : l2R3 →ₗ.[ℂ] l2R3 where
  domain := SobolevH2
  toFun := laplacianLinearMap

/-- The domain of `laplacianPMap` is `SobolevH2` (= H²(ℝ³)).  Definitional. -/
@[simp] theorem laplacianPMap_domain : laplacianPMap.domain = SobolevH2 :=
  rfl

/-- The action of `laplacianPMap` is the weak Laplacian.  Definitional. -/
theorem laplacianPMap_apply (ψ : l2R3) (hψ : MemSobolevH2 ψ) :
    laplacianPMap ⟨ψ, hψ⟩ = weakLaplacian ψ hψ :=
  rfl

/-- Symmetry: ⟪−Δψ, φ⟫ = ⟪ψ, −Δφ⟫ on H².  Direct repackaging of
    `laplacian_symmetric`. -/
theorem laplacian_isFormalAdjoint :
    laplacianPMap.IsFormalAdjoint laplacianPMap :=
  fun ψ φ => laplacian_symmetric ψ.1 φ.1 ψ.2 φ.2

/-- H² is dense in L².  Direct repackaging of `sobolevH2_dense`. -/
theorem laplacian_domain_dense :
    Dense (laplacianPMap.domain : Set l2R3) :=
  sobolevH2_dense

/-! ## Obligation 1 (HARD): Fourier diagonalises −Δ

`𝓕(−Δψ) = (2π)²‖ξ‖² · 𝓕ψ`, as an a.e. identity of the L² representatives.

Routed through tempered distributions: the analytic core is `weakLaplacian_toTD`
(the weak Laplacian *is* the distributional −Δ); everything below it is Mathlib
plumbing (`laplacian_eq_fourierMultiplierCLM` + C_c^∞ testing). -/

/-! ### Route B′: the weak Laplacian is the distributional −Δ

`weakLaplacian_toTD` is proved by factoring the second-order identity through a
**first-order** weak=distributional bridge applied twice — so it needs only
H¹-norm density (`smooth_compactly_supported_dense_H1`, which the project has),
never H²-norm density (which it lacks).  Helpers first. -/

/-- **The analytic core.**  The weak Laplacian, as a tempered distribution, equals
    the negative distributional Laplacian.  Assembled from the first-order bridge
    (applied to `ψ` and to each `weakGradient ψ i`) and `weakLaplacian_eq_neg_sum`. -/
theorem weakLaplacian_toTD (ψ : l2R3) (hψ : MemSobolevH2 ψ) :
    Lp.toTemperedDistribution (weakLaplacian ψ hψ)
      = - Laplacian.laplacian (Lp.toTemperedDistribution ψ) := by
  -- each second distributional derivative is `toTD` of an iterated weak gradient
  have hstep : ∀ i : Fin 3,
      LineDeriv.lineDerivOp (EuclideanSpace.single i (1 : ℝ) : R3)
        (LineDeriv.lineDerivOp (EuclideanSpace.single i (1 : ℝ) : R3)
          (Lp.toTemperedDistribution ψ))
        = Lp.toTemperedDistribution (weakGradient (weakGradient ψ (sobolevH2_le_sobolevH1 hψ) i)
            (memSobolevH1_weakGradient ψ hψ i) i) := fun i => by
    rw [lineDerivOp_toTD_weakGradient ψ (sobolevH2_le_sobolevH1 hψ) i,
      lineDerivOp_toTD_weakGradient (weakGradient ψ (sobolevH2_le_sobolevH1 hψ) i)
        (memSobolevH1_weakGradient ψ hψ i) i]
  -- `Lp.toTemperedDistribution` as the underlying continuous linear map
  have htoTD : (Lp.toTemperedDistribution : l2R3 → 𝓢'(R3, ℂ))
      = ⇑(Lp.toTemperedDistributionCLM ℂ (volume : Measure R3) 2) :=
    funext fun f => (Lp.toTemperedDistributionCLM_apply f).symm
  rw [TemperedDistribution.laplacian_eq_sum (EuclideanSpace.basisFun (Fin 3) ℝ)]
  simp only [EuclideanSpace.basisFun_apply, hstep]
  rw [weakLaplacian_eq_neg_sum ψ hψ, htoTD, map_neg, map_sum]

/-- **Fourier diagonalises −Δ.**  Assembled from `weakLaplacian_toTD` (analytic
    core) and Mathlib's `laplacian_eq_fourierMultiplierCLM` via `aeEq_of_toTD_smulLeft`. -/
theorem fourier_weakLaplacian (ψ : l2R3) (hψ : MemSobolevH2 ψ) :
    (fourierL2 (weakLaplacian ψ hψ) : R3 → ℂ)
      =ᵐ[volume] fun ξ => (laplacianSymbol ξ : ℂ) * (fourierL2 ψ : R3 → ℂ) ξ := by
  have hsym : Function.HasTemperateGrowth (fun x : R3 => Complex.ofReal (‖x‖ ^ 2)) := by
    fun_prop
  -- `(2π)²‖ξ‖²` symbol equals `(2π)²` times the `‖ξ‖²` symbol, as functions
  have hsymbol : (fun ξ => (laplacianSymbol ξ : ℂ))
      = ((2 * Real.pi) ^ 2 : ℂ) • (fun x : R3 => Complex.ofReal (‖x‖ ^ 2)) := by
    ext ξ; simp only [Pi.smul_apply, smul_eq_mul, laplacianSymbol]; push_cast; ring
  -- distribution identity: toTD (𝓕 (−Δψ)) = laplacianSymbol • toTD (𝓕 ψ)
  have key : Lp.toTemperedDistribution (𝓕 (weakLaplacian ψ hψ))
      = TemperedDistribution.smulLeftCLM ℂ (fun ξ => (laplacianSymbol ξ : ℂ))
          (Lp.toTemperedDistribution (𝓕 ψ)) := by
    rw [← Lp.fourier_toTemperedDistribution_eq (weakLaplacian ψ hψ),
      ← Lp.fourier_toTemperedDistribution_eq ψ, weakLaplacian_toTD ψ hψ,
      TemperedDistribution.laplacian_eq_fourierMultiplierCLM,
      TemperedDistribution.fourierMultiplierCLM_apply, neg_smul, neg_neg,
      ← Complex.coe_smul ((2 * Real.pi) ^ 2), fourier_smul, fourier_fourierInv_eq,
      hsymbol, TemperedDistribution.smulLeftCLM_smul hsym,
      ContinuousLinearMap.smul_apply]
    congr 1
    push_cast
    ring
  -- transport across the `fourierL2 = 𝓕` bridge and apply the plumbing lemma
  simp only [fourierL2_eq]
  exact aeEq_of_toTD_smulLeft laplacianSymbol_hasTemperateGrowth
    (locallyIntegrable_laplacianSymbol_mul (𝓕 ψ)) key

/-! ## The general surjectivity lemma

Assembles the obligations: for `ε` with `ε.im ≠ 0`, `(−Δ + ε)` is onto. -/

/-- **Surjectivity of (−Δ + ε) on H²(ℝ³) for `ε.im ≠ 0`.**  For every `φ ∈ L²`
    there is `ψ ∈ H²` solving `(−Δ + ε)ψ = φ`.  The solution is built on the
    Fourier side as `ψ̂ = resolventSymbol ε · φ̂`: it lies in H² because the
    weighted multiplier `(1+‖ξ‖²)·resolventSymbol ε` is bounded, and it solves
    the equation because `((2π)²‖ξ‖² + ε)·resolventSymbol ε = 1`.  This is the
    common resolvent-surjectivity core behind the `±i` deficiency conditions. -/
theorem laplacian_range_general (ε : ℂ) (hε : ε.im ≠ 0) (φ : l2R3) :
    ∃ ψ : laplacianPMap.domain, laplacianPMap ψ + ε • (ψ : l2R3) = φ := by
  -- candidate Fourier transform of the solution: ψ̂ = φ̂ / ((2π)²‖ξ‖² + ε)
  set ĝ : R3 → ℂ := fun ξ => resolventSymbol ε ξ * (fourierL2 φ : R3 → ℂ) ξ with hĝ
  -- ψ̂ ∈ L² (bounded multiplier, `|resolventSymbol| ≤ 1/|ε.im|`)
  have hĝ_mem : MemLp ĝ 2 volume :=
    memLp_two_boundedMul (aestronglyMeasurable_resolventSymbol ε)
      (Filter.Eventually.of_forall fun ξ => norm_resolventSymbol_le hε ξ) (fourierL2 φ)
  -- the solution ψ := 𝓕⁻¹ ψ̂
  set ψ : l2R3 := fourierL2.symm (hĝ_mem.toLp ĝ) with hψ_def
  have hFψ : fourierL2 ψ = hĝ_mem.toLp ĝ := by
    rw [hψ_def, LinearIsometryEquiv.apply_symm_apply]
  have hFψ_fun : (fourierL2 ψ : R3 → ℂ) =ᵐ[volume] ĝ := by
    rw [hFψ]; exact hĝ_mem.coeFn_toLp
  -- ψ ∈ H²: `(1+‖ξ‖²)·𝓕ψ` is L² because `(1+‖ξ‖²)·resolventSymbol` is bounded
  have hψ_mem : MemSobolevH2 ψ := by
    apply memSobolevH2_of_fourier_decay
    obtain ⟨C, hCbd⟩ := exists_bound_weighted_resolventSymbol hε
    have hbase : MemLp
        (fun ξ => (((1 + ‖ξ‖ ^ 2 : ℝ) : ℂ) * resolventSymbol ε ξ) * (fourierL2 φ : R3 → ℂ) ξ)
        2 volume :=
      memLp_two_boundedMul (aestronglyMeasurable_weighted_resolventSymbol ε)
        (Filter.Eventually.of_forall hCbd) (fourierL2 φ)
    refine hbase.ae_eq ?_
    filter_upwards [hFψ_fun] with ξ hξ
    simp only [hξ, hĝ]; ring
  -- the equation, checked on the Fourier side then transported back
  refine ⟨⟨ψ, hψ_mem⟩, ?_⟩
  rw [laplacianPMap_apply ψ hψ_mem]
  -- suffices: 𝓕(−Δψ + ε•ψ) = 𝓕 φ, by injectivity of 𝓕
  apply fourierL2.injective
  rw [map_add, map_smul]
  apply L2_ext
  -- a.e.:  (2π)²‖ξ‖²·𝓕ψ + ε·𝓕ψ = ((2π)²‖ξ‖² + ε)·resolventSymbol·𝓕φ = 𝓕φ
  have hlap := fourier_weakLaplacian ψ hψ_mem
  filter_upwards [Lp.coeFn_add (fourierL2 (weakLaplacian ψ hψ_mem)) (ε • fourierL2 ψ),
    Lp.coeFn_smul ε (fourierL2 ψ), hlap, hFψ_fun] with ξ hadd hsmul hlapξ hξ
  rw [hadd, Pi.add_apply, hsmul, Pi.smul_apply, hlapξ, hξ, smul_eq_mul, hĝ]
  -- goal:  laplacianSymbol ξ * (resolventSymbol ε ξ * 𝓕φ ξ)
  --        + ε * (resolventSymbol ε ξ * 𝓕φ ξ)  =  𝓕φ ξ
  have hcancel := resolventSymbol_mul_cancel hε ξ
  -- (s + ε) * resolventSymbol = 1, so LHS = 𝓕φ ξ
  have : (laplacianSymbol ξ : ℂ) * (resolventSymbol ε ξ * (fourierL2 φ : R3 → ℂ) ξ)
       + ε * (resolventSymbol ε ξ * (fourierL2 φ : R3 → ℂ) ξ)
       = ((laplacianSymbol ξ : ℂ) + ε) * resolventSymbol ε ξ * (fourierL2 φ : R3 → ℂ) ξ := by
    ring
  rw [this, hcancel, one_mul]

/-! ## Surjectivity of `−Δ ± i` (deficiency conditions)

The two `±i` range conditions feeding the von Neumann self-adjointness criterion,
as direct instances of the Fourier-multiplier resolvent `laplacian_range_general`
(both proved, sorry-free). -/

/-- **Surjectivity of (−Δ + i) on H²(ℝ³).**  For every `φ ∈ L²` there is
    `ψ ∈ H²` with `(−Δ + i)ψ = φ`; the `+i` deficiency condition of the von
    Neumann criterion, a direct instance of `laplacian_range_general`. -/
theorem laplacian_range_add_I :
    ∀ φ : l2R3, ∃ ψ : laplacianPMap.domain,
      laplacianPMap ψ + I • (ψ : l2R3) = φ :=
  fun φ => laplacian_range_general I (by simp) φ

/-- **Surjectivity of (−Δ − i) on H²(ℝ³).**  For every `φ ∈ L²` there is
    `ψ ∈ H²` with `(−Δ − i)ψ = φ`; the `−i` deficiency condition of the von
    Neumann criterion, from `laplacian_range_general` at `ε = −i`. -/
theorem laplacian_range_sub_I :
    ∀ φ : l2R3, ∃ ψ : laplacianPMap.domain,
      laplacianPMap ψ - I • (ψ : l2R3) = φ := by
  intro φ
  obtain ⟨ψ, hψ⟩ := laplacian_range_general (-I) (by simp) φ
  exact ⟨ψ, by rw [sub_eq_add_neg, ← neg_smul]; exact hψ⟩

/-- **Self-adjointness of −Δ on H²(ℝ³).**

    Assembled from symmetry (`laplacian_isFormalAdjoint`), density
    (`laplacian_domain_dense`), and the two surjectivity lemmas
    (`laplacian_range_add_I`, `laplacian_range_sub_I`) via the library's von
    Neumann criterion.  Sorry-free. -/
theorem laplacian_isSelfAdjoint : IsSelfAdjoint laplacianPMap :=
  isSelfAdjoint_of_surjective_addSub laplacianPMap
    laplacian_isFormalAdjoint laplacian_domain_dense
    laplacian_range_add_I laplacian_range_sub_I

/-- −Δ packaged as a `SelfAdjointOperator` (kinetic energy). -/
def laplacianObservable : SelfAdjointOperator l2R3 where
  toLinearPMap := laplacianPMap
  selfAdjoint := laplacian_isSelfAdjoint

/-! ## The free-particle unitary group

Stone's theorem (`genToGroup`) turns the self-adjoint `−Δ` into the free-particle
evolution `e^{it(−Δ)}`; the generator-extraction round-trip gives back `−Δ`.
-/

/-- The free-particle unitary group generated by `−Δ`, `U(t) = e^{it(−Δ)}`. -/
def freeParticleGroup : OneParameterUnitaryGroup (H := l2R3) :=
  genToGroup laplacian_isSelfAdjoint

/-- The generator of the free-particle group is `−Δ` (Stone's theorem). -/
theorem generator_freeParticleGroup :
    generator freeParticleGroup = laplacianPMap :=
  generator_genToGroup laplacian_isSelfAdjoint

/-- The domain of the generator of the free evolution is `H²(ℝ³)`. -/
theorem freeParticleGroup_generator_domain :
    (generator freeParticleGroup).domain = SobolevH2 := by
  rw [generator_freeParticleGroup]; rfl

/-! ## Spectral properties of `−Δ` -/

/-- Any eigenvalue of `−Δ` is nonnegative: from `laplacian_nonneg`,
`λ‖ψ‖² = re⟪−Δψ, ψ⟫ = ‖∇ψ‖² ≥ 0`, and `ψ ≠ 0`. -/
theorem laplacian_spectrum_nonneg
    (ψ : l2R3) (hψ : MemSobolevH2 ψ) (lam : ℝ)
    (hψ_ne : ψ ≠ 0)
    (heig : weakLaplacian ψ hψ = (lam : ℂ) • ψ) :
    0 ≤ lam := by
  have h0 : 0 ≤ (inner (𝕜 := ℂ) (weakLaplacian ψ hψ) ψ).re :=
    laplacian_nonneg ψ hψ
  erw [heig, inner_smul_left, Complex.conj_ofReal,
    inner_self_eq_norm_sq_to_K (𝕜 := ℂ), ← Complex.ofReal_pow,
    ← Complex.ofReal_mul, Complex.ofReal_re] at h0
  -- h0 : 0 ≤ lam * ‖ψ‖ ^ 2
  have hnorm : 0 < ‖ψ‖ ^ 2 := pow_pos (norm_pos_iff.mpr hψ_ne) 2
  by_contra hlam
  exact absurd h0 (not_le.mpr (mul_neg_of_neg_of_pos (not_le.mp hlam) hnorm))

/-- `−Δ` on `L²(ℝ³)` has no eigenvalues (purely continuous spectrum).

If `−Δψ = λψ` then in Fourier space `((2π)²‖ξ‖² − λ)·𝓕ψ = 0` a.e.
(`fourier_weakLaplacian`).  The symbol `(2π)²‖ξ‖²` equals `λ` only on the sphere
`‖ξ‖ = √λ/(2π)`, a Lebesgue-null set in `ℝ³` (`Measure.addHaar_sphere`); hence
`𝓕ψ = 0` a.e. and, since `fourierL2` is a linear isometry (Plancherel), `ψ = 0`. -/
theorem laplacian_no_eigenvalues
    (lam : ℝ) (ψ : l2R3) (hψ : MemSobolevH2 ψ)
    (heig : weakLaplacian ψ hψ = (lam : ℂ) • ψ) :
    ψ = 0 := by
  -- The frequencies where the symbol `(2π)²‖ξ‖²` hits `λ` form a sphere — null.
  have hN : volume {ξ : R3 | laplacianSymbol ξ = lam} = 0 := by
    refine measure_mono_null ?_
      (Measure.addHaar_sphere (volume : Measure R3) 0 (Real.sqrt lam / (2 * Real.pi)))
    intro ξ hξ
    simp only [Set.mem_setOf_eq] at hξ
    rw [Metric.mem_sphere, dist_zero_right,
      eq_div_iff (by positivity : (2 * Real.pi : ℝ) ≠ 0)]
    have hlam : lam = (2 * Real.pi) ^ 2 * ‖ξ‖ ^ 2 := hξ.symm
    rw [hlam, Real.sqrt_mul (sq_nonneg _),
      Real.sqrt_sq (by positivity : (0 : ℝ) ≤ 2 * Real.pi), Real.sqrt_sq (norm_nonneg ξ)]
    ring
  -- Fourier-transform the eigen-equation: `fourierL2 (−Δψ) = λ · fourierL2 ψ`.
  have hsmul : fourierL2 (weakLaplacian ψ hψ) = (lam : ℂ) • fourierL2 ψ := by
    rw [heig]; exact map_smul fourierL2 (lam : ℂ) ψ
  -- a.e. pointwise: `(2π)²‖ξ‖² · 𝓕ψ ξ = λ · 𝓕ψ ξ`.
  have hae : ∀ᵐ ξ : R3, (laplacianSymbol ξ : ℂ) * (fourierL2 ψ : R3 → ℂ) ξ
      = (lam : ℂ) * (fourierL2 ψ : R3 → ℂ) ξ := by
    have hcoe : (fourierL2 (weakLaplacian ψ hψ) : R3 → ℂ)
        =ᵐ[volume] fun ξ => (lam : ℂ) * (fourierL2 ψ : R3 → ℂ) ξ := by
      rw [hsmul]
      filter_upwards [Lp.coeFn_smul (lam : ℂ) (fourierL2 ψ)] with ξ hξ
      rw [hξ, Pi.smul_apply, smul_eq_mul]
    filter_upwards [fourier_weakLaplacian ψ hψ, hcoe] with ξ h1 h2
    rw [← h1, h2]
  -- Off the null sphere `𝓕ψ ξ = 0`; hence `𝓕ψ = 0` a.e.
  have hzero_ae : (fourierL2 ψ : R3 → ℂ) =ᵐ[volume] 0 := by
    have hne : ∀ᵐ ξ : R3, laplacianSymbol ξ ≠ lam := by
      rw [ae_iff]; simpa using hN
    filter_upwards [hae, hne] with ξ h1 h2
    rw [Pi.zero_apply]
    have hz : ((laplacianSymbol ξ : ℂ) - lam) * (fourierL2 ψ : R3 → ℂ) ξ = 0 := by
      rw [sub_mul, h1, sub_self]
    rcases mul_eq_zero.mp hz with h | h
    · exact absurd (Complex.ofReal_inj.mp (sub_eq_zero.mp h)) h2
    · exact h
  -- Plancherel: `fourierL2` is injective, so `ψ = 0`.
  have hfourier_zero : fourierL2 ψ = 0 :=
    Lp.ext (hzero_ae.trans (Lp.coeFn_zero ℂ 2 (volume : Measure R3)).symm)
  exact fourierL2.injective (by rw [hfourier_zero, map_zero])

/-- Resolvent bound: `‖(−Δ − z)⁻¹‖ ≤ 1/|Im z|`. Purely abstract — from the
resolvent estimate for self-adjoint operators, no Fourier analysis needed. -/
theorem laplacian_resolvent_bound (z : ℂ) (hz : z.im ≠ 0) :
    ‖selfAdjointResolvent laplacian_isSelfAdjoint z hz‖ ≤ 1 / |z.im| := by
  rw [selfAdjointResolvent_eq_genToGroup]
  exact resolvent_bound z hz _ _ _

/-! ## Interface summary

### For `CoulombBound.lean`:
- `laplacianPMap` is the unperturbed `A`; `laplacianPMap.domain = SobolevH2`
  holds by `rfl`, so **no domain transport is needed**: a linear map
  `SobolevH2 →ₗ[ℂ] l2R3` *is* a `laplacianPMap.domain →ₗ[ℂ] l2R3`.
- `laplacianPMap_apply` bridges `laplacianPMap ⟨ψ, hψ⟩ ↔ weakLaplacian ψ hψ`
  (also `rfl`), so Hardy estimates in terms of `weakLaplacian` transfer
  verbatim to estimates in terms of `‖laplacianPMap ψ‖`.

### For `HydrogenHamiltonian.lean`:
- `kato_rellich_bound_zero laplacian_isSelfAdjoint V hV_sym hV₀ lam`
  produces `IsSelfAdjoint (perturbedOp laplacianPMap ((lam : ℂ) • V))`,
  i.e. self-adjointness of −Δ − Z/r on H²(ℝ³).
- `genToGroup` then yields the hydrogen evolution, and
  `spectralPVM`/`spectralTheorem` its spectral measure.

### Already available once `laplacian_isSelfAdjoint` is discharged:
- `selfAdjointResolvent laplacian_isSelfAdjoint` with norm ≤ 1/|Im z|;
- `spectralPVM laplacian_isSelfAdjoint` and `spectralPVM_resolvent_formula`;
- the unitary group `freeParticleGroup` with Stone's theorem.
-/

end Spectra.QuantumMechanics.Hydrogen
