/-
Copyright (c) 2026 Spectra Formalization Project. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Adam Bornemann
Filename: UnitaryEvolution/Stone/Converse.lean
-/
import Spectra.OneParameterUnitaryGroup.Basic
import Spectra.YosidaHille.Approximation.Exponential
import Spectra.YosidaHille.Helpers
import Spectra.YosidaHille.Unique
/-!
# Stone's lemma: Complete Statement

This file assembles the complete Stone's lemma, establishing a bijective
correspondence between strongly continuous one-parameter unitary groups and
self-adjoint operators on a Hilbert space.

## References

* [Stone, "On one-parameter unitary groups in Hilbert space"][stone1932]
* [von Neumann, "Über Funktionen von Funktionaloperatoren"][vonneumann1932]
* [Reed, Simon, *Methods of Modern Mathematical Physics I*][reed1980], lemma VIII.8

## Tags

Stone's lemma, unitary group, self-adjoint operator, spectral theory
-/
open InnerProductSpace Complex Filter Topology
open Spectra.Stone.Yosida
open Spectra.OneParameterUnitaryGroup
open Spectra.Stoneslemma
open scoped ComplexConjugate
variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
namespace Spectra.StonesTheorem

/-- The strongly continuous one-parameter unitary group generated by a self-adjoint
operator, built from the Yosida exponential. -/
noncomputable def genToGroup {A : H →ₗ.[ℂ] H} (hA : IsSelfAdjoint A) :
    OneParameterUnitaryGroup (H := H) :=
  let hsym : A.IsFormalAdjoint A := by
    have h := LinearPMap.adjoint_isFormalAdjoint hA.dense_domain
    rwa [LinearPMap.isSelfAdjoint_def.mp hA] at h
  let hplus  := (isSelfAdjoint_to_surjective hA).1
  let hminus := (isSelfAdjoint_to_surjective hA).2
  let hd     := hA.dense_domain
  { U := fun t => exponential hsym hplus hminus hd t
    unitary := fun t ψ φ => exponential_unitary hsym hplus hminus hd t ψ φ
    group_law := fun s t => ContinuousLinearMap.ext fun ψ => by
      rw [ContinuousLinearMap.comp_apply]
      exact exponential_group_law hsym hplus hminus hd s t ψ
    identity := ContinuousLinearMap.ext fun ψ => by
      rw [ContinuousLinearMap.id_apply]
      exact exponential_identity hsym hplus hminus hd ψ
    strong_continuous := fun ψ => exponential_strong_continuous hsym hplus hminus hd ψ }

/-- Round-trip 2 (`gen ∘ exp = id`): the generator of the constructed group is `A`. -/
lemma generator_genToGroup {A : H →ₗ.[ℂ] H} (hA : IsSelfAdjoint A) :
    generator (genToGroup hA) = A := by
  -- re-derive the four hypotheses; proof-irrelevance makes them defeq to genToGroup's `let`s
  have hsym : A.IsFormalAdjoint A := by
    have h := LinearPMap.adjoint_isFormalAdjoint hA.dense_domain
    rwa [LinearPMap.isSelfAdjoint_def.mp hA] at h
  have hplus  := (isSelfAdjoint_to_surjective hA).1
  have hminus := (isSelfAdjoint_to_surjective hA).2
  have hd     := hA.dense_domain
  -- (1)  A ≤ generator (genToGroup hA)
  have hAle : A ≤ generator (genToGroup hA) := by
    refine ⟨fun z hz => ?_, fun x y hxy => ?_⟩
    · -- domain inclusion: genDiffQuot (genToGroup hA) z → A⟨z,hz⟩
      rw [generator_domain, mem_generatorDomain]
      exact ⟨A ⟨z, hz⟩, exponential_generator_eq' hsym hplus hminus hd z hz⟩
    · -- value agreement, by uniqueness of limits
      have hgen : Tendsto (genDiffQuot (genToGroup hA) (x : H)) (𝓝[≠] 0)
          (𝓝 (generator (genToGroup hA) y)) := by
        rw [hxy]; exact generator_tendsto (genToGroup hA) y
      exact tendsto_nhds_unique
        (exponential_generator_eq' hsym hplus hminus hd (x : H) x.2) hgen
  -- (2)  generator (genToGroup hA) is self-adjoint — free, via A's deficiency + hAle
  have hSAgen : IsSelfAdjoint (generator (genToGroup hA)) := by
    have hdense' : Dense ((generator (genToGroup hA)).domain : Set H) :=
      hd.mono (SetLike.coe_subset_coe.mpr hAle.1)
    refine isSelfAdjoint_of_surjective_addSub _ (generator_isFormalAdjoint _) hdense' ?_ ?_
    · intro φ
      obtain ⟨ψ, hψ⟩ := hplus φ
      refine ⟨⟨(ψ : H), hAle.1 ψ.2⟩, ?_⟩
      rw [← hAle.2 (x := ψ) (y := ⟨(ψ : H), hAle.1 ψ.2⟩) rfl]; exact hψ
    · intro φ
      obtain ⟨ψ, hψ⟩ := hminus φ
      refine ⟨⟨(ψ : H), hAle.1 ψ.2⟩, ?_⟩
      rw [← hAle.2 (x := ψ) (y := ⟨(ψ : H), hAle.1 ψ.2⟩) rfl]; exact hψ
  -- (3)  maximality: A self-adjoint, gen self-adjoint, A ≤ gen ⟹ equal
  exact Eq.symm (IsSelfAdjoint.eq_of_le hA hSAgen hAle)

open Spectra.Resolvent in
noncomputable def stoneEquiv :
    OneParameterUnitaryGroup (H := H) ≃ {A : H →ₗ.[ℂ] H // IsSelfAdjoint A} where
  toFun  U := ⟨generator U, generator_isSelfAdjoint U⟩
  invFun A := genToGroup A.2
  left_inv  U := group_unique _ _ (generator_genToGroup (generator_isSelfAdjoint U))
  right_inv A := Subtype.ext (generator_genToGroup A.2)

@[simp] lemma stoneEquiv_apply (U : OneParameterUnitaryGroup (H := H)) :
    (stoneEquiv U : H →ₗ.[ℂ] H) = generator U := rfl

@[simp] lemma stoneEquiv_symm_apply {A : H →ₗ.[ℂ] H} (hA : IsSelfAdjoint A) :
    stoneEquiv.symm ⟨A, hA⟩ = genToGroup hA := rfl

@[simp] lemma stoneEquiv_symm_U {A : H →ₗ.[ℂ] H} (hA : IsSelfAdjoint A) (t : ℝ) (ψ : H) :
    (stoneEquiv.symm ⟨A, hA⟩).U t ψ = (genToGroup hA).U t ψ := rfl

/-- For self-adjoint `A` and `ψ ∈ dom A`, the orbit `t ↦ U_A(t) ψ` solves `f'(t) = i A f(t)`. -/
lemma stone_orbit_hasDerivAt (U : OneParameterUnitaryGroup (H := H))
    (ψ : (generator U).domain) (t : ℝ) :
    HasDerivAt (fun s => U.U s (ψ : H))
      (I • generator U ⟨U.U t (ψ : H), generator_domain_invariant U t ψ⟩) t := by
  rw [generator_comm]; exact unitary_orbit_hasDerivAt U ψ t

end Spectra.StonesTheorem
