/-
Copyright (c) 2026 Spectra Formalization Project. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Adam Bornemann
-/

import Spectra.QuantumMechanics.OneParameterUnitaryGroup.Basic
import Spectra.QuantumMechanics.Observable.Basic
import Spectra.QuantumMechanics.Stone.Basic
import Spectra.SobolevSpaces.DensityResults
import Spectra.SpectralTheory.ResolventForm
import Mathlib.Analysis.Fourier.LpSpace
import Mathlib.Analysis.Real.Pi.Bounds
import Mathlib.Analysis.Distribution.FourierMultiplier
import Mathlib.Analysis.Distribution.AEEqOfIntegralContDiff
import Spectra.Resolvent.Range
/-!
# The Laplacian as a Self-Adjoint Operator

This file packages the negative Laplacian −Δ on H²(ℝ³) as an unbounded
operator `laplacianPMap : L2_R3 →ₗ.[ℂ] L2_R3` and establishes the spectral
pipeline around it.

## Architecture

This file was rewritten for the refactored Stone library.  The old design
("`Generator U` as a structure with `domain`/`op`/`symmetric` fields, built
*from* a unitary group") is inverted: the fundamental object is now the
partial linear map, self-adjointness is Mathlib's star-based `IsSelfAdjoint`
on `LinearPMap`, and the unitary group is *derived* by Stone's theorem:

```
  SobolevSpaces.lean                       this file
  ┌───────────────────┐                    ┌──────────────────────────────┐
  │ SobolevH2         │── domain ────────→ │ laplacianPMap : L2 →ₗ.[ℂ] L2 │
  │ laplacianLinearMap│── toFun ─────────→ │                              │
  │ laplacian_symm    │── IsFormalAdjoint→ │ laplacian_isSelfAdjoint      │
  │ sobolevH2_dense   │── Dense ─────────→ │   (von Neumann criterion)    │
  └───────────────────┘                    └──────────────┬───────────────┘
                                                          │ genToGroup
                                           ┌──────────────▼───────────────┐
                                           │ freeParticleGroup            │
                                           │ selfAdjointResolvent         │
                                           │ spectralPVM / spectralTheorem│
                                           └──────────────────────────────┘
```

Once `laplacian_isSelfAdjoint` is in place, the library gives for free:
* `freeParticleGroup := genToGroup laplacian_isSelfAdjoint` with
  `generator freeParticleGroup = laplacianPMap` (Stone);
* `selfAdjointResolvent laplacian_isSelfAdjoint z hz` with the norm bound
  `≤ 1/|Im z|` (proved below, *not* sorried);
* `spectralPVM laplacian_isSelfAdjoint` and the full spectral theorem.

## Remaining analytic content

Exactly two sorries carry real mathematics: surjectivity of (−Δ ± i) on H²
(`laplacian_range_add_I`, `laplacian_range_sub_I`).  Everything that was a
structural obligation in the old design (`generator_formula`,
`domain_invariant`, `domain_maximal`) is now a theorem of the Stone library.

**Route via Fourier transform:** under Plancherel, −Δ is multiplication by
|ξ|².  The equation (−Δ ± i)ψ = φ becomes (|ξ|² ± i)ψ̂ = φ̂, solved by
ψ̂ = φ̂/(|ξ|² ± i); the estimates |1/(|ξ|² ± i)| ≤ 1 and
(1+|ξ|²)²/||ξ|² ± i|² ≤ C give ψ ∈ H².  Interface: `sobolevH2_fourier_char`.

**Route via Lax–Milgram:** the form a(u,v) = ⟨∇u, ∇v⟩ ∓ i⟨u, v⟩ is coercive
on H¹ (|a(u,u)| ≥ ‖u‖²); Riesz representation produces u ∈ H¹ with
a(u,·) = ⟨φ,·⟩, and elliptic regularity lifts u to H².

## Main definitions

* `laplacianPMap` — −Δ with domain H²(ℝ³), as a `LinearPMap`.
* `laplacianObservable` — the same, packaged as `UnboundedObservable`.
* `freeParticleGroup` — the unitary group generated by −Δ via Stone.
  NB: in this library's convention (`schrodingerEquation`:
  d/dt U(t)ψ = i·A·U(t)ψ), the group generated by A = −Δ is
  U(t) = exp(it(−Δ)) = exp(−itΔ).
* `freeGreensFunction` — the explicit kernel e^{−√(−z)|x|}/(4π|x|).

## Main statements

* `laplacian_isSelfAdjoint` — −Δ is self-adjoint on H²(ℝ³)
  (assembled from the two surjectivity sorries; no other gaps).
* `laplacian_spectrum_nonneg` — eigenvalues of −Δ are ≥ 0 (**proved**).
* `laplacian_no_eigenvalues` — −Δ on ℝ³ has no eigenvalues (Fourier; **proved**).
* `laplacian_resolvent_bound` — ‖(−Δ − z)⁻¹‖ ≤ 1/|Im z| (**proved**, from
  `Spectra.Resolvent.resolvent_bound`).

## References

* [Reed, Simon, *Methods of Modern Mathematical Physics II*][reed1975], Thm X.25.
* [Hall, *Quantum Theory for Mathematicians*][hall2013], §9.6.
* [Lieb, Loss, *Analysis*][lieb2001], Chapter 7.
-/

noncomputable section

open MeasureTheory Complex Filter InnerProductSpace
open Spectra.Sobolev
open Spectra.QuantumMechanics
open Spectra.QuantumMechanics.OneParameterUnitaryGroup
open Spectra.QuantumMechanics.Observable
open Spectra.QuantumMechanics.Stoneslemma
open Spectra.QuantumMechanics.StonesTheorem
open Spectra.Resolvent
open Spectra.QuantumMechanics.SpectralTheory
open FourierTransform
open scoped Topology NNReal ENNReal SchwartzMap ContDiff

namespace Spectra.QuantumMechanics.Hydrogen

/-! ## −Δ as a partial linear map -/

/-- **The negative Laplacian as an unbounded operator on L²(ℝ³).**

    Domain H²(ℝ³), action `laplacianLinearMap` (= the weak −Δ from
    `SobolevSpaces.lean`).  Both fields are supplied by `SobolevSpaces.lean`,
    so this definition is sorry-free, and the domain/action lemmas below are
    `rfl`. -/
def laplacianPMap : L2_R3 →ₗ.[ℂ] L2_R3 where
  domain := SobolevH2
  toFun := laplacianLinearMap

@[simp] theorem laplacianPMap_domain : laplacianPMap.domain = SobolevH2 :=
  rfl

/-- The action of `laplacianPMap` is the weak Laplacian.  Definitional. -/
theorem laplacianPMap_apply (ψ : L2_R3) (hψ : MemSobolevH2 ψ) :
    laplacianPMap ⟨ψ, hψ⟩ = weakLaplacian ψ hψ :=
  rfl

/-- Symmetry: ⟪−Δψ, φ⟫ = ⟪ψ, −Δφ⟫ on H².  Direct repackaging of
    `laplacian_symmetric`. -/
theorem laplacian_isFormalAdjoint :
    laplacianPMap.IsFormalAdjoint laplacianPMap :=
  fun ψ φ => laplacian_symmetric ψ.1 φ.1 ψ.2 φ.2

/-- H² is dense in L².  Direct repackaging of `sobolevH2_dense`. -/
theorem laplacian_domain_dense :
    Dense (laplacianPMap.domain : Set L2_R3) :=
  sobolevH2_dense

/-- The L² Fourier transform on `L²(ℝ³)`, as an isometric equivalence (Plancherel).

    A literal one-liner: the project's custom `MeasureSpace R3` instance was removed
    (see `SobolevSpaces/WeakDerivative.lean`) so that `L2_R3`'s measure IS Mathlib's
    `measureSpaceOfInnerProductSpace` volume — the same measure `Lp.fourierTransformₗᵢ`
    lives over.  No measure-diamond transport needed. -/
def fourierL2 : L2_R3 ≃ₗᵢ[ℂ] L2_R3 :=
  Lp.fourierTransformₗᵢ R3 ℂ

/-! ## The Fourier symbol of −Δ -/

/-- The multiplier that −Δ becomes under the Fourier transform: `m(ξ) = (2π)²‖ξ‖²`
    (real, `≥ 0`).  Content of `SchwartzMap.laplacian_eq_fourierMultiplierCLM`
    transported to `L2_R3`. -/
def laplacianSymbol (ξ : R3) : ℝ := (2 * Real.pi) ^ 2 * ‖ξ‖ ^ 2

lemma laplacianSymbol_nonneg (ξ : R3) : 0 ≤ laplacianSymbol ξ :=
  mul_nonneg (sq_nonneg _) (sq_nonneg _)

/-- `fourierL2` is definitionally the L² Fourier transform `𝓕`. -/
lemma fourierL2_eq (f : L2_R3) : fourierL2 f = 𝓕 f := rfl

/-- The symbol `(2π)²‖ξ‖²` as a complex function has temperate growth. -/
lemma laplacianSymbol_hasTemperateGrowth :
    Function.HasTemperateGrowth (fun ξ : R3 => (laplacianSymbol ξ : ℂ)) := by
  unfold laplacianSymbol; fun_prop

/-! ## Obligation 1 (HARD): Fourier diagonalises −Δ

`𝓕(−Δψ) = (2π)²‖ξ‖² · 𝓕ψ`, as an a.e. identity of the L² representatives.

Routed through tempered distributions: the analytic core is `weakLaplacian_toTD`
(the weak Laplacian *is* the distributional −Δ); everything below it is Mathlib
plumbing (`laplacian_eq_fourierMultiplierCLM` + C_c^∞ testing). -/

/-! ### Route B′: the weak Laplacian is the distributional −Δ

`weakLaplacian_toTD` is proved by factoring the second-order identity through a
**first-order** weak=distributional bridge applied twice — so it needs only
H¹-norm density (`smooth_compactly_supported_dense_H1`, which the project has),
never H²-norm density (which it lacks).  Helpers first. -/

/-- The weak gradient of an `H²` function is itself `H¹`: its weak `j`-derivative
    is the `(i,j)` second derivative of the original, which exists by `hψ.2 i j`. -/
lemma memSobolevH1_weakGradient (ψ : L2_R3) (hψ : MemSobolevH2 ψ) (i : Fin 3) :
    MemSobolevH1 (weakGradient ψ (sobolevH2_le_H1 hψ) i) := by
  intro j
  obtain ⟨g, mid, hmid_i, hmid_j⟩ := hψ.2 i j
  refine ⟨g, ?_⟩
  have hmid : mid = weakGradient ψ (sobolevH2_le_H1 hψ) i :=
    hasWeakDerivative_unique ψ i mid _ hmid_i (weakGradient_spec ψ (sobolevH2_le_H1 hψ) i)
  rwa [hmid] at hmid_j

/-- `−Δψ` as the iterated weak gradient: `weakLaplacian ψ = −Σᵢ ∂ᵢ(∂ᵢψ)`. -/
lemma weakLaplacian_eq_neg_sum (ψ : L2_R3) (hψ : MemSobolevH2 ψ) :
    weakLaplacian ψ hψ
      = -∑ i, weakGradient (weakGradient ψ (sobolevH2_le_H1 hψ) i)
          (memSobolevH1_weakGradient ψ hψ i) i := by
  unfold weakLaplacian
  congr 1
  refine Finset.sum_congr rfl (fun i _ => ?_)
  obtain ⟨mid, hmid_i, hmid_ii⟩ := (hψ.2 i i).choose_spec
  have hmid : mid = weakGradient ψ (sobolevH2_le_H1 hψ) i :=
    hasWeakDerivative_unique ψ i mid _ hmid_i (weakGradient_spec ψ (sobolevH2_le_H1 hψ) i)
  rw [hmid] at hmid_ii
  exact hasWeakDerivative_unique _ i _ _ hmid_ii
    (weakGradient_spec _ (memSobolevH1_weakGradient ψ hψ i) i)

/-- The first-order bridge for a **smooth compactly-supported** function: here it is
    classical, via `lineDerivOp_toTemperedDistributionCLM_eq` on the Schwartz map. -/
lemma lineDerivOp_toTD_of_smooth (φ : R3 → ℂ) (hφ : ContDiff ℝ ∞ φ)
    (hsupp : HasCompactSupport φ) (i : Fin 3) :
    LineDeriv.lineDerivOp (EuclideanSpace.single i (1 : ℝ) : R3)
        (Lp.toTemperedDistribution ((memLp_of_smooth_compactSupport φ hφ hsupp).toLp φ))
      = Lp.toTemperedDistribution ((memLp_partialDeriv φ i hφ hsupp).toLp
          (fun x => fderiv ℝ φ x (EuclideanSpace.single i 1))) := by
  set m : R3 := EuclideanSpace.single i (1 : ℝ) with hm
  set φ𝓢 : 𝓢(R3, ℂ) := hsupp.toSchwartzMap hφ with hφ𝓢
  have hcoe : (⇑φ𝓢 : R3 → ℂ) = φ := rfl
  -- both L² approximants agree a.e. with the corresponding Schwartz maps
  have hLp1 : (memLp_of_smooth_compactSupport φ hφ hsupp).toLp φ = φ𝓢.toLp 2 volume := by
    apply Lp.ext
    filter_upwards [(memLp_of_smooth_compactSupport φ hφ hsupp).coeFn_toLp,
      φ𝓢.coeFn_toLp 2 volume] with x h1 h2
    rw [h1, h2, hcoe]
  have hLp2 : (memLp_partialDeriv φ i hφ hsupp).toLp (fun x => fderiv ℝ φ x m)
      = (LineDeriv.lineDerivOp m φ𝓢).toLp 2 volume := by
    apply Lp.ext
    filter_upwards [(memLp_partialDeriv φ i hφ hsupp).coeFn_toLp,
      (LineDeriv.lineDerivOp m φ𝓢).coeFn_toLp 2 volume] with x h1 h2
    rw [h1, h2, SchwartzMap.lineDerivOp_apply_eq_fderiv, hcoe]
  rw [hLp1, hLp2, Lp.toTemperedDistribution_toLp_eq, Lp.toTemperedDistribution_toLp_eq]
  exact TemperedDistribution.lineDerivOp_toTemperedDistributionCLM_eq φ𝓢 m

/-- **First-order bridge (the new analytic content).**  The distributional `i`-th
    partial derivative of an `H¹` function's tempered distribution equals the
    tempered distribution of its weak derivative.

    Proof (Route B′): approximate `f` by `C_c^∞` in the H¹ norm
    (`smooth_compactly_supported_dense_H1` — first derivatives converge in L²);
    for each smooth approximant the identity is classical (`lineDerivOp_toTD_of_smooth`);
    pass to the limit using that `toTemperedDistributionCLM` and `∂ᵢ` are continuous
    on `𝓢'` (T₂). -/
lemma lineDerivOp_toTD_weakGradient (f : L2_R3) (hf : MemSobolevH1 f) (i : Fin 3) :
    LineDeriv.lineDerivOp (EuclideanSpace.single i (1 : ℝ) : R3) (Lp.toTemperedDistribution f)
      = Lp.toTemperedDistribution (weakGradient f hf i) := by
  set m : R3 := EuclideanSpace.single i (1 : ℝ) with hm
  -- H¹ approximating sequence of `C_c^∞` functions (ε = 1/(n+1))
  choose φ hφ hsupp hand using fun n : ℕ =>
    meyers_serrin_approx_multi f (weakGradient f hf) (weakGradient_spec f hf)
      (1 / (n + 1 : ℝ)) (by positivity)
  set g : ℕ → L2_R3 :=
    fun n => (memLp_of_smooth_compactSupport (φ n) (hφ n) (hsupp n)).toLp (φ n) with hg
  set dgn : ℕ → L2_R3 := fun n => (memLp_partialDeriv (φ n) i (hφ n) (hsupp n)).toLp
    (fun x => fderiv ℝ (φ n) x (EuclideanSpace.single i 1)) with hdgn
  -- `Lp.toTemperedDistribution` is continuous (it is a CLM)
  have htoTD : (Lp.toTemperedDistribution : L2_R3 → 𝓢'(R3, ℂ))
      = ⇑(Lp.toTemperedDistributionCLM ℂ (volume : Measure R3) 2) :=
    funext fun x => (Lp.toTemperedDistributionCLM_apply x).symm
  have hcont_toTD : Continuous (Lp.toTemperedDistribution : L2_R3 → 𝓢'(R3, ℂ)) := by
    rw [htoTD]; exact (Lp.toTemperedDistributionCLM ℂ (volume : Measure R3) 2).continuous
  -- L² convergence from the 1/(n+1) bounds
  have hg_tend : Tendsto g atTop (𝓝 f) := by
    rw [tendsto_iff_norm_sub_tendsto_zero]
    refine squeeze_zero (fun n => norm_nonneg _) (fun n => ?_)
      tendsto_one_div_add_atTop_nhds_zero_nat
    rw [norm_sub_rev]; exact (hand n).1.le
  have hdg_tend : Tendsto dgn atTop (𝓝 (weakGradient f hf i)) := by
    rw [tendsto_iff_norm_sub_tendsto_zero]
    refine squeeze_zero (fun n => norm_nonneg _) (fun n => ?_)
      tendsto_one_div_add_atTop_nhds_zero_nat
    rw [norm_sub_rev]; exact ((hand n).2 i).le
  -- the sequence `n ↦ ∂_m (toTD (gₙ))` has two limits; conclude by T₂ uniqueness
  refine tendsto_nhds_unique (l := Filter.atTop)
    (f := fun n => LineDeriv.lineDerivOp m (Lp.toTemperedDistribution (g n))) ?_ ?_
  · exact ((ContinuousLineDeriv.continuous_lineDerivOp m).tendsto _).comp
      ((hcont_toTD.tendsto f).comp hg_tend)
  · have heq : (fun n => LineDeriv.lineDerivOp m (Lp.toTemperedDistribution (g n)))
        = fun n => Lp.toTemperedDistribution (dgn n) :=
      funext fun n => lineDerivOp_toTD_of_smooth (φ n) (hφ n) (hsupp n) i
    rw [heq]
    exact (hcont_toTD.tendsto (weakGradient f hf i)).comp hdg_tend

/-- **The analytic core.**  The weak Laplacian, as a tempered distribution, equals
    the negative distributional Laplacian.  Assembled from the first-order bridge
    (applied to `ψ` and to each `weakGradient ψ i`) and `weakLaplacian_eq_neg_sum`. -/
theorem weakLaplacian_toTD (ψ : L2_R3) (hψ : MemSobolevH2 ψ) :
    Lp.toTemperedDistribution (weakLaplacian ψ hψ)
      = - Laplacian.laplacian (Lp.toTemperedDistribution ψ) := by
  -- each second distributional derivative is `toTD` of an iterated weak gradient
  have hstep : ∀ i : Fin 3,
      LineDeriv.lineDerivOp (EuclideanSpace.single i (1 : ℝ) : R3)
        (LineDeriv.lineDerivOp (EuclideanSpace.single i (1 : ℝ) : R3)
          (Lp.toTemperedDistribution ψ))
        = Lp.toTemperedDistribution (weakGradient (weakGradient ψ (sobolevH2_le_H1 hψ) i)
            (memSobolevH1_weakGradient ψ hψ i) i) := fun i => by
    rw [lineDerivOp_toTD_weakGradient ψ (sobolevH2_le_H1 hψ) i,
      lineDerivOp_toTD_weakGradient (weakGradient ψ (sobolevH2_le_H1 hψ) i)
        (memSobolevH1_weakGradient ψ hψ i) i]
  -- `Lp.toTemperedDistribution` as the underlying continuous linear map
  have htoTD : (Lp.toTemperedDistribution : L2_R3 → 𝓢'(R3, ℂ))
      = ⇑(Lp.toTemperedDistributionCLM ℂ (volume : Measure R3) 2) :=
    funext fun f => (Lp.toTemperedDistributionCLM_apply f).symm
  rw [TemperedDistribution.laplacian_eq_sum (EuclideanSpace.basisFun (Fin 3) ℝ)]
  simp only [EuclideanSpace.basisFun_apply, hstep]
  rw [weakLaplacian_eq_neg_sum ψ hψ, htoTD, map_neg, map_sum]

/-- Local integrability of `(2π)²‖ξ‖² · g` for `g ∈ L²`: continuous × L²-loc. -/
lemma locallyIntegrable_laplacianSymbol_mul (g : L2_R3) :
    LocallyIntegrable (fun ξ => (laplacianSymbol ξ : ℂ) * (g : R3 → ℂ) ξ) volume := by
  have hLI : LocallyIntegrable (g : R3 → ℂ) volume :=
    (Lp.memLp g).locallyIntegrable one_le_two
  rw [MeasureTheory.locallyIntegrable_iff]
  intro K hK
  exact IntegrableOn.continuousOn_mul
    (Continuous.continuousOn (by unfold laplacianSymbol; fun_prop))
    (hLI.integrableOn_isCompact hK) hK

/-- Plumbing: a distributional identity `toTD A = (m • ·)(toTD B)` with `m` of
    temperate growth recovers the a.e. pointwise product, by testing against
    `C_c^∞` (`ae_eq_of_integral_contDiff_smul_eq`). -/
lemma aeEq_of_toTD_smulLeft {A B : L2_R3} {m : R3 → ℂ} (hm : Function.HasTemperateGrowth m)
    (hmloc : LocallyIntegrable (fun ξ => m ξ * (B : R3 → ℂ) ξ) volume)
    (h : Lp.toTemperedDistribution A
        = TemperedDistribution.smulLeftCLM ℂ m (Lp.toTemperedDistribution B)) :
    (A : R3 → ℂ) =ᵐ[volume] fun ξ => m ξ * (B : R3 → ℂ) ξ := by
  refine ae_eq_of_integral_contDiff_smul_eq
    ((Lp.memLp A).locallyIntegrable one_le_two) hmloc (fun g hg hgsupp => ?_)
  -- view the real C_c^∞ test function `g` as a complex Schwartz map
  set gℂ : 𝓢(R3, ℂ) :=
    (hgsupp.comp_left (g := ((↑) : ℝ → ℂ)) Complex.ofReal_zero).toSchwartzMap
      (Complex.ofRealCLM.contDiff.comp hg) with hgℂ
  have hgℂ_coe : ⇑gℂ = fun x => ((g x : ℝ) : ℂ) := rfl
  have hpair := DFunLike.congr_fun h gℂ
  rw [Lp.toTemperedDistribution_apply, TemperedDistribution.smulLeftCLM_apply_apply,
    Lp.toTemperedDistribution_apply] at hpair
  simp only [hgℂ_coe, SchwartzMap.smulLeftCLM_apply_apply hm, smul_eq_mul,
    Complex.real_smul] at hpair ⊢
  rw [hpair]
  refine integral_congr_ae (Filter.Eventually.of_forall (fun x => ?_))
  ring

/-- **Fourier diagonalises −Δ.**  Assembled from `weakLaplacian_toTD` (analytic
    core) and Mathlib's `laplacian_eq_fourierMultiplierCLM` via `aeEq_of_toTD_smulLeft`. -/
theorem fourier_weakLaplacian (ψ : L2_R3) (hψ : MemSobolevH2 ψ) :
    (fourierL2 (weakLaplacian ψ hψ) : R3 → ℂ)
      =ᵐ[volume] fun ξ => (laplacianSymbol ξ : ℂ) * (fourierL2 ψ : R3 → ℂ) ξ := by
  have hsym : Function.HasTemperateGrowth (fun x : R3 => Complex.ofReal (‖x‖ ^ 2)) := by
    fun_prop
  -- `(2π)²‖ξ‖²` symbol equals `(2π)²` times the `‖ξ‖²` symbol, as functions
  have hsymbol : (fun ξ => (laplacianSymbol ξ : ℂ))
      = ((2 * Real.pi) ^ 2 : ℂ) • (fun x : R3 => Complex.ofReal (‖x‖ ^ 2)) := by
    ext ξ; simp only [Pi.smul_apply, smul_eq_mul, laplacianSymbol]; push_cast; ring
  -- distribution identity: toTD (𝓕 (−Δψ)) = laplacianSymbol • toTD (𝓕 ψ)
  have key : Lp.toTemperedDistribution (𝓕 (weakLaplacian ψ hψ))
      = TemperedDistribution.smulLeftCLM ℂ (fun ξ => (laplacianSymbol ξ : ℂ))
          (Lp.toTemperedDistribution (𝓕 ψ)) := by
    rw [← Lp.fourier_toTemperedDistribution_eq (weakLaplacian ψ hψ),
      ← Lp.fourier_toTemperedDistribution_eq ψ, weakLaplacian_toTD ψ hψ,
      TemperedDistribution.laplacian_eq_fourierMultiplierCLM,
      TemperedDistribution.fourierMultiplierCLM_apply, neg_smul, neg_neg,
      ← Complex.coe_smul ((2 * Real.pi) ^ 2), fourier_smul, fourier_fourierInv_eq,
      hsymbol, TemperedDistribution.smulLeftCLM_smul hsym,
      ContinuousLinearMap.smul_apply]
    congr 1
    push_cast
    ring
  -- transport across the `fourierL2 = 𝓕` bridge and apply the plumbing lemma
  simp only [fourierL2_eq]
  exact aeEq_of_toTD_smulLeft laplacianSymbol_hasTemperateGrowth
    (locallyIntegrable_laplacianSymbol_mul (𝓕 ψ)) key

/-! ## Obligation 2 (HARD): H² ⇐ Fourier decay

If `(1+‖ξ‖²)·𝓕ψ ∈ L²` then `ψ ∈ H²`.  (The ⇒ direction is not needed for
surjectivity.)  Proved via the *converse* of the first-order bridge: the Fourier
multiplier `2πi⟪ξ,eₖ⟫` builds the weak derivatives. -/

/-- Converse of `aeEq_of_toTD_smulLeft`: an a.e. pointwise product lifts to a
    distributional `smulLeft` identity (test against all Schwartz `u`). -/
lemma toTD_smulLeft_eq {A B : L2_R3} {m : R3 → ℂ} (hm : Function.HasTemperateGrowth m)
    (hAB : (A : R3 → ℂ) =ᵐ[volume] fun ξ => m ξ * (B : R3 → ℂ) ξ) :
    Lp.toTemperedDistribution A
      = TemperedDistribution.smulLeftCLM ℂ m (Lp.toTemperedDistribution B) := by
  ext u
  rw [TemperedDistribution.smulLeftCLM_apply_apply, Lp.toTemperedDistribution_apply,
    Lp.toTemperedDistribution_apply]
  simp only [SchwartzMap.smulLeftCLM_apply_apply hm]
  refine integral_congr_ae ?_
  filter_upwards [hAB] with ξ hξ
  simp only [smul_eq_mul, hξ]; ring

/-- Converse of the first-order bridge: a distributional identity
    `∂_{eₖ}(toTD ψ) = toTD g` yields a weak derivative `HasWeakDerivative ψ k g`
    (test against `C_c^∞`). -/
lemma hasWeakDerivative_of_distEq (ψ g : L2_R3) (k : Fin 3)
    (hd : LineDeriv.lineDerivOp (EuclideanSpace.single k (1 : ℝ) : R3)
        (Lp.toTemperedDistribution ψ) = Lp.toTemperedDistribution g) :
    HasWeakDerivative ψ k g := by
  intro φ hφ hsupp
  set φ𝓢 : 𝓢(R3, ℂ) := hsupp.toSchwartzMap hφ with hφ𝓢
  have hcoe : (⇑φ𝓢 : R3 → ℂ) = φ := rfl
  have hpair := DFunLike.congr_fun hd φ𝓢
  rw [TemperedDistribution.lineDerivOp_apply_apply, Lp.toTemperedDistribution_apply,
    Lp.toTemperedDistribution_apply] at hpair
  simp only [SchwartzMap.neg_apply, SchwartzMap.lineDerivOp_apply_eq_fderiv, hcoe,
    smul_eq_mul, neg_mul] at hpair
  rw [integral_neg] at hpair
  -- hpair : -∫ fderiv·ψ = ∫ φ·g ;  goal : ∫ ψ·fderiv = -∫ g·φ
  have h1 : ∫ x, ψ x * fderiv ℝ φ x (EuclideanSpace.single k 1)
      = ∫ x, fderiv ℝ φ x (EuclideanSpace.single k 1) * ψ x := by simp_rw [mul_comm]
  have h2 : ∫ x, g x * φ x = ∫ x, φ x * g x := by simp_rw [mul_comm]
  rw [h1, h2]
  linear_combination -hpair

/-- The Fourier multiplier of the `k`-th partial derivative: `2πi⟪ξ,eₖ⟫`. -/
def derivSymbol (k : Fin 3) (ξ : R3) : ℂ :=
  2 * Real.pi * Complex.I * ((inner ℝ ξ (EuclideanSpace.single k (1 : ℝ)) : ℝ) : ℂ)

lemma derivSymbol_hasTemperateGrowth (k : Fin 3) :
    Function.HasTemperateGrowth (derivSymbol k) := by unfold derivSymbol; fun_prop

/-- `𝓕` is injective on `𝓢'`. -/
lemma fourierTD_injective :
    Function.Injective (𝓕 : 𝓢'(R3, ℂ) → 𝓢'(R3, ℂ)) := fun a b hab => by
  have := congrArg (fun x => (𝓕⁻ x : 𝓢'(R3, ℂ))) hab
  simpa only [fourierInv_fourier_eq] using this

/-- **Construct the `k`-th weak derivative from Fourier decay.**  If
    `derivSymbol k · 𝓕ψ ∈ L²`, its inverse Fourier transform `g` is the weak
    `k`-derivative of `ψ`, with `𝓕g = derivSymbol k · 𝓕ψ`. -/
lemma weakDeriv_construct (ψ : L2_R3) (k : Fin 3)
    (hmem : MemLp (fun ξ => derivSymbol k ξ * (fourierL2 ψ : R3 → ℂ) ξ) 2 volume) :
    ∃ g : L2_R3, HasWeakDerivative ψ k g ∧
      (fourierL2 g : R3 → ℂ) =ᵐ[volume] fun ξ => derivSymbol k ξ * (fourierL2 ψ : R3 → ℂ) ξ := by
  refine ⟨fourierL2.symm (hmem.toLp _), ?_, ?_⟩
  swap
  · rw [LinearIsometryEquiv.apply_symm_apply]; exact hmem.coeFn_toLp
  -- the Fourier characterisation of the candidate `g`
  have hfg : (fourierL2 (fourierL2.symm (hmem.toLp _)) : R3 → ℂ)
      =ᵐ[volume] fun ξ => derivSymbol k ξ * (fourierL2 ψ : R3 → ℂ) ξ := by
    rw [LinearIsometryEquiv.apply_symm_apply]; exact hmem.coeFn_toLp
  set g : L2_R3 := fourierL2.symm (hmem.toLp _) with hgdef
  -- distribution identity  ∂_{eₖ}(toTD ψ) = toTD g, then test against C_c^∞
  apply hasWeakDerivative_of_distEq
  apply fourierTD_injective
  have hg₀ : Function.HasTemperateGrowth
      (fun ξ : R3 => ((inner ℝ ξ (EuclideanSpace.single k (1 : ℝ)) : ℝ) : ℂ)) := by fun_prop
  rw [TemperedDistribution.fourier_lineDerivOp_eq, Lp.fourier_toTemperedDistribution_eq,
    Lp.fourier_toTemperedDistribution_eq]
  simp only [← fourierL2_eq]
  rw [toTD_smulLeft_eq (derivSymbol_hasTemperateGrowth k) hfg,
    ← ContinuousLinearMap.smul_apply, ← TemperedDistribution.smulLeftCLM_smul hg₀]
  congr 2

theorem memSobolevH2_of_fourier_decay (ψ : L2_R3)
    (h : MemLp (fun ξ => ((1 + ‖ξ‖ ^ 2 : ℝ) : ℂ) * (fourierL2 ψ : R3 → ℂ) ξ) 2 volume) :
    MemSobolevH2 ψ := by
  -- `‖derivSymbol k ξ‖ ≤ 2π‖ξ‖`, and the weaker `≤ 2π(1+‖ξ‖²)`
  have hbd2 : ∀ (k : Fin 3) (ξ : R3), ‖derivSymbol k ξ‖ ≤ 2 * Real.pi * ‖ξ‖ := by
    intro k ξ
    have hi : |(inner ℝ ξ (EuclideanSpace.single k (1 : ℝ)) : ℝ)| ≤ ‖ξ‖ := by
      simpa using abs_real_inner_le_norm ξ (EuclideanSpace.single k (1 : ℝ))
    have hnorm : ‖derivSymbol k ξ‖
        = 2 * Real.pi * |(inner ℝ ξ (EuclideanSpace.single k (1 : ℝ)) : ℝ)| := by
      simp only [derivSymbol, norm_mul, Complex.norm_ofNat, Complex.norm_real, Complex.norm_I,
        Real.norm_eq_abs, mul_one, abs_of_pos Real.pi_pos]
    rw [hnorm]
    nlinarith [Real.pi_pos, abs_nonneg (inner ℝ ξ (EuclideanSpace.single k (1 : ℝ)) : ℝ), hi]
  have hbd : ∀ (k : Fin 3) (ξ : R3), ‖derivSymbol k ξ‖ ≤ 2 * Real.pi * (1 + ‖ξ‖ ^ 2) := by
    intro k ξ
    calc ‖derivSymbol k ξ‖ ≤ 2 * Real.pi * ‖ξ‖ := hbd2 k ξ
      _ ≤ 2 * Real.pi * (1 + ‖ξ‖ ^ 2) := by nlinarith [Real.pi_pos, sq_nonneg (‖ξ‖ - 1)]
  -- `‖((1+‖ξ‖²:ℝ):ℂ)·𝓕ψ ξ‖ = (1+‖ξ‖²)·‖𝓕ψ ξ‖`
  have hwt : ∀ ξ : R3, ‖((1 + ‖ξ‖ ^ 2 : ℝ) : ℂ) * (fourierL2 ψ : R3 → ℂ) ξ‖
      = (1 + ‖ξ‖ ^ 2) * ‖(fourierL2 ψ : R3 → ℂ) ξ‖ := by
    intro ξ; rw [norm_mul, Complex.norm_real, Real.norm_eq_abs, abs_of_nonneg (by positivity)]
  -- generic L²-membership of a Fourier multiplier dominated by `C(1+‖ξ‖²)·𝓕ψ`
  have hmemMul : ∀ (k : Fin 3) (B : L2_R3),
      (B : R3 → ℂ) =ᵐ[volume] (fourierL2 ψ : R3 → ℂ) →
      MemLp (fun ξ => derivSymbol k ξ * (B : R3 → ℂ) ξ) 2 volume := by
    intro k B hB
    refine MemLp.of_le_mul (c := 2 * Real.pi) h
      ((by unfold derivSymbol; fun_prop : AEStronglyMeasurable (derivSymbol k) volume).mul
        (Lp.aestronglyMeasurable B)) ?_
    filter_upwards [hB] with ξ hξ
    rw [norm_mul, hξ, hwt, ← mul_assoc]
    exact mul_le_mul_of_nonneg_right (hbd k ξ) (norm_nonneg ((fourierL2 ψ : R3 → ℂ) ξ))
  -- first weak derivatives
  have hmem1 : ∀ k, MemLp (fun ξ => derivSymbol k ξ * (fourierL2 ψ : R3 → ℂ) ξ) 2 volume :=
    fun k => hmemMul k (fourierL2 ψ) (Filter.EventuallyEq.refl _ _)
  choose g hg_wd hg_four using fun k => weakDeriv_construct ψ k (hmem1 k)
  refine ⟨fun k => ⟨g k, hg_wd k⟩, fun i j => ?_⟩
  -- second derivative: differentiate `g i` once more in direction `j`
  have hmem2 : MemLp (fun ξ => derivSymbol j ξ * (fourierL2 (g i) : R3 → ℂ) ξ) 2 volume := by
    refine MemLp.of_le_mul (c := (2 * Real.pi) ^ 2) h
      ((by unfold derivSymbol; fun_prop : AEStronglyMeasurable (derivSymbol j) volume).mul
        (Lp.aestronglyMeasurable _)) ?_
    filter_upwards [hg_four i] with ξ hξ
    rw [norm_mul, hξ, norm_mul, hwt]
    have hprod : ‖derivSymbol j ξ‖ * ‖derivSymbol i ξ‖ ≤ (2 * Real.pi) ^ 2 * (1 + ‖ξ‖ ^ 2) := by
      calc ‖derivSymbol j ξ‖ * ‖derivSymbol i ξ‖
          ≤ (2 * Real.pi * ‖ξ‖) * (2 * Real.pi * ‖ξ‖) :=
            mul_le_mul (hbd2 j ξ) (hbd2 i ξ) (norm_nonneg _) (by positivity)
        _ = (2 * Real.pi) ^ 2 * ‖ξ‖ ^ 2 := by ring
        _ ≤ (2 * Real.pi) ^ 2 * (1 + ‖ξ‖ ^ 2) := by nlinarith [Real.pi_pos, sq_nonneg ‖ξ‖]
    calc ‖derivSymbol j ξ‖ * (‖derivSymbol i ξ‖ * ‖(fourierL2 ψ : R3 → ℂ) ξ‖)
        = (‖derivSymbol j ξ‖ * ‖derivSymbol i ξ‖) * ‖(fourierL2 ψ : R3 → ℂ) ξ‖ := by ring
      _ ≤ ((2 * Real.pi) ^ 2 * (1 + ‖ξ‖ ^ 2)) * ‖(fourierL2 ψ : R3 → ℂ) ξ‖ :=
          mul_le_mul_of_nonneg_right hprod (norm_nonneg _)
      _ = (2 * Real.pi) ^ 2 * ((1 + ‖ξ‖ ^ 2) * ‖(fourierL2 ψ : R3 → ℂ) ξ‖) := by ring
  obtain ⟨gij, hgij_wd, _⟩ := weakDeriv_construct (g i) j hmem2
  exact ⟨gij, g i, hg_wd i, hgij_wd⟩

/-! ## Mild glue lemmas -/

/-- Pointwise multiplication by an essentially-bounded measurable symbol keeps an
    L² function in L².  `eLpNorm` domination via `MemLp.of_le_mul`. -/
lemma memLp_two_boundedMul {m : R3 → ℂ} (hm : AEStronglyMeasurable m volume)
    {C : ℝ} (hC : ∀ᵐ ξ ∂volume, ‖m ξ‖ ≤ C) (g : L2_R3) :
    MemLp (fun ξ => m ξ * (g : R3 → ℂ) ξ) 2 volume := by
  refine MemLp.of_le_mul (c := C) (Lp.memLp g) (hm.mul (Lp.aestronglyMeasurable g)) ?_
  filter_upwards [hC] with ξ hξ
  rw [norm_mul]
  exact mul_le_mul_of_nonneg_right hξ (norm_nonneg _)

/-- Two L² elements with a.e.-equal representatives are equal. -/
lemma L2_ext {a b : L2_R3} (h : (a : R3 → ℂ) =ᵐ[volume] (b : R3 → ℂ)) : a = b :=
  Lp.ext h

/-! ## The resolvent symbol and its bound -/

/-- The resolvent multiplier `1/((2π)²‖ξ‖² + ε)` for `ε ∈ {i, −i}`. -/
def resolventSymbol (ε : ℂ) (ξ : R3) : ℂ := ((laplacianSymbol ξ : ℂ) + ε)⁻¹

lemma laplacianSymbol_add_ne_zero {ε : ℂ} (hε : ε.im ≠ 0) (ξ : R3) :
    (laplacianSymbol ξ : ℂ) + ε ≠ 0 := by
  intro h
  apply hε
  have him : ((laplacianSymbol ξ : ℂ) + ε).im = 0 := by rw [h]; rfl
  simpa using him

lemma resolventSymbol_mul_cancel {ε : ℂ} (hε : ε.im ≠ 0) (ξ : R3) :
    ((laplacianSymbol ξ : ℂ) + ε) * resolventSymbol ε ξ = 1 :=
  mul_inv_cancel₀ (laplacianSymbol_add_ne_zero hε ξ)

/-- The imaginary part alone forces `|(2π)²‖ξ‖² + ε| ≥ |ε.im|`. -/
lemma abs_im_le_norm_laplacianSymbol_add (ε : ℂ) (ξ : R3) :
    |ε.im| ≤ ‖(laplacianSymbol ξ : ℂ) + ε‖ := by
  have him : ((laplacianSymbol ξ : ℂ) + ε).im = ε.im := by simp
  rw [← him]; exact abs_im_le_norm _

/-- `|1/((2π)²‖ξ‖² + ε)| ≤ 1/|ε.im|`. -/
lemma norm_resolventSymbol_le {ε : ℂ} (hε : ε.im ≠ 0) (ξ : R3) :
    ‖resolventSymbol ε ξ‖ ≤ 1 / |ε.im| := by
  rw [resolventSymbol, norm_inv, one_div]
  exact inv_anti₀ (abs_pos.mpr hε) (abs_im_le_norm_laplacianSymbol_add ε ξ)

/-- The H²-weighted resolvent symbol `(1+‖ξ‖²)/((2π)²‖ξ‖² + ε)` is bounded — this is
    what lands the solution in H² rather than just L².  Witness
    `C = 1 + (1+|ε.re|)/|ε.im|`: split `(1+‖ξ‖²) ≤ 1 + (2π)²‖ξ‖²` (as `(2π)² ≥ 1`) and
    bound `(2π)²‖ξ‖² ≤ ‖z‖ + |ε.re|` via `|Re z| ≤ ‖z‖`, `|ε.im| ≤ ‖z‖`. -/
lemma exists_bound_weighted_resolventSymbol {ε : ℂ} (hε : ε.im ≠ 0) :
    ∃ C : ℝ, ∀ ξ : R3, ‖((1 + ‖ξ‖ ^ 2 : ℝ) : ℂ) * resolventSymbol ε ξ‖ ≤ C := by
  refine ⟨1 + (1 + |ε.re|) / |ε.im|, fun ξ => ?_⟩
  set s : ℝ := laplacianSymbol ξ with hs_def
  set z : ℂ := (s : ℂ) + ε with hz_def
  have hd : 0 < |ε.im| := abs_pos.mpr hε
  have him : |ε.im| ≤ ‖z‖ := abs_im_le_norm_laplacianSymbol_add ε ξ
  have hzpos : 0 < ‖z‖ := lt_of_lt_of_le hd him
  -- the LHS norm equals (1+‖ξ‖²) / ‖z‖
  have lhs_eq : ‖((1 + ‖ξ‖ ^ 2 : ℝ) : ℂ) * resolventSymbol ε ξ‖
      = (1 + ‖ξ‖ ^ 2) * ‖z‖⁻¹ := by
    rw [norm_mul, resolventSymbol, ← hs_def, ← hz_def, norm_inv, Complex.norm_real,
      Real.norm_eq_abs, abs_of_nonneg (by positivity)]
  rw [lhs_eq, mul_inv_le_iff₀ hzpos]
  -- goal: 1 + ‖ξ‖² ≤ (1 + (1+|ε.re|)/|ε.im|) * ‖z‖
  -- key facts
  have hpi : (1 : ℝ) ≤ (2 * Real.pi) ^ 2 := by nlinarith [Real.pi_gt_three]
  have hst : ‖ξ‖ ^ 2 ≤ s := by
    rw [hs_def, laplacianSymbol]
    nlinarith [mul_nonneg (by linarith : (0:ℝ) ≤ (2 * Real.pi) ^ 2 - 1) (sq_nonneg ‖ξ‖)]
  have hzre : z.re = s + ε.re := by rw [hz_def]; simp
  have hsb : s ≤ ‖z‖ + |ε.re| := by
    have h1 : s + ε.re ≤ ‖z‖ := hzre ▸ (le_abs_self z.re).trans (abs_re_le_norm z)
    nlinarith [neg_le_abs ε.re]
  rw [show (1 + (1 + |ε.re|) / |ε.im|) = (|ε.im| + 1 + |ε.re|) / |ε.im| by field_simp; ring,
    div_mul_eq_mul_div, le_div_iff₀ hd]
  nlinarith [mul_le_mul_of_nonneg_left (hst.trans hsb) hd.le,
    mul_le_mul_of_nonneg_right him (abs_nonneg ε.re), him, hd, sq_nonneg ‖ξ‖, abs_nonneg ε.re]

/-- Measurability of `ξ ↦ resolventSymbol ε ξ`.  (`fun_prop` can't do the complex
    inverse; route through `Measurable.inv`, valid since `ℂ` has `ContinuousInv₀`.) -/
lemma aestronglyMeasurable_resolventSymbol (ε : ℂ) :
    AEStronglyMeasurable (resolventSymbol ε) volume := by
  apply Measurable.aestronglyMeasurable
  unfold resolventSymbol laplacianSymbol
  apply Measurable.inv
  fun_prop

/-- Measurability of the weighted symbol. -/
lemma aestronglyMeasurable_weighted_resolventSymbol (ε : ℂ) :
    AEStronglyMeasurable
      (fun ξ => ((1 + ‖ξ‖ ^ 2 : ℝ) : ℂ) * resolventSymbol ε ξ) volume :=
  (by fun_prop : AEStronglyMeasurable (fun ξ : R3 => ((1 + ‖ξ‖ ^ 2 : ℝ) : ℂ)) volume).mul
    (aestronglyMeasurable_resolventSymbol ε)

/-! ## The general surjectivity lemma

Assembles the obligations: for `ε` with `ε.im ≠ 0`, `(−Δ + ε)` is onto. -/

theorem laplacian_range_general (ε : ℂ) (hε : ε.im ≠ 0) (φ : L2_R3) :
    ∃ ψ : laplacianPMap.domain, laplacianPMap ψ + ε • (ψ : L2_R3) = φ := by
  -- candidate Fourier transform of the solution: ψ̂ = φ̂ / ((2π)²‖ξ‖² + ε)
  set ĝ : R3 → ℂ := fun ξ => resolventSymbol ε ξ * (fourierL2 φ : R3 → ℂ) ξ with hĝ
  -- ψ̂ ∈ L² (bounded multiplier, `|resolventSymbol| ≤ 1/|ε.im|`)
  have hĝ_mem : MemLp ĝ 2 volume :=
    memLp_two_boundedMul (aestronglyMeasurable_resolventSymbol ε)
      (Filter.Eventually.of_forall fun ξ => norm_resolventSymbol_le hε ξ) (fourierL2 φ)
  -- the solution ψ := 𝓕⁻¹ ψ̂
  set ψ : L2_R3 := fourierL2.symm (hĝ_mem.toLp ĝ) with hψ_def
  have hFψ : fourierL2 ψ = hĝ_mem.toLp ĝ := by
    rw [hψ_def, LinearIsometryEquiv.apply_symm_apply]
  have hFψ_fun : (fourierL2 ψ : R3 → ℂ) =ᵐ[volume] ĝ := by
    rw [hFψ]; exact hĝ_mem.coeFn_toLp
  -- ψ ∈ H²: `(1+‖ξ‖²)·𝓕ψ` is L² because `(1+‖ξ‖²)·resolventSymbol` is bounded
  have hψ_mem : MemSobolevH2 ψ := by
    apply memSobolevH2_of_fourier_decay
    obtain ⟨C, hCbd⟩ := exists_bound_weighted_resolventSymbol hε
    have hbase : MemLp
        (fun ξ => (((1 + ‖ξ‖ ^ 2 : ℝ) : ℂ) * resolventSymbol ε ξ) * (fourierL2 φ : R3 → ℂ) ξ)
        2 volume :=
      memLp_two_boundedMul (aestronglyMeasurable_weighted_resolventSymbol ε)
        (Filter.Eventually.of_forall hCbd) (fourierL2 φ)
    refine hbase.ae_eq ?_
    filter_upwards [hFψ_fun] with ξ hξ
    simp only [hξ, hĝ]; ring
  -- the equation, checked on the Fourier side then transported back
  refine ⟨⟨ψ, hψ_mem⟩, ?_⟩
  rw [laplacianPMap_apply ψ hψ_mem]
  -- suffices: 𝓕(−Δψ + ε•ψ) = 𝓕 φ, by injectivity of 𝓕
  apply fourierL2.injective
  rw [map_add, map_smul]
  apply L2_ext
  -- a.e.:  (2π)²‖ξ‖²·𝓕ψ + ε·𝓕ψ = ((2π)²‖ξ‖² + ε)·resolventSymbol·𝓕φ = 𝓕φ
  have hlap := fourier_weakLaplacian ψ hψ_mem
  filter_upwards [Lp.coeFn_add (fourierL2 (weakLaplacian ψ hψ_mem)) (ε • fourierL2 ψ),
    Lp.coeFn_smul ε (fourierL2 ψ), hlap, hFψ_fun] with ξ hadd hsmul hlapξ hξ
  rw [hadd, Pi.add_apply, hsmul, Pi.smul_apply, hlapξ, hξ, smul_eq_mul, hĝ]
  -- goal:  laplacianSymbol ξ * (resolventSymbol ε ξ * 𝓕φ ξ)
  --        + ε * (resolventSymbol ε ξ * 𝓕φ ξ)  =  𝓕φ ξ
  have hcancel := resolventSymbol_mul_cancel hε ξ
  -- (s + ε) * resolventSymbol = 1, so LHS = 𝓕φ ξ
  have : (laplacianSymbol ξ : ℂ) * (resolventSymbol ε ξ * (fourierL2 φ : R3 → ℂ) ξ)
       + ε * (resolventSymbol ε ξ * (fourierL2 φ : R3 → ℂ) ξ)
       = ((laplacianSymbol ξ : ℂ) + ε) * resolventSymbol ε ξ * (fourierL2 φ : R3 → ℂ) ξ := by
    ring
  rw [this, hcancel, one_mul]

/-! ## The two drop-in targets

Exact statements of the sorried lemmas in `Laplacian.lean`; once
`laplacian_range_general` is real, replace those sorries with these. -/

/-- Drop-in for `laplacian_range_add_I`. -/
theorem laplacian_range_add_I :
    ∀ φ : L2_R3, ∃ ψ : laplacianPMap.domain,
      laplacianPMap ψ + I • (ψ : L2_R3) = φ :=
  fun φ => laplacian_range_general I (by simp) φ

/-- Drop-in for `laplacian_range_sub_I`. -/
theorem laplacian_range_sub_I :
    ∀ φ : L2_R3, ∃ ψ : laplacianPMap.domain,
      laplacianPMap ψ - I • (ψ : L2_R3) = φ := by
  intro φ
  obtain ⟨ψ, hψ⟩ := laplacian_range_general (-I) (by simp) φ
  exact ⟨ψ, by rw [sub_eq_add_neg, ← neg_smul]; exact hψ⟩

/-- **Self-adjointness of −Δ on H²(ℝ³).**

    Assembled from symmetry + density + the two surjectivity lemmas via the
    library's von Neumann criterion.  No sorry in this proof itself. -/
theorem laplacian_isSelfAdjoint : IsSelfAdjoint laplacianPMap :=
  isSelfAdjoint_of_surjective_addSub laplacianPMap
    laplacian_isFormalAdjoint laplacian_domain_dense
    laplacian_range_add_I laplacian_range_sub_I

/-- −Δ packaged as an `UnboundedObservable` (kinetic energy). -/
def laplacianObservable : UnboundedObservable L2_R3 where
  toLinearPMap := laplacianPMap
  selfAdjoint := laplacian_isSelfAdjoint

/-! ## The free-particle unitary group

Stone's theorem (`genToGroup`) turns the self-adjoint `−Δ` into the free-particle
evolution `e^{it(−Δ)}`; the generator-extraction round-trip gives back `−Δ`.
-/

/-- The free-particle unitary group generated by `−Δ`, `U(t) = e^{it(−Δ)}`. -/
def freeParticleGroup : OneParameterUnitaryGroup (H := L2_R3) :=
  genToGroup laplacian_isSelfAdjoint

/-- The generator of the free-particle group is `−Δ` (Stone's theorem). -/
theorem generator_freeParticleGroup :
    generator freeParticleGroup = laplacianPMap :=
  generator_genToGroup laplacian_isSelfAdjoint

/-- The domain of the generator of the free evolution is `H²(ℝ³)`. -/
theorem freeParticleGroup_generator_domain :
    (generator freeParticleGroup).domain = SobolevH2 := by
  rw [generator_freeParticleGroup]; rfl

/-! ## Spectral properties of `−Δ` -/

/-- Any eigenvalue of `−Δ` is nonnegative: from `laplacian_nonneg`,
`λ‖ψ‖² = re⟪−Δψ, ψ⟫ = ‖∇ψ‖² ≥ 0`, and `ψ ≠ 0`. -/
theorem laplacian_spectrum_nonneg
    (ψ : L2_R3) (hψ : MemSobolevH2 ψ) (lam : ℝ)
    (hψ_ne : ψ ≠ 0)
    (heig : weakLaplacian ψ hψ = (lam : ℂ) • ψ) :
    0 ≤ lam := by
  have h0 : 0 ≤ (inner (𝕜 := ℂ) (weakLaplacian ψ hψ) ψ).re :=
    laplacian_nonneg ψ hψ
  erw [heig, inner_smul_left, Complex.conj_ofReal,
    inner_self_eq_norm_sq_to_K (𝕜 := ℂ), ← Complex.ofReal_pow,
    ← Complex.ofReal_mul, Complex.ofReal_re] at h0
  -- h0 : 0 ≤ lam * ‖ψ‖ ^ 2
  have hnorm : 0 < ‖ψ‖ ^ 2 := pow_pos (norm_pos_iff.mpr hψ_ne) 2
  by_contra hlam
  exact absurd h0 (not_le.mpr (mul_neg_of_neg_of_pos (not_le.mp hlam) hnorm))

/-- `−Δ` on `L²(ℝ³)` has no eigenvalues (purely continuous spectrum).

If `−Δψ = λψ` then in Fourier space `((2π)²‖ξ‖² − λ)·𝓕ψ = 0` a.e.
(`fourier_weakLaplacian`).  The symbol `(2π)²‖ξ‖²` equals `λ` only on the sphere
`‖ξ‖ = √λ/(2π)`, a Lebesgue-null set in `ℝ³` (`Measure.addHaar_sphere`); hence
`𝓕ψ = 0` a.e. and, since `fourierL2` is a linear isometry (Plancherel), `ψ = 0`. -/
theorem laplacian_no_eigenvalues
    (lam : ℝ) (ψ : L2_R3) (hψ : MemSobolevH2 ψ)
    (heig : weakLaplacian ψ hψ = (lam : ℂ) • ψ) :
    ψ = 0 := by
  -- The frequencies where the symbol `(2π)²‖ξ‖²` hits `λ` form a sphere — null.
  have hN : volume {ξ : R3 | laplacianSymbol ξ = lam} = 0 := by
    refine measure_mono_null ?_
      (Measure.addHaar_sphere (volume : Measure R3) 0 (Real.sqrt lam / (2 * Real.pi)))
    intro ξ hξ
    simp only [Set.mem_setOf_eq] at hξ
    rw [Metric.mem_sphere, dist_zero_right,
      eq_div_iff (by positivity : (2 * Real.pi : ℝ) ≠ 0)]
    have hlam : lam = (2 * Real.pi) ^ 2 * ‖ξ‖ ^ 2 := hξ.symm
    rw [hlam, Real.sqrt_mul (sq_nonneg _),
      Real.sqrt_sq (by positivity : (0 : ℝ) ≤ 2 * Real.pi), Real.sqrt_sq (norm_nonneg ξ)]
    ring
  -- Fourier-transform the eigen-equation: `fourierL2 (−Δψ) = λ · fourierL2 ψ`.
  have hsmul : fourierL2 (weakLaplacian ψ hψ) = (lam : ℂ) • fourierL2 ψ := by
    rw [heig]; exact map_smul fourierL2 (lam : ℂ) ψ
  -- a.e. pointwise: `(2π)²‖ξ‖² · 𝓕ψ ξ = λ · 𝓕ψ ξ`.
  have hae : ∀ᵐ ξ : R3, (laplacianSymbol ξ : ℂ) * (fourierL2 ψ : R3 → ℂ) ξ
      = (lam : ℂ) * (fourierL2 ψ : R3 → ℂ) ξ := by
    have hcoe : (fourierL2 (weakLaplacian ψ hψ) : R3 → ℂ)
        =ᵐ[volume] fun ξ => (lam : ℂ) * (fourierL2 ψ : R3 → ℂ) ξ := by
      rw [hsmul]
      filter_upwards [Lp.coeFn_smul (lam : ℂ) (fourierL2 ψ)] with ξ hξ
      rw [hξ, Pi.smul_apply, smul_eq_mul]
    filter_upwards [fourier_weakLaplacian ψ hψ, hcoe] with ξ h1 h2
    rw [← h1, h2]
  -- Off the null sphere `𝓕ψ ξ = 0`; hence `𝓕ψ = 0` a.e.
  have hzero_ae : (fourierL2 ψ : R3 → ℂ) =ᵐ[volume] 0 := by
    have hne : ∀ᵐ ξ : R3, laplacianSymbol ξ ≠ lam := by
      rw [ae_iff]; simpa using hN
    filter_upwards [hae, hne] with ξ h1 h2
    rw [Pi.zero_apply]
    have hz : ((laplacianSymbol ξ : ℂ) - lam) * (fourierL2 ψ : R3 → ℂ) ξ = 0 := by
      rw [sub_mul, h1, sub_self]
    rcases mul_eq_zero.mp hz with h | h
    · exact absurd (Complex.ofReal_inj.mp (sub_eq_zero.mp h)) h2
    · exact h
  -- Plancherel: `fourierL2` is injective, so `ψ = 0`.
  have hfourier_zero : fourierL2 ψ = 0 :=
    Lp.ext (hzero_ae.trans (Lp.coeFn_zero ℂ 2 (volume : Measure R3)).symm)
  exact fourierL2.injective (by rw [hfourier_zero, map_zero])

/-- Resolvent bound: `‖(−Δ − z)⁻¹‖ ≤ 1/|Im z|`. Purely abstract — from the
resolvent estimate for self-adjoint operators, no Fourier analysis needed. -/
theorem laplacian_resolvent_bound (z : ℂ) (hz : z.im ≠ 0) :
    ‖selfAdjointResolvent laplacian_isSelfAdjoint z hz‖ ≤ 1 / |z.im| := by
  rw [selfAdjointResolvent_eq_genToGroup]
  exact resolvent_bound _ _ _ z hz

/-! ## The free Green's function

For explicit spectral computations we record the free Green's function
`G_z(x) = e^{−√(−z)|x|} / (4π|x|)`, with the principal branch of the square root
(so `Re √(−z) > 0` whenever `Im z ≠ 0`). Tying it to `selfAdjointResolvent`, and
the exponential decay, both require the radial Fourier computation, so the two
identities below are left open. -/

/-- The free Green's function `G_z(x) = e^{−√(−z)|x|}/(4π|x|)`, principal branch of
the square root; `0` at the origin. -/
def freeGreensFunction (z : ℂ) : R3 → ℂ := fun x =>
  if ‖x‖ = 0 then 0
  else Complex.exp (-((-z) ^ ((1 : ℂ) / 2)) * (‖x‖ : ℂ)) /
    ((4 * Real.pi * ‖x‖ : ℝ) : ℂ)

/-- The Green's function is the integral kernel of the free resolvent.

Verify `𝓕[G_z](ξ) = 1/(|ξ|² − z)` by the radial contour computation, then
Plancherel turns multiplication by `1/(|ξ|² − z)` into convolution with `G_z`.
Needs the Fourier characterization of `−Δ`; left open. -/
theorem freeGreensFunction_is_resolvent_kernel
    (z : ℂ) (hz : z.im ≠ 0) (f : L2_R3) :
    ∀ᵐ x : R3,
      (selfAdjointResolvent laplacian_isSelfAdjoint z hz f : R3 → ℂ) x =
      ∫ y, freeGreensFunction z (x - y) * (f : R3 → ℂ) y :=
  sorry

/-- The Green's function decays exponentially with rate `Re √(−z) > 0`.

Direct from the explicit formula: the witness is `c = Re((−z)^{1/2}) > 0`, since
`−z ∉ [0, ∞)` when `Im z ≠ 0` and the principal branch maps `ℂ ∖ [0, ∞)` into the
open right half-plane. Left open (elementary but `cpow`-fiddly). -/
theorem freeGreensFunction_decay (z : ℂ) (hz : z.im ≠ 0) :
    ∃ c : ℝ, 0 < c ∧ ∀ x : R3, x ≠ 0 →
      ‖freeGreensFunction z x‖ ≤
        Real.exp (-c * ‖x‖) / (4 * Real.pi * ‖x‖) := by
  have hz' : -z ≠ 0 := neg_ne_zero.mpr (by rintro rfl; simp at hz)
  set w : ℂ := (-z) ^ ((1 : ℂ) / 2) with hw
  refine ⟨w.re, ?_, ?_⟩
  · -- `Re((−z)^{1/2}) = ‖−z‖^{1/2}·cos(arg(−z)/2) > 0`, since `arg(−z) ∈ (−π, π)`.
    have harg_gt : -Real.pi < Complex.arg (-z) := Complex.neg_pi_lt_arg (-z)
    have harg_lt : Complex.arg (-z) < Real.pi := by
      rcases (Complex.arg_le_pi (-z)).lt_or_eq with h | h
      · exact h
      · exact absurd (Complex.arg_eq_pi_iff.mp h).2 (by simpa using hz)
    rw [hw, Complex.cpow_def_of_ne_zero hz', Complex.exp_re]
    refine mul_pos (Real.exp_pos _) ?_
    have h12 : ((1 : ℂ) / 2) = ((1 / 2 : ℝ) : ℂ) := by push_cast; ring
    have him : (Complex.log (-z) * ((1 : ℂ) / 2)).im = Complex.arg (-z) / 2 := by
      rw [h12, Complex.mul_im, Complex.ofReal_im, Complex.ofReal_re, Complex.log_im]; ring
    rw [him]
    exact Real.cos_pos_of_mem_Ioo ⟨by linarith, by linarith⟩
  · intro x hx
    have hxn : ‖x‖ ≠ 0 := norm_ne_zero_iff.mpr hx
    have hxpos : 0 < ‖x‖ := norm_pos_iff.mpr hx
    have hdenom_pos : 0 < 4 * Real.pi * ‖x‖ :=
      mul_pos (mul_pos (by norm_num) Real.pi_pos) hxpos
    refine le_of_eq ?_
    have hval : freeGreensFunction z x
        = Complex.exp (-w * (‖x‖ : ℂ)) / ((4 * Real.pi * ‖x‖ : ℝ) : ℂ) := by
      rw [freeGreensFunction, if_neg hxn, ← hw]
    have hre : (-w * (‖x‖ : ℂ)).re = -w.re * ‖x‖ := by
      simp [Complex.mul_re, Complex.ofReal_re, Complex.ofReal_im]
    rw [hval, norm_div, Complex.norm_exp, Complex.norm_real, Real.norm_eq_abs,
      abs_of_pos hdenom_pos, hre]

/-! ## Interface summary

### For `CoulombBound.lean`:
- `laplacianPMap` is the unperturbed `A`; `laplacianPMap.domain = SobolevH2`
  holds by `rfl`, so **no domain transport is needed**: a linear map
  `SobolevH2 →ₗ[ℂ] L2_R3` *is* a `laplacianPMap.domain →ₗ[ℂ] L2_R3`.
- `laplacianPMap_apply` bridges `laplacianPMap ⟨ψ, hψ⟩ ↔ weakLaplacian ψ hψ`
  (also `rfl`), so Hardy estimates in terms of `weakLaplacian` transfer
  verbatim to estimates in terms of `‖laplacianPMap ψ‖`.

### For `HydrogenHamiltonian.lean`:
- `kato_rellich_bound_zero laplacian_isSelfAdjoint V hV_sym hV₀ lam`
  produces `IsSelfAdjoint (perturbedOp laplacianPMap ((lam : ℂ) • V))`,
  i.e. self-adjointness of −Δ − Z/r on H²(ℝ³).
- `genToGroup` then yields the hydrogen evolution, and
  `spectralPVM`/`spectralTheorem` its spectral measure.

### Already available once `laplacian_isSelfAdjoint` is discharged:
- `selfAdjointResolvent laplacian_isSelfAdjoint` with norm ≤ 1/|Im z|;
- `spectralPVM laplacian_isSelfAdjoint` and `spectralPVM_resolvent_formula`;
- the unitary group `freeParticleGroup` with Stone's theorem.
-/

end Spectra.QuantumMechanics.Hydrogen
