/-
Copyright (c) 2026 Spectra Formalization Project. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Adam Bornemann
-/
import Spectra.QuantumMechanics.OneParameterUnitaryGroup.Basic
import Spectra.QuantumMechanics.Observable.Basic
import Spectra.QuantumMechanics.Stone.Basic
import Spectra.SobolevSpaces.DensityResults
import Spectra.SpectralTheory.ResolventForm
import Spectra.Resolvent.Range
/-!
# The Laplacian as a Self-Adjoint Operator

This file packages the negative Laplacian −Δ on H²(ℝ³) as an unbounded
operator `laplacianPMap : L2_R3 →ₗ.[ℂ] L2_R3` and establishes the spectral
pipeline around it.

## Architecture

This file was rewritten for the refactored Stone library.  The old design
("`Generator U` as a structure with `domain`/`op`/`symmetric` fields, built
*from* a unitary group") is inverted: the fundamental object is now the
partial linear map, self-adjointness is Mathlib's star-based `IsSelfAdjoint`
on `LinearPMap`, and the unitary group is *derived* by Stone's theorem:

```
  SobolevSpaces.lean                       this file
  ┌───────────────────┐                    ┌──────────────────────────────┐
  │ SobolevH2         │── domain ────────→ │ laplacianPMap : L2 →ₗ.[ℂ] L2 │
  │ laplacianLinearMap│── toFun ─────────→ │                              │
  │ laplacian_symm    │── IsFormalAdjoint→ │ laplacian_isSelfAdjoint      │
  │ sobolevH2_dense   │── Dense ─────────→ │   (von Neumann criterion)    │
  └───────────────────┘                    └──────────────┬───────────────┘
                                                          │ genToGroup
                                           ┌──────────────▼───────────────┐
                                           │ freeParticleGroup            │
                                           │ selfAdjointResolvent         │
                                           │ spectralPVM / spectralTheorem│
                                           └──────────────────────────────┘
```

Once `laplacian_isSelfAdjoint` is in place, the library gives for free:
* `freeParticleGroup := genToGroup laplacian_isSelfAdjoint` with
  `generator freeParticleGroup = laplacianPMap` (Stone);
* `selfAdjointResolvent laplacian_isSelfAdjoint z hz` with the norm bound
  `≤ 1/|Im z|` (proved below, *not* sorried);
* `spectralPVM laplacian_isSelfAdjoint` and the full spectral theorem.

## Remaining analytic content

Exactly two sorries carry real mathematics: surjectivity of (−Δ ± i) on H²
(`laplacian_range_add_I`, `laplacian_range_sub_I`).  Everything that was a
structural obligation in the old design (`generator_formula`,
`domain_invariant`, `domain_maximal`) is now a theorem of the Stone library.

**Route via Fourier transform:** under Plancherel, −Δ is multiplication by
|ξ|².  The equation (−Δ ± i)ψ = φ becomes (|ξ|² ± i)ψ̂ = φ̂, solved by
ψ̂ = φ̂/(|ξ|² ± i); the estimates |1/(|ξ|² ± i)| ≤ 1 and
(1+|ξ|²)²/||ξ|² ± i|² ≤ C give ψ ∈ H².  Interface: `sobolevH2_fourier_char`.

**Route via Lax–Milgram:** the form a(u,v) = ⟨∇u, ∇v⟩ ∓ i⟨u, v⟩ is coercive
on H¹ (|a(u,u)| ≥ ‖u‖²); Riesz representation produces u ∈ H¹ with
a(u,·) = ⟨φ,·⟩, and elliptic regularity lifts u to H².

## Main definitions

* `laplacianPMap` — −Δ with domain H²(ℝ³), as a `LinearPMap`.
* `laplacianObservable` — the same, packaged as `UnboundedObservable`.
* `freeParticleGroup` — the unitary group generated by −Δ via Stone.
  NB: in this library's convention (`schrodingerEquation`:
  d/dt U(t)ψ = i·A·U(t)ψ), the group generated by A = −Δ is
  U(t) = exp(it(−Δ)) = exp(−itΔ).
* `freeGreensFunction` — the explicit kernel e^{−√(−z)|x|}/(4π|x|).

## Main statements

* `laplacian_isSelfAdjoint` — −Δ is self-adjoint on H²(ℝ³)
  (assembled from the two surjectivity sorries; no other gaps).
* `laplacian_spectrum_nonneg` — eigenvalues of −Δ are ≥ 0 (**proved**).
* `laplacian_no_eigenvalues` — −Δ on ℝ³ has no eigenvalues (Fourier; sorry).
* `laplacian_resolvent_bound` — ‖(−Δ − z)⁻¹‖ ≤ 1/|Im z| (**proved**, from
  `Spectra.Resolvent.resolvent_bound`).

## References

* [Reed, Simon, *Methods of Modern Mathematical Physics II*][reed1975], Thm X.25.
* [Hall, *Quantum Theory for Mathematicians*][hall2013], §9.6.
* [Lieb, Loss, *Analysis*][lieb2001], Chapter 7.
-/

noncomputable section

open MeasureTheory Complex Filter InnerProductSpace
open Spectra.Sobolev
open Spectra.QuantumMechanics
open Spectra.QuantumMechanics.OneParameterUnitaryGroup
open Spectra.QuantumMechanics.Observable
open Spectra.QuantumMechanics.Stoneslemma
open Spectra.QuantumMechanics.StonesTheorem
open Spectra.Resolvent
open Spectra.QuantumMechanics.SpectralTheory
open scoped Topology NNReal ENNReal

namespace Spectra.QuantumMechanics.Hydrogen

/-! ## −Δ as a partial linear map -/

/-- **The negative Laplacian as an unbounded operator on L²(ℝ³).**

    Domain H²(ℝ³), action `laplacianLinearMap` (= the weak −Δ from
    `SobolevSpaces.lean`).  Both fields are supplied by `SobolevSpaces.lean`,
    so this definition is sorry-free, and the domain/action lemmas below are
    `rfl`. -/
def laplacianPMap : L2_R3 →ₗ.[ℂ] L2_R3 where
  domain := SobolevH2
  toFun := laplacianLinearMap

@[simp] theorem laplacianPMap_domain : laplacianPMap.domain = SobolevH2 :=
  rfl

/-- The action of `laplacianPMap` is the weak Laplacian.  Definitional. -/
theorem laplacianPMap_apply (ψ : L2_R3) (hψ : MemSobolevH2 ψ) :
    laplacianPMap ⟨ψ, hψ⟩ = weakLaplacian ψ hψ :=
  rfl

/-- Symmetry: ⟪−Δψ, φ⟫ = ⟪ψ, −Δφ⟫ on H².  Direct repackaging of
    `laplacian_symmetric`. -/
theorem laplacian_isFormalAdjoint :
    laplacianPMap.IsFormalAdjoint laplacianPMap :=
  fun ψ φ => laplacian_symmetric ψ.1 φ.1 ψ.2 φ.2

/-- H² is dense in L².  Direct repackaging of `sobolevH2_dense`. -/
theorem laplacian_domain_dense :
    Dense (laplacianPMap.domain : Set L2_R3) :=
  sobolevH2_dense

/-! ## Self-adjointness: the von Neumann criterion

The two lemmas below are the *only* analytic sorries of this file.  They
assert surjectivity of (−Δ ± i) : H² → L², i.e. vanishing deficiency
indices.  Discharge via the Fourier route (`sobolevH2_fourier_char`) or
Lax–Milgram, as described in the module docstring.
-/

/-- **Surjectivity of −Δ + i.**

    **Discharge route (Fourier):** ψ̂ := φ̂/(|ξ|² + i) is well defined
    (|ξ|² + i ≠ 0), lies in L² (|1/(|ξ|² + i)| ≤ 1), and lies in H²
    ((1+|ξ|²)²|ψ̂|² ≤ C|φ̂|²); inverting Plancherel solves the equation. -/
theorem laplacian_range_add_I :
    ∀ φ : L2_R3, ∃ ψ : laplacianPMap.domain,
      laplacianPMap ψ + I • (ψ : L2_R3) = φ :=
  sorry

/-- **Surjectivity of −Δ − i.**  Mirror image of `laplacian_range_add_I`. -/
theorem laplacian_range_sub_I :
    ∀ φ : L2_R3, ∃ ψ : laplacianPMap.domain,
      laplacianPMap ψ - I • (ψ : L2_R3) = φ :=
  sorry

/-- **Self-adjointness of −Δ on H²(ℝ³).**

    Assembled from symmetry + density + the two surjectivity lemmas via the
    library's von Neumann criterion.  No sorry in this proof itself. -/
theorem laplacian_isSelfAdjoint : IsSelfAdjoint laplacianPMap :=
  isSelfAdjoint_of_surjective_addSub laplacianPMap
    laplacian_isFormalAdjoint laplacian_domain_dense
    laplacian_range_add_I laplacian_range_sub_I

/-- −Δ packaged as an `UnboundedObservable` (kinetic energy). -/
def laplacianObservable : UnboundedObservable L2_R3 where
  toLinearPMap := laplacianPMap
  selfAdjoint := laplacian_isSelfAdjoint

/-! ## The free-particle unitary group

Stone's theorem (`genToGroup`) turns the self-adjoint `−Δ` into the free-particle
evolution `e^{it(−Δ)}`; the generator-extraction round-trip gives back `−Δ`.
-/

/-- The free-particle unitary group generated by `−Δ`, `U(t) = e^{it(−Δ)}`. -/
def freeParticleGroup : OneParameterUnitaryGroup (H := L2_R3) :=
  genToGroup laplacian_isSelfAdjoint

/-- The generator of the free-particle group is `−Δ` (Stone's theorem). -/
theorem generator_freeParticleGroup :
    generator freeParticleGroup = laplacianPMap :=
  generator_genToGroup laplacian_isSelfAdjoint

/-- The domain of the generator of the free evolution is `H²(ℝ³)`. -/
theorem freeParticleGroup_generator_domain :
    (generator freeParticleGroup).domain = SobolevH2 := by
  rw [generator_freeParticleGroup]; rfl

/-! ## Spectral properties of `−Δ` -/

/-- Any eigenvalue of `−Δ` is nonnegative: from `laplacian_nonneg`,
`λ‖ψ‖² = re⟪−Δψ, ψ⟫ = ‖∇ψ‖² ≥ 0`, and `ψ ≠ 0`. -/
theorem laplacian_spectrum_nonneg
    (ψ : L2_R3) (hψ : MemSobolevH2 ψ) (lam : ℝ)
    (hψ_ne : ψ ≠ 0)
    (heig : weakLaplacian ψ hψ = (lam : ℂ) • ψ) :
    0 ≤ lam := by
  have h0 : 0 ≤ (inner (𝕜 := ℂ) (weakLaplacian ψ hψ) ψ).re :=
    laplacian_nonneg ψ hψ
  erw [heig, inner_smul_left, Complex.conj_ofReal,
    inner_self_eq_norm_sq_to_K (𝕜 := ℂ), ← Complex.ofReal_pow,
    ← Complex.ofReal_mul, Complex.ofReal_re] at h0
  -- h0 : 0 ≤ lam * ‖ψ‖ ^ 2
  have hnorm : 0 < ‖ψ‖ ^ 2 := pow_pos (norm_pos_iff.mpr hψ_ne) 2
  by_contra hlam
  exact absurd h0 (not_le.mpr (mul_neg_of_neg_of_pos (not_le.mp hlam) hnorm))

/-- `−Δ` on `L²(ℝ³)` has no eigenvalues (purely continuous spectrum).

If `−Δψ = λψ` then in Fourier space `(|ξ|² − λ)ψ̂ = 0`, so `ψ̂` is supported on the
sphere `{|ξ|² = λ}`, a Lebesgue-null set in `ℝ³`; hence `ψ̂ = 0` a.e. and `ψ = 0`.
This needs the Fourier characterization of `−Δ` (see the note in `CoulombBound`
on `laplacian_range_add_I`), so it is left open. -/
theorem laplacian_no_eigenvalues
    (lam : ℝ) (ψ : L2_R3) (hψ : MemSobolevH2 ψ)
    (heig : weakLaplacian ψ hψ = (lam : ℂ) • ψ) :
    ψ = 0 :=
  sorry

/-- Resolvent bound: `‖(−Δ − z)⁻¹‖ ≤ 1/|Im z|`. Purely abstract — from the
resolvent estimate for self-adjoint operators, no Fourier analysis needed. -/
theorem laplacian_resolvent_bound (z : ℂ) (hz : z.im ≠ 0) :
    ‖selfAdjointResolvent laplacian_isSelfAdjoint z hz‖ ≤ 1 / |z.im| := by
  rw [selfAdjointResolvent_eq_genToGroup]
  exact resolvent_bound _ _ _ z hz

/-! ## The free Green's function

For explicit spectral computations we record the free Green's function
`G_z(x) = e^{−√(−z)|x|} / (4π|x|)`, with the principal branch of the square root
(so `Re √(−z) > 0` whenever `Im z ≠ 0`). Tying it to `selfAdjointResolvent`, and
the exponential decay, both require the radial Fourier computation, so the two
identities below are left open. -/

/-- The free Green's function `G_z(x) = e^{−√(−z)|x|}/(4π|x|)`, principal branch of
the square root; `0` at the origin. -/
def freeGreensFunction (z : ℂ) : R3 → ℂ := fun x =>
  if ‖x‖ = 0 then 0
  else Complex.exp (-((-z) ^ ((1 : ℂ) / 2)) * (‖x‖ : ℂ)) /
    ((4 * Real.pi * ‖x‖ : ℝ) : ℂ)

/-- The Green's function is the integral kernel of the free resolvent.

Verify `𝓕[G_z](ξ) = 1/(|ξ|² − z)` by the radial contour computation, then
Plancherel turns multiplication by `1/(|ξ|² − z)` into convolution with `G_z`.
Needs the Fourier characterization of `−Δ`; left open. -/
theorem freeGreensFunction_is_resolvent_kernel
    (z : ℂ) (hz : z.im ≠ 0) (f : L2_R3) :
    ∀ᵐ x : R3,
      (selfAdjointResolvent laplacian_isSelfAdjoint z hz f : R3 → ℂ) x =
      ∫ y, freeGreensFunction z (x - y) * (f : R3 → ℂ) y :=
  sorry

/-- The Green's function decays exponentially with rate `Re √(−z) > 0`.

Direct from the explicit formula: the witness is `c = Re((−z)^{1/2}) > 0`, since
`−z ∉ [0, ∞)` when `Im z ≠ 0` and the principal branch maps `ℂ ∖ [0, ∞)` into the
open right half-plane. Left open (elementary but `cpow`-fiddly). -/
theorem freeGreensFunction_decay (z : ℂ) (hz : z.im ≠ 0) :
    ∃ c : ℝ, 0 < c ∧ ∀ x : R3, x ≠ 0 →
      ‖freeGreensFunction z x‖ ≤
        Real.exp (-c * ‖x‖) / (4 * Real.pi * ‖x‖) := by
  have hz' : -z ≠ 0 := neg_ne_zero.mpr (by rintro rfl; simp at hz)
  set w : ℂ := (-z) ^ ((1 : ℂ) / 2) with hw
  refine ⟨w.re, ?_, ?_⟩
  · -- `Re((−z)^{1/2}) = ‖−z‖^{1/2}·cos(arg(−z)/2) > 0`, since `arg(−z) ∈ (−π, π)`.
    have harg_gt : -Real.pi < Complex.arg (-z) := Complex.neg_pi_lt_arg (-z)
    have harg_lt : Complex.arg (-z) < Real.pi := by
      rcases (Complex.arg_le_pi (-z)).lt_or_eq with h | h
      · exact h
      · exact absurd (Complex.arg_eq_pi_iff.mp h).2 (by simpa using hz)
    rw [hw, Complex.cpow_def_of_ne_zero hz', Complex.exp_re]
    refine mul_pos (Real.exp_pos _) ?_
    have h12 : ((1 : ℂ) / 2) = ((1 / 2 : ℝ) : ℂ) := by push_cast; ring
    have him : (Complex.log (-z) * ((1 : ℂ) / 2)).im = Complex.arg (-z) / 2 := by
      rw [h12, Complex.mul_im, Complex.ofReal_im, Complex.ofReal_re, Complex.log_im]; ring
    rw [him]
    exact Real.cos_pos_of_mem_Ioo ⟨by linarith, by linarith⟩
  · intro x hx
    have hxn : ‖x‖ ≠ 0 := norm_ne_zero_iff.mpr hx
    have hxpos : 0 < ‖x‖ := norm_pos_iff.mpr hx
    have hdenom_pos : 0 < 4 * Real.pi * ‖x‖ :=
      mul_pos (mul_pos (by norm_num) Real.pi_pos) hxpos
    refine le_of_eq ?_
    have hval : freeGreensFunction z x
        = Complex.exp (-w * (‖x‖ : ℂ)) / ((4 * Real.pi * ‖x‖ : ℝ) : ℂ) := by
      rw [freeGreensFunction, if_neg hxn, ← hw]
    have hre : (-w * (‖x‖ : ℂ)).re = -w.re * ‖x‖ := by
      simp [Complex.mul_re, Complex.ofReal_re, Complex.ofReal_im]
    rw [hval, norm_div, Complex.norm_exp, Complex.norm_real, Real.norm_eq_abs,
      abs_of_pos hdenom_pos, hre]

/-! ## Interface summary

### For `CoulombBound.lean`:
- `laplacianPMap` is the unperturbed `A`; `laplacianPMap.domain = SobolevH2`
  holds by `rfl`, so **no domain transport is needed**: a linear map
  `SobolevH2 →ₗ[ℂ] L2_R3` *is* a `laplacianPMap.domain →ₗ[ℂ] L2_R3`.
- `laplacianPMap_apply` bridges `laplacianPMap ⟨ψ, hψ⟩ ↔ weakLaplacian ψ hψ`
  (also `rfl`), so Hardy estimates in terms of `weakLaplacian` transfer
  verbatim to estimates in terms of `‖laplacianPMap ψ‖`.

### For `HydrogenHamiltonian.lean`:
- `kato_rellich_bound_zero laplacian_isSelfAdjoint V hV_sym hV₀ lam`
  produces `IsSelfAdjoint (perturbedOp laplacianPMap ((lam : ℂ) • V))`,
  i.e. self-adjointness of −Δ − Z/r on H²(ℝ³).
- `genToGroup` then yields the hydrogen evolution, and
  `spectralPVM`/`spectralTheorem` its spectral measure.

### Already available once `laplacian_isSelfAdjoint` is discharged:
- `selfAdjointResolvent laplacian_isSelfAdjoint` with norm ≤ 1/|Im z|;
- `spectralPVM laplacian_isSelfAdjoint` and `spectralPVM_resolvent_formula`;
- the unitary group `freeParticleGroup` with Stone's theorem.
-/

end Spectra.QuantumMechanics.Hydrogen
