/-
Copyright (c) 2026 Spectra Formalization Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Bornemann
-/
import Spectra.YosidaHille.Basic
import Spectra.QuantumMechanics.Generator.Basic
/-!
# The Schrödinger Equation

The Schrödinger equation emerges as a theorem from Stone's correspondence: the orbit of any
strongly continuous one-parameter unitary group, restricted to the domain of its generator `A`,
solves `ψ'(t) = i A ψ(t)`. No self-adjointness hypothesis is needed — the generator of such a
group is automatically self-adjoint (`generator_isSelfAdjoint`). The proof stitches together the
derivative of the orbit (`unitary_orbit_hasDerivAt`) with `generator_comm`, which moves `A` to the
outside (`A ψ(t)` rather than `U(t)(Aψ₀)`).

## Main results

* `schrodingerEquation`: the general-`t` form, stated directly from a raw
  `OneParameterUnitaryGroup` and its generator.
* `schrodingerEquation_zero`: the `t = 0` instance.
* `schrodinger_of_selfAdjoint`: the Hamiltonian-first form, stated from a bare `IsSelfAdjoint A`
  rather than a pre-built one-parameter group.

## Implementation notes

`schrodingerEquation` is the Stone-correspondence-direct entry point (raw
`OneParameterUnitaryGroup` input); `Spectra.Operator.SelfAdjointOperator.schrodingerEquation`
(`QuantumMechanics/Generator/Basic.lean`) is the bundled-observable entry point for the same
physics, built from Stone's theorem the other way around (starting from a self-adjoint operator).
`schrodinger_of_selfAdjoint` below is the Hamiltonian-first analogue of `schrodingerEquation`: it
is proved as a one-line corollary of `Spectra.Operator.SelfAdjointOperator.schrodingerEquation` by
bundling `⟨A, hA⟩` into a `SelfAdjointOperator`, rather than re-deriving the derivative from
scratch.

## References
* Schrödinger, "Quantisierung als Eigenwertproblem" (1926)
* Stone, "On one-parameter unitary groups in Hilbert space" (1932)
-/
open InnerProductSpace Complex Filter Topology
open Spectra.YosidaHille
open Spectra.OneParameterUnitaryGroup
variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
namespace Spectra.QuantumMechanics.Schrodinger

/-- **The Schrödinger equation.** For `ψ₀` in the domain of the generator `A := generator U_grp`,
the orbit `s ↦ U(s)ψ₀` is differentiable at every `t` with `d/ds U(s)ψ₀ = i A (U(t)ψ₀)`. -/
theorem schrodingerEquation (U_grp : OneParameterUnitaryGroup (H := H))
    (ψ₀ : H) (hψ₀ : ψ₀ ∈ (generator U_grp).domain) (t : ℝ) :
    HasDerivAt (fun s : ℝ => U_grp.U s ψ₀)
      (I • generator U_grp ⟨U_grp.U t ψ₀, generator_domain_invariant U_grp t ⟨ψ₀, hψ₀⟩⟩) t := by
  have h := unitary_orbit_hasDerivAt U_grp ⟨ψ₀, hψ₀⟩ t
  rwa [← generator_comm U_grp t ⟨ψ₀, hψ₀⟩] at h

/-- **The Schrödinger equation at the origin.** The `t = 0` instance of `schrodingerEquation`. -/
theorem schrodingerEquation_zero (U_grp : OneParameterUnitaryGroup (H := H))
    (ψ₀ : H) (hψ₀ : ψ₀ ∈ (generator U_grp).domain) :
    HasDerivAt (fun t : ℝ => U_grp.U t ψ₀)
      (I • generator U_grp ⟨U_grp.U 0 ψ₀, generator_domain_invariant U_grp 0 ⟨ψ₀, hψ₀⟩⟩) 0 :=
  schrodingerEquation U_grp ψ₀ hψ₀ 0

/-- The evolution generated by a self-adjoint `A` preserves `dom A`. Transports
`generator_domain_invariant` across the round-trip `generator (genToGroup hA) = A`. -/
lemma genToGroup_domain_invariant {A : H →ₗ.[ℂ] H} (hA : IsSelfAdjoint A)
    (t : ℝ) (ψ₀ : H) (hψ₀ : ψ₀ ∈ A.domain) :
    (genToGroup hA).U t ψ₀ ∈ A.domain := by
  have hdom : (generator (genToGroup hA)).domain = A.domain := by rw [generator_genToGroup hA]
  rw [← hdom]
  exact generator_domain_invariant (genToGroup hA) t ⟨ψ₀, by rw [hdom]; exact hψ₀⟩

/-- **The Schrödinger equation, Hamiltonian-first.** Given a self-adjoint `A` and
`ψ₀ ∈ dom A`, the evolution `s ↦ (genToGroup hA).U s ψ₀` (i.e. `e^{isA}ψ₀`) solves
`ψ'(t) = i A ψ(t)` — with `A` applied to the evolved state, on the nose.

A one-line corollary of `Spectra.Operator.SelfAdjointOperator.schrodingerEquation`
(`QuantumMechanics/Generator/Basic.lean`), bundling `⟨A, hA⟩` into a `SelfAdjointOperator`. -/
theorem schrodinger_of_selfAdjoint {A : H →ₗ.[ℂ] H} (hA : IsSelfAdjoint A)
    (ψ₀ : H) (hψ₀ : ψ₀ ∈ A.domain) (t : ℝ) :
    HasDerivAt (fun s => (genToGroup hA).U s ψ₀)
      (I • A ⟨(genToGroup hA).U t ψ₀, genToGroup_domain_invariant hA t ψ₀ hψ₀⟩) t :=
  Spectra.Operator.SelfAdjointOperator.schrodingerEquation
    (⟨A, hA⟩ : Spectra.Operator.SelfAdjointOperator H) hψ₀ t

end Spectra.QuantumMechanics.Schrodinger
