/-
Copyright (c) 2026 Spectra Formalization Project. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Adam Bornemann
Filename: UnitaryEvolution/Stone/Converse.lean
-/
import Spectra.UnitaryEvolution.Stone.Helpers
import Spectra.UnitaryEvolution.Yosida.Exponential
/-!
# Stone's lemma: Complete Statement

This file assembles the complete Stone's lemma, establishing a bijective
correspondence between strongly continuous one-parameter unitary groups and
self-adjoint operators on a Hilbert space.

## References

* [Stone, "On one-parameter unitary groups in Hilbert space"][stone1932]
* [von Neumann, "Über Funktionen von Funktionaloperatoren"][vonneumann1932]
* [Reed, Simon, *Methods of Modern Mathematical Physics I*][reed1980], lemma VIII.8

## Tags

Stone's lemma, unitary group, self-adjoint operator, spectral theory
-/
namespace QuantumMechanics.Stoneslemma

open InnerProductSpace Complex Filter Topology
open Yosida Resolvent Bochner
open scoped ComplexConjugate

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]


/-- The strongly continuous one-parameter unitary group generated by a self-adjoint
operator, built from the Yosida exponential. -/
noncomputable def genToGroup {A : H →ₗ.[ℂ] H} (hA : IsSelfAdjoint A) :
    OneParameterUnitaryGroup (H := H) :=
  let hsym : A.IsFormalAdjoint A := by
    have h := LinearPMap.adjoint_isFormalAdjoint hA.dense_domain
    rwa [LinearPMap.isSelfAdjoint_def.mp hA] at h
  let hplus  := (isSelfAdjoint_to_surjective hA).1
  let hminus := (isSelfAdjoint_to_surjective hA).2
  let hd     := hA.dense_domain
  { U := fun t => exponential hsym hplus hminus hd t
    unitary := fun t ψ φ => exponential_unitary hsym hplus hminus hd t ψ φ
    group_law := fun s t => ContinuousLinearMap.ext fun ψ => by
      rw [ContinuousLinearMap.comp_apply]
      exact exponential_group_law hsym hplus hminus hd s t ψ
    identity := ContinuousLinearMap.ext fun ψ => by
      rw [ContinuousLinearMap.id_apply]
      exact exponential_identity hsym hplus hminus hd ψ
    strong_continuous := fun ψ => exponential_strong_continuous hsym hplus hminus hd ψ }

/-- Round-trip 2 (`gen ∘ exp = id`): the generator of the constructed group is `A`. -/
lemma generator_genToGroup {A : H →ₗ.[ℂ] H} (hA : IsSelfAdjoint A) :
    generator (genToGroup hA) = A := by
  -- re-derive the four hypotheses; proof-irrelevance makes them defeq to genToGroup's `let`s
  have hsym : A.IsFormalAdjoint A := by
    have h := LinearPMap.adjoint_isFormalAdjoint hA.dense_domain
    rwa [LinearPMap.isSelfAdjoint_def.mp hA] at h
  have hplus  := (isSelfAdjoint_to_surjective hA).1
  have hminus := (isSelfAdjoint_to_surjective hA).2
  have hd     := hA.dense_domain
  -- (1)  A ≤ generator (genToGroup hA)
  have hAle : A ≤ generator (genToGroup hA) := by
    refine ⟨fun z hz => ?_, fun x y hxy => ?_⟩
    · -- domain inclusion: genDiffQuot (genToGroup hA) z → A⟨z,hz⟩
      rw [generator_domain, mem_generatorDomain]
      exact ⟨A ⟨z, hz⟩, exponential_generator_eq' hsym hplus hminus hd z hz⟩
    · -- value agreement, by uniqueness of limits
      have hgen : Tendsto (genDiffQuot (genToGroup hA) (x : H)) (𝓝[≠] 0)
          (𝓝 (generator (genToGroup hA) y)) := by
        rw [hxy]; exact generator_tendsto (genToGroup hA) y
      exact tendsto_nhds_unique
        (exponential_generator_eq' hsym hplus hminus hd (x : H) x.2) hgen
  -- (2)  generator (genToGroup hA) is self-adjoint — free, via A's deficiency + hAle
  have hSAgen : IsSelfAdjoint (generator (genToGroup hA)) := by
    have hdense' : Dense ((generator (genToGroup hA)).domain : Set H) :=
      hd.mono (SetLike.coe_subset_coe.mpr hAle.1)
    refine isSelfAdjoint_of_surjective_addSub _ (generator_isFormalAdjoint _) hdense' ?_ ?_
    · intro φ
      obtain ⟨ψ, hψ⟩ := hplus φ
      refine ⟨⟨(ψ : H), hAle.1 ψ.2⟩, ?_⟩
      rw [← hAle.2 (x := ψ) (y := ⟨(ψ : H), hAle.1 ψ.2⟩) rfl]; exact hψ
    · intro φ
      obtain ⟨ψ, hψ⟩ := hminus φ
      refine ⟨⟨(ψ : H), hAle.1 ψ.2⟩, ?_⟩
      rw [← hAle.2 (x := ψ) (y := ⟨(ψ : H), hAle.1 ψ.2⟩) rfl]; exact hψ
  -- (3)  maximality: A self-adjoint, gen self-adjoint, A ≤ gen ⟹ equal
  exact Eq.symm (IsSelfAdjoint.eq_of_le hA hSAgen hAle)


end QuantumMechanics.Stoneslemma
