/-
Copyright (c) 2026 Logos Library Formalization Project. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Adam Bornemann
Filename: QuantumMechanics/SpectralTheory/SpectralAxiom.lean
-/
import Spectra.UnitaryEvolution.Stone.Bijection
import Mathlib.MeasureTheory.Integral.Bochner.Basic

/-!
# The Spectral Axiom

This file contains **the single axiom** required to complete Bochner's theorem
via the GNS-Stone route.

## Statement

For any strongly continuous one-parameter unitary group `U(t)` on a Hilbert
space `H` and any vector `ξ ∈ H`, there exists a finite positive Borel measure
`μ` on `ℝ` such that:

  `⟨ξ, U(t)ξ⟩ = ∫ e^{itlambda} dμ(lambda)`    for all `t ∈ ℝ`

with `μ(ℝ) = ‖ξ‖²`.

## Mathematical status

This is a consequence of the **spectral theorem for self-adjoint operators**.
The full theorem asserts that every self-adjoint operator `A` admits a
projection-valued measure `E` on `ℝ` with `A = ∫ lambda dE(lambda)`. Given `U(t) = e^{itA}`
(Stone's theorem, **proved** in `UnitaryEvo/Stone.lean`), the scalar spectral
measure is `μ_ξ(S) = ⟨E(S)ξ, ξ⟩`, and the representation formula follows from
the functional calculus.

## Discharge plan

This axiom will be discharged by proving the spectral theorem for unbounded
self-adjoint operators. Candidate routes (all independent of Bochner):

1. **Cayley route**: The Cayley transform `U = (A-i)(A+i)⁻¹` is unitary
   (proved in `CayleyTransform/Transform.lean`). The spectral theorem for
   bounded unitary operators (via continuous functional calculus on C*-algebras,
   or direct construction) gives a PVM for `U` on `𝕋`. Pull back via the
   inverse Möbius map to get the PVM for `A` on `ℝ`.

2. **Resolution of the identity**: Construct `E((-∞, lambda])` directly as the
   strong limit of `(2πi)⁻¹ ∫_C R(z) dz` around the spectrum below `lambda`.

3. **Commutative C*-algebra**: The C*-algebra generated by `(A-i)⁻¹` is
   commutative; Gelfand's theorem gives a spectral measure.

Once discharged, `#print axioms bochner_theorem` will show only the three
standard Lean axioms (`propext`, `Quot.sound`, `Classical.choice`).

## Downstream usage

This axiom is used exactly once: in `Spectral.lean` to produce the
representing measure for Bochner's theorem. The full proof chain is:

  `IsContinuous f`
    →  GNS construction   (`GNS/PreHilbert.lean`, `GNS/Completion.lean`)
    →  Hilbert space H, unitary group U(t), cyclic vector ξ
    →  f(t) = ⟨ξ, U(t)ξ⟩
    →  **this axiom** produces measure μ
    →  f(t) = ∫ e^{itlambda} dμ(lambda)

Combined with Fourier uniqueness (**proved**, `Fourier/Unique.lean`), this
gives the complete Bochner theorem.

## Tags

spectral theorem, axiom, projection-valued measure, scalar spectral measure
-/
namespace QuantumMechanics

open Complex MeasureTheory Filter Topology
open QuantumMechanics.StonesTheorem


/-- **The Spectral Axiom.**

For any strongly continuous one-parameter unitary group on a complex
Hilbert space and any vector ξ, there exists a finite positive Borel
measure μ on ℝ such that `⟨ξ, U(t)ξ⟩ = ∫ e^{itlambda} dμ(lambda)`.

This is a consequence of the spectral theorem for self-adjoint operators.
It will be discharged when the spectral theorem is formalized. -/
axiom spectral_scalar_measure_exists
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    (U_grp :  OneParameterUnitaryGroup (H := H))
    (ξ : H) :
    ∃ (μ : Measure ℝ), IsFiniteMeasure μ ∧
      (∀ t : ℝ, @inner ℂ H _ ξ (U_grp.U t ξ) =
        ∫ lambda, exp (I * ↑lambda * ↑t) ∂μ)

end QuantumMechanics
