/-
Copyright (c) 2026 Spectra Project. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Adam Bornemann
Filename: QuantumMechanics/Generator.lean
Target: Mathlib v4.31.0-rc1
-/
import Spectra.Stone.Basic
import Spectra.QuantumMechanics.Observable.Basic
import Spectra.Resolvent.Integral.Domain
/-!
# The Generator as a Quantum Observable

With Stone's theorem complete, the infinitesimal generator of a strongly
continuous one-parameter unitary group is *known* to be self-adjoint —
which is precisely the single field of `UnboundedObservable`.  This file
is the thin, physics-facing layer that packages that fact.  The
construction of the generator itself lives in `Stone/`; nothing here
re-proves analysis.

## Main definitions

* `OneParameterUnitaryGroup.generatorObservable` — the generator, bundled
  as an `UnboundedObservable` (the *Hamiltonian* of the dynamics).
* `UnboundedObservable.evolution` — the unitary group `t ↦ exp(itA)`
  generated by an observable (Schrödinger time evolution).
* `stoneObservableEquiv` — **Stone's theorem, observable form**:
  `OneParameterUnitaryGroup H ≃ UnboundedObservable H`.

## Main results

* `UnboundedObservable.schrodingerEquation` — for `ψ ∈ dom A`, the orbit
  `t ↦ exp(itA)ψ` solves `dψ/dt = i A ψ(t)`.
* `UnboundedObservable.evolution_mem_domain` — the evolution preserves
  the domain of its Hamiltonian.
* `OneParameterUnitaryGroup.inner_generator_invariant` — conservation of
  energy: `⟪U_t ψ, A (U_t ψ)⟫ = ⟪ψ, A ψ⟫`.
* `existsUnique_hamiltonian` — every quantum dynamics has exactly one
  Hamiltonian.

## Design notes

The round-trip identities of `stoneEquiv` (in `Stone/Converse.lean`) do
all the work; the only genuinely new ingredients here are two trivial
helpers: extensionality for `UnboundedObservable` (two observables with
the same `LinearPMap` are equal — the self-adjointness field is a `Prop`)
and transport of a `LinearPMap` application along an equality of
operators.  Both are candidates for relocation (`Observable/Basic.lean`
and an `Operator/` helper file respectively) once this compiles.

Sign convention: `genDiffQuot` divides by `it`, so `generator U = A`
means `U t = exp(itA)` and the orbit derivative is `i·Aψ`.

## Tags

Stone's theorem, generator, Hamiltonian, Schrödinger equation, unitary group
-/
open InnerProductSpace Complex Filter Topology
open scoped ComplexConjugate

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
open Spectra.Resolvent
open Spectra.OneParameterUnitaryGroup Spectra.Stoneslemma Spectra.StonesTheorem
namespace Spectra.QuantumMechanics

open Observable UnboundedObservable

/-! ### Helpers (candidates for relocation) -/

/-- Two observables with the same underlying `LinearPMap` are equal.
The `selfAdjoint` field is a `Prop`, so this is proof irrelevance.
*(Move to `Observable/Basic.lean`.)* -/
@[ext] lemma Observable.UnboundedObservable.ext
    {A B : UnboundedObservable H}
    (h : A.toLinearPMap = B.toLinearPMap) : A = B := by
  cases A; cases B; cases h; rfl

omit [CompleteSpace H] in
/-- Transport a `LinearPMap` application along an equality of operators.
*(Move to an `Operator/` helper file.)* -/
lemma LinearPMap.apply_congr {f g : H →ₗ.[ℂ] H} (h : f = g)
    (x : H) (hx : x ∈ f.domain) :
    f ⟨x, hx⟩ = g ⟨x, h ▸ hx⟩ := by
  subst h; rfl

/-! ### The generator as an observable -/
end QuantumMechanics

namespace OneParameterUnitaryGroup
open QuantumMechanics.Observable UnboundedObservable
/-- The infinitesimal generator of a one-parameter unitary group, bundled
as a genuine quantum observable.  Self-adjointness is the hard half of
Stone's theorem (`generator_isSelfAdjoint`); this definition is pure
packaging. -/
noncomputable def generatorObservable (U : OneParameterUnitaryGroup (H := H)) :
    UnboundedObservable H where
  toLinearPMap := generator U
  selfAdjoint := generator_isSelfAdjoint U

@[simp] lemma generatorObservable_toLinearPMap
    (U : OneParameterUnitaryGroup (H := H)) :
    U.generatorObservable.toLinearPMap = generator U := rfl

@[simp] lemma generatorObservable_domain
    (U : OneParameterUnitaryGroup (H := H)) :
    U.generatorObservable.domain = (generator U).domain := rfl

/-- **Conservation of energy** along the orbit: the quadratic form of the
generator is invariant under the flow it generates,
`⟪U_t ψ, A (U_t ψ)⟫ = ⟪ψ, A ψ⟫`.

Proof: the commutation `A (U_t ψ) = U_t (A ψ)` (`generator_comm`)
followed by unitarity. -/
theorem inner_generator_invariant (U : OneParameterUnitaryGroup (H := H))
    (ψ : (generator U).domain) (t : ℝ) :
    ⟪U.U t (ψ : H),
      generator U ⟨U.U t (ψ : H), generator_domain_invariant U t ψ⟩⟫_ℂ =
    ⟪(ψ : H), generator U ψ⟫_ℂ := by
  rw [generator_comm]
  exact U.unitary t (ψ : H) (generator U ψ)

end OneParameterUnitaryGroup

/-! ### Schrödinger time evolution of an observable -/

namespace QuantumMechanics.Observable.UnboundedObservable

/-- The strongly continuous unitary group `t ↦ exp(itA)` generated by an
observable: **Schrödinger time evolution** with Hamiltonian `A`. -/
noncomputable def evolution (A : UnboundedObservable H) :
    OneParameterUnitaryGroup (H := H) :=
  genToGroup A.selfAdjoint

/-- The generator of the evolution of `A` is `A` itself
(round trip `gen ∘ exp = id` of Stone's theorem). -/
lemma generator_evolution (A : UnboundedObservable H) :
    generator A.evolution = A.toLinearPMap :=
  generator_genToGroup A.selfAdjoint

@[simp] lemma generatorObservable_evolution (A : UnboundedObservable H) :
    A.evolution.generatorObservable = A :=
  UnboundedObservable.ext A.generator_evolution

/-- The domain of the generator of `A.evolution` is the domain of `A`. -/
lemma evolution_generator_domain (A : UnboundedObservable H) :
    (generator A.evolution).domain = A.domain :=
  congrArg LinearPMap.domain A.generator_evolution

/-- The evolution preserves the domain of its Hamiltonian:
`ψ ∈ dom A → exp(itA) ψ ∈ dom A`. -/
lemma evolution_mem_domain (A : UnboundedObservable H) {ψ : H}
    (hψ : ψ ∈ A.domain) (t : ℝ) :
    A.evolution.U t ψ ∈ A.domain := by
  rw [← A.evolution_generator_domain] at hψ ⊢
  exact generator_domain_invariant A.evolution t ⟨ψ, hψ⟩

/-- **The Schrödinger equation.**  For `ψ ∈ dom A`, the orbit
`t ↦ exp(itA) ψ` is differentiable with derivative `i · A ψ(t)`, the
membership proof being supplied by domain invariance. -/
lemma schrodingerEquation (A : UnboundedObservable H) {ψ : H}
    (hψ : ψ ∈ A.domain) (t : ℝ) :
    HasDerivAt (fun s => A.evolution.U s ψ)
      (I • A.toLinearPMap
        ⟨A.evolution.U t ψ, A.evolution_mem_domain hψ t⟩) t := by
  have hψ' : ψ ∈ (generator A.evolution).domain :=
    A.evolution_generator_domain.symm ▸ hψ
  have h := stone_orbit_hasDerivAt A.evolution ⟨ψ, hψ'⟩ t
  rwa [LinearPMap.apply_congr A.generator_evolution] at h

end UnboundedObservable

/-- **Stone's theorem.** Every self-adjoint operator on `H` is the infinitesimal
generator of exactly one strongly continuous one-parameter unitary group. -/
theorem exists_unique_generator {A : H →ₗ.[ℂ] H} (hA : IsSelfAdjoint A) :
    ∃! U : OneParameterUnitaryGroup (H := H), generator U = A :=
  ⟨genToGroup hA, generator_genToGroup hA,
   fun U hU => group_unique U (genToGroup hA) (hU.trans (generator_genToGroup hA).symm)⟩

/-! ### Stone's theorem, observable form -/

/-- **Stone's theorem (observable form).**  Strongly continuous
one-parameter unitary groups on `H` correspond bijectively to quantum
observables: every group has a self-adjoint generator, and every
self-adjoint operator generates a unique group. -/
noncomputable def stoneObservableEquiv :
    OneParameterUnitaryGroup (H := H) ≃ UnboundedObservable H where
  toFun U := U.generatorObservable
  invFun A := A.evolution
  left_inv U := group_unique _ _
    (generator_genToGroup (generator_isSelfAdjoint U))
  right_inv A := A.generatorObservable_evolution

@[simp] lemma stoneObservableEquiv_apply
    (U : OneParameterUnitaryGroup (H := H)) :
    stoneObservableEquiv U = U.generatorObservable := rfl

@[simp] lemma stoneObservableEquiv_symm_apply (A : UnboundedObservable H) :
    stoneObservableEquiv.symm A = A.evolution := rfl

/-- Every strongly continuous one-parameter unitary group is generated by
a **unique** observable — every quantum dynamics has exactly one
Hamiltonian. -/
lemma existsUnique_hamiltonian (U : OneParameterUnitaryGroup (H := H)) :
    ∃! A : UnboundedObservable H, A.evolution = U :=
  ⟨U.generatorObservable, stoneObservableEquiv.left_inv U,
   fun A hA => by rw [← hA]; exact A.generatorObservable_evolution.symm⟩

end Spectra.QuantumMechanics.Observable
