/-
Copyright (c) 2026 Spectra Formalization Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Bornemann
-/
import Spectra.YosidaHille.Basic
import Spectra.Operator.SelfAdjoint
import Spectra.Resolvent.Integral.Domain
/-!
# The Generator as a Quantum Observable

With Stone's theorem complete, the infinitesimal generator of a strongly
continuous one-parameter unitary group is *known* to be self-adjoint —
which is precisely the single field of `SelfAdjointOperator`.  This file
is the thin, physics-facing layer that packages that fact.  The
generator itself is defined in `OneParameterUnitaryGroup/Basic.lean`, and
Stone's theorem (self-adjointness, the round-trip identities with
`genToGroup`) is proved in `Spectra/YosidaHille/Basic.lean`; nothing here
re-proves analysis.

## Main definitions

* `OneParameterUnitaryGroup.generatorObservable` — the generator, bundled
  as a `SelfAdjointOperator` (the *Hamiltonian* of the dynamics).
* `SelfAdjointOperator.evolution` — the unitary group `t ↦ exp(itA)`
  generated by an observable (Schrödinger time evolution).
* `stoneObservableEquiv` — **Stone's theorem, observable form**:
  `OneParameterUnitaryGroup H ≃ SelfAdjointOperator H`.

## Main results

* `SelfAdjointOperator.schrodingerEquation` — for `ψ ∈ dom A`, the orbit
  `t ↦ exp(itA)ψ` solves `dψ/dt = i A ψ(t)`.
* `SelfAdjointOperator.evolution_mem_domain` — the evolution preserves
  the domain of its Hamiltonian.
* `OneParameterUnitaryGroup.inner_generator_invariant` — conservation of
  energy: `⟪U_t ψ, A (U_t ψ)⟫ = ⟪ψ, A ψ⟫`.
* `Spectra.QuantumMechanics.Observable.exists_unique_generator` — **Stone's
  theorem** in raw `LinearPMap` form: every self-adjoint operator is the
  generator of exactly one one-parameter unitary group.
* `existsUnique_hamiltonian` — every quantum dynamics has exactly one
  Hamiltonian.

## Design notes

The round-trip identities of `stoneEquiv` (`stone_orbit_hasDerivAt`,
`generator_genToGroup`, `group_unique`, in `Spectra/YosidaHille/Basic.lean`)
do all the work; the genuinely new content here is the physics packaging:
`schrodingerEquation`, `inner_generator_invariant`, and
`evolution_mem_domain` translate those round-trip identities into the
Schrödinger equation and energy conservation, plus a small transport
helper (`LinearPMap.apply_congr`) for rewriting along the `generator = A`
identity. Extensionality for `SelfAdjointOperator` lives directly in
`Operator/SelfAdjoint.lean` alongside the structure.

Sign convention: `genDiffQuot` divides by `it`, so `generator U = A`
means `U t = exp(itA)` and the orbit derivative is `i·Aψ`.

## Tags

Stone's theorem, generator, Hamiltonian, Schrödinger equation, unitary group
-/
open InnerProductSpace Complex
open scoped ComplexConjugate

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
open Spectra.Resolvent
open Spectra.OneParameterUnitaryGroup Spectra.YosidaHille

omit [CompleteSpace H] in
/-- Transport a `LinearPMap` application along an equality of operators. -/
lemma _root_.LinearPMap.apply_congr {f g : H →ₗ.[ℂ] H} (h : f = g)
    (x : H) (hx : x ∈ f.domain) :
    f ⟨x, hx⟩ = g ⟨x, h ▸ hx⟩ := by
  subst h; rfl

namespace Spectra.QuantumMechanics

/-! ### The generator as an observable -/

end QuantumMechanics

namespace OneParameterUnitaryGroup
open Spectra.Operator SelfAdjointOperator
/-- The infinitesimal generator of a one-parameter unitary group, bundled
as a genuine quantum observable.  Self-adjointness is the hard half of
Stone's theorem (`generator_isSelfAdjoint`); this definition is pure
packaging. -/
noncomputable def generatorObservable (U : OneParameterUnitaryGroup (H := H)) :
    SelfAdjointOperator H where
  toLinearPMap := generator U
  selfAdjoint := generator_isSelfAdjoint U

@[simp] lemma generatorObservable_toLinearPMap
    (U : OneParameterUnitaryGroup (H := H)) :
    U.generatorObservable.toLinearPMap = generator U := rfl

@[simp] lemma generatorObservable_domain
    (U : OneParameterUnitaryGroup (H := H)) :
    U.generatorObservable.domain = (generator U).domain := rfl

/-- **Conservation of energy** along the orbit: the quadratic form of the
generator is invariant under the flow it generates,
`⟪U_t ψ, A (U_t ψ)⟫ = ⟪ψ, A ψ⟫`.

Proof: the commutation `A (U_t ψ) = U_t (A ψ)` (`generator_comm`)
followed by unitarity. -/
theorem inner_generator_invariant (U : OneParameterUnitaryGroup (H := H))
    (ψ : (generator U).domain) (t : ℝ) :
    ⟪U.U t (ψ : H),
      generator U ⟨U.U t (ψ : H), generator_domain_invariant U t ψ⟩⟫_ℂ =
    ⟪(ψ : H), generator U ψ⟫_ℂ := by
  rw [generator_comm]
  exact U.unitary t (ψ : H) (generator U ψ)

end OneParameterUnitaryGroup

open Spectra.Operator SelfAdjointOperator

/-! ### Schrödinger time evolution of an observable -/

/-- The strongly continuous unitary group `t ↦ exp(itA)` generated by an
observable: **Schrödinger time evolution** with Hamiltonian `A`. -/
noncomputable def _root_.Spectra.Operator.SelfAdjointOperator.evolution
    (A : SelfAdjointOperator H) : OneParameterUnitaryGroup (H := H) :=
  genToGroup A.selfAdjoint

/-- The generator of the evolution of `A` is `A` itself
(round trip `gen ∘ exp = id` of Stone's theorem). -/
lemma _root_.Spectra.Operator.SelfAdjointOperator.generator_evolution
    (A : SelfAdjointOperator H) :
    generator A.evolution = A.toLinearPMap :=
  generator_genToGroup A.selfAdjoint

@[simp] lemma _root_.Spectra.Operator.SelfAdjointOperator.generatorObservable_evolution
    (A : SelfAdjointOperator H) :
    A.evolution.generatorObservable = A :=
  SelfAdjointOperator.ext A.generator_evolution

/-- The domain of the generator of `A.evolution` is the domain of `A`. -/
lemma _root_.Spectra.Operator.SelfAdjointOperator.evolution_generator_domain
    (A : SelfAdjointOperator H) :
    (generator A.evolution).domain = A.domain :=
  congrArg LinearPMap.domain A.generator_evolution

/-- The evolution preserves the domain of its Hamiltonian:
`ψ ∈ dom A → exp(itA) ψ ∈ dom A`. -/
lemma _root_.Spectra.Operator.SelfAdjointOperator.evolution_mem_domain
    (A : SelfAdjointOperator H) {ψ : H}
    (hψ : ψ ∈ A.domain) (t : ℝ) :
    A.evolution.U t ψ ∈ A.domain := by
  rw [← A.evolution_generator_domain] at hψ ⊢
  exact generator_domain_invariant A.evolution t ⟨ψ, hψ⟩

/-- **The Schrödinger equation.**  For `ψ ∈ dom A`, the orbit
`t ↦ exp(itA) ψ` is differentiable with derivative `i · A ψ(t)`, the
membership proof being supplied by domain invariance. -/
lemma _root_.Spectra.Operator.SelfAdjointOperator.schrodingerEquation
    (A : SelfAdjointOperator H) {ψ : H}
    (hψ : ψ ∈ A.domain) (t : ℝ) :
    HasDerivAt (fun s => A.evolution.U s ψ)
      (I • A.toLinearPMap
        ⟨A.evolution.U t ψ, A.evolution_mem_domain hψ t⟩) t := by
  have hψ' : ψ ∈ (generator A.evolution).domain :=
    A.evolution_generator_domain.symm ▸ hψ
  have h := stone_orbit_hasDerivAt A.evolution ⟨ψ, hψ'⟩ t
  rwa [(generator A.evolution).apply_congr A.generator_evolution] at h

namespace QuantumMechanics.Observable

/-- **Stone's theorem.** Every self-adjoint operator on `H` is the infinitesimal
generator of exactly one strongly continuous one-parameter unitary group. -/
theorem exists_unique_generator {A : H →ₗ.[ℂ] H} (hA : IsSelfAdjoint A) :
    ∃! U : OneParameterUnitaryGroup (H := H), generator U = A :=
  ⟨genToGroup hA, generator_genToGroup hA,
   fun U hU => group_unique U (genToGroup hA) (hU.trans (generator_genToGroup hA).symm)⟩

/-! ### Stone's theorem, observable form -/

/-- **Stone's theorem (observable form).**  Strongly continuous
one-parameter unitary groups on `H` correspond bijectively to quantum
observables: every group has a self-adjoint generator, and every
self-adjoint operator generates a unique group. -/
noncomputable def stoneObservableEquiv :
    OneParameterUnitaryGroup (H := H) ≃ SelfAdjointOperator H where
  toFun U := U.generatorObservable
  invFun A := A.evolution
  left_inv U := group_unique _ _
    (generator_genToGroup (generator_isSelfAdjoint U))
  right_inv A := A.generatorObservable_evolution

@[simp] lemma stoneObservableEquiv_apply
    (U : OneParameterUnitaryGroup (H := H)) :
    stoneObservableEquiv U = U.generatorObservable := rfl

@[simp] lemma stoneObservableEquiv_symm_apply (A : SelfAdjointOperator H) :
    stoneObservableEquiv.symm A = A.evolution := rfl

/-- Every strongly continuous one-parameter unitary group is generated by
a **unique** observable — every quantum dynamics has exactly one
Hamiltonian. -/
lemma existsUnique_hamiltonian (U : OneParameterUnitaryGroup (H := H)) :
    ∃! A : SelfAdjointOperator H, A.evolution = U :=
  ⟨U.generatorObservable, stoneObservableEquiv.left_inv U,
   fun A hA => by rw [← hA]; exact A.generatorObservable_evolution.symm⟩

end Spectra.QuantumMechanics.Observable
